import { useState } from "react";
import { Link } from "react-router-dom";
import { CommercialLandingLayout, LandingPrimaryCta } from "@/components/marketing/CommercialLandingLayout";
import { Seo } from "@/components/Seo";
import { getRouteSeo } from "@/content/routesSeo";

const primaryCta = "/signup?intent=scan";

function ReceiptSlip({ compact = false }: { compact?: boolean }) {
  return (
    <div className={`relative bg-white text-slate-800 shadow-xl ring-1 ring-slate-200 ${compact ? "w-44 rounded-xl p-4" : "w-full max-w-[250px] rounded-2xl p-5"}`}>
      <div className="text-center"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-slate-800">Harbor Market</p><p className="mt-1 text-[8px] text-slate-400">Purchase receipt</p></div>
      <div className="mt-4 space-y-2 border-y border-dashed border-slate-300 py-3 text-[8px]">
        <div className="flex justify-between"><span>Studio paper</span><span>$18.00</span></div>
        <div className="flex justify-between"><span>Ink cartridges</span><span>$42.00</span></div>
        <div className="flex justify-between"><span>Desk cable</span><span>$12.00</span></div>
      </div>
      <div className="mt-3 flex justify-between text-xs font-black"><span>Total</span><span>$78.12</span></div>
      <p className="mt-3 text-center text-[7px] uppercase tracking-wider text-slate-400">Sep 30, 2026</p>
    </div>
  );
}

function ExtractedFields({ compact = false }: { compact?: boolean }) {
  const fields = [["Merchant", "Harbor Market", "fa-store"], ["Total", "$78.12", "fa-dollar-sign"], ["Date", "Sep 30, 2026", "fa-calendar"], ["Category", "Office supplies", "fa-tags"]];
  return <div className={`rounded-2xl border border-teal-100 bg-white shadow-lg ${compact ? "p-3" : "p-5 sm:p-6"}`}><div className="flex items-center justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-wider text-teal-700">Extracted details</p><p className="mt-1 text-sm font-black text-slate-950">Ready for review</p></div><span className="flex h-9 w-9 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><i className="fas fa-check text-xs" aria-hidden /></span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{fields.map(([label, value, icon]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-2 text-[8px] font-bold uppercase tracking-wider text-slate-400"><i className={`fas ${icon} text-teal-600`} aria-hidden />{label}</div><p className="mt-1 truncate text-[10px] font-extrabold text-slate-800">{value}</p></div>)}</div></div>;
}

function ScannerHeroPreview() {
  return <div className="relative mx-auto max-w-2xl" role="img" aria-label="Receipt Cycle scanner capturing a receipt and preparing extracted fields for review">
    <div className="overflow-hidden rounded-[28px] border border-white/70 bg-white shadow-[0_28px_90px_rgba(15,118,110,0.22)] ring-1 ring-slate-200">
      <div className="flex items-center justify-between border-b border-slate-100 bg-slate-950 px-4 py-3 text-white"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-rose-300" /><span className="h-2.5 w-2.5 rounded-full bg-amber-300" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-300" /></div><p className="text-[10px] font-bold">Receipt capture</p><i className="fas fa-wand-magic-sparkles text-teal-300" aria-hidden /></div>
      <div className="grid min-h-[430px] gap-0 bg-[#edf8f4] sm:grid-cols-[0.86fr_1.14fr]">
        <div className="relative flex items-center justify-center overflow-hidden bg-slate-900 p-6">
          <div className="absolute inset-5 rounded-[24px] border-2 border-dashed border-teal-300/60" />
          <div className="absolute left-8 top-8 h-8 w-8 border-l-4 border-t-4 border-teal-300" /><div className="absolute right-8 top-8 h-8 w-8 border-r-4 border-t-4 border-teal-300" /><div className="absolute bottom-8 left-8 h-8 w-8 border-b-4 border-l-4 border-teal-300" /><div className="absolute bottom-8 right-8 h-8 w-8 border-b-4 border-r-4 border-teal-300" />
          <div className="relative -rotate-2"><ReceiptSlip compact /></div>
          <span className="absolute bottom-5 rounded-full bg-white/15 px-3 py-1.5 text-[9px] font-bold text-white backdrop-blur">Hold steady and keep the edges visible</span>
        </div>
        <div className="flex flex-col justify-center p-4 sm:p-6"><p className="text-[9px] font-extrabold uppercase tracking-[0.18em] text-teal-700">AI extraction complete</p><h3 className="mt-2 font-display text-xl font-bold text-slate-950">Check the details before saving</h3><p className="mt-2 text-[10px] leading-5 text-slate-500">The image stays connected to a reviewable expense draft.</p><div className="mt-4"><ExtractedFields compact /></div><div className="mt-3 flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-[9px] font-semibold text-amber-800"><i className="fas fa-eye" aria-hidden />Review suggested fields before continuing</div></div>
      </div>
    </div>
    <div className="absolute -bottom-5 -left-3 hidden rounded-2xl bg-white p-3 shadow-xl ring-1 ring-slate-200 sm:flex sm:items-center sm:gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-100 text-teal-700"><i className="fas fa-language" aria-hidden /></span><div><p className="text-[8px] font-bold uppercase text-slate-400">Detected language</p><p className="text-xs font-black">English</p></div></div>
  </div>;
}

function CaptureChoices() {
  return <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-950 p-5 text-white"><i className="fas fa-camera text-2xl text-teal-300" aria-hidden /><p className="mt-5 text-sm font-extrabold">Use the receipt camera</p><p className="mt-2 text-[10px] leading-5 text-slate-300">Frame the paper, control the flash, and capture the image while the receipt is still in hand.</p></div><div className="rounded-2xl border border-teal-100 bg-white p-5"><i className="fas fa-images text-2xl text-teal-700" aria-hidden /><p className="mt-5 text-sm font-extrabold">Choose an existing image</p><p className="mt-2 text-[10px] leading-5 text-slate-500">Select a receipt from the mobile gallery or upload a supported image from the web.</p></div></div>;
}

function ConfidencePreview() {
  return <div className="rounded-2xl bg-white p-5 shadow-lg ring-1 ring-slate-200"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">OCR review</p><p className="mt-1 font-display text-lg font-bold">Confidence: medium</p></div><span className="h-3 w-3 rounded-full bg-amber-400" /></div><div className="mt-5 space-y-3">{[["Merchant", "High"], ["Total", "High"], ["Date", "Review"], ["Category", "Suggested"]].map(([field, state], index) => <div key={field} className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-600">{field}</span><span className={`rounded-full px-2.5 py-1 text-[9px] font-extrabold ${index < 2 ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{state}</span></div>)}</div></div>;
}

function ReviewFormPreview() {
  return <div className="rounded-2xl bg-white p-5 shadow-lg ring-1 ring-slate-200"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-[9px] font-bold uppercase tracking-wider text-teal-700">Review expense</p><p className="mt-1 text-sm font-black">AI extracted this information</p></div><i className="fas fa-pen-to-square text-teal-700" aria-hidden /></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["Merchant", "Harbor Market"], ["Amount", "$78.12"], ["Date", "2026-09-30"], ["Payment", "Card"]].map(([label, value]) => <div key={label}><p className="text-[8px] font-bold uppercase text-slate-400">{label}</p><div className="mt-1 rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-bold text-slate-700">{value}</div></div>)}</div><button type="button" className="mt-4 min-h-10 w-full rounded-xl bg-teal-700 px-4 text-[10px] font-extrabold text-white">Continue to save expense</button></div>;
}

function SavedRecordPreview() {
  return <div className="rounded-2xl bg-slate-950 p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-teal-300">Saved transaction</p><p className="mt-1 font-display text-lg font-bold">Harbor Market</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-[9px] font-bold">Office supplies</span></div><p className="mt-5 text-3xl font-black text-rose-300">-$78.12</p><div className="mt-5 grid grid-cols-2 gap-2 text-[9px]"><div className="rounded-xl bg-white/10 p-3"><p className="text-slate-400">Receipt</p><p className="mt-1 font-bold">Attached</p></div><div className="rounded-xl bg-white/10 p-3"><p className="text-slate-400">Date</p><p className="mt-1 font-bold">Sep 30</p></div></div></div>;
}

function ScanJourneyVisual() {
  const steps = [["fa-camera", "Capture", "Receipt image"], ["fa-wand-magic-sparkles", "Read", "OCR and AI"], ["fa-pen", "Review", "Editable fields"], ["fa-folder-open", "Save", "Expense record"]];
  return <div className="relative mx-auto flex min-h-[660px] w-full max-w-md flex-col overflow-hidden rounded-[34px] bg-slate-950 p-6 text-white shadow-2xl sm:p-8" role="img" aria-label="Receipt image moving through OCR extraction, review, and expense saving">
    <div className="absolute -right-20 -top-16 h-56 w-56 rounded-full bg-teal-500/20 blur-2xl" /><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-teal-300">Receipt to record</p><h3 className="mt-3 font-display text-2xl font-bold">Four checkpoints keep the scan useful</h3></div>
    <div className="relative mt-8 flex flex-1 flex-col justify-between gap-4">{steps.map(([icon, title, detail], index) => <div key={title} className="relative flex items-center gap-4 rounded-2xl border border-white/10 bg-white/10 p-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-teal-500/20 text-teal-200"><i className={`fas ${icon}`} aria-hidden /></span><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Step {index + 1}</p><p className="mt-1 font-display text-lg font-bold">{title}</p><p className="text-xs text-slate-300">{detail}</p></div>{index < steps.length - 1 ? <span className="absolute -bottom-5 left-9 h-5 w-px bg-teal-400/50" /> : null}</div>)}</div>
    <div className="relative mt-7 rounded-2xl bg-white p-5 text-slate-900"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase text-slate-400">Result</p><p className="mt-1 font-display text-lg font-bold">Expense ready for your records</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><i className="fas fa-check" aria-hidden /></span></div></div>
  </div>;
}

export default function AiReceiptScannerLanding() {
  const seo = getRouteSeo("/ai-receipt-scanner");
  const [activeAudienceId, setActiveAudienceId] = useState("freelancers");
  const benefits = [
    ["fa-camera", "Capture while the receipt is available", "A receipt scanner app shortens the gap between paying and recording. Photograph the paper at the counter or choose a saved image before the slip reaches a pocket, glove box, or desk drawer."],
    ["fa-wand-magic-sparkles", "Turn the image into a working draft", "The AI receipt scanner app reads the visible purchase details and proposes structured fields. Merchant, total, date, time, category, payment method, currency, tax, and items appear when the source supports them."],
    ["fa-pen-to-square", "Correct the result before it becomes a record", "OCR is an assistant, not the final reviewer. Edit the amount, merchant, category, date, formatted text, or other available details before you continue to the expense form."],
    ["fa-receipt", "Keep evidence beside the transaction", "The receipt image or structured receipt data can stay with the saved transaction, making it easier to reopen the expense and understand where the numbers came from."],
    ["fa-magnifying-glass", "Find the expense after the paper is gone", "Once saved, the transaction can be searched and filtered by merchant, category, date, type, and amount. The scan becomes part of an organized record instead of an isolated photo."],
  ];
  const audiences = [
    { id: "freelancers", title: "Freelancers", body: "Use the scanner after client travel, coffee meetings, software purchases, or office-supply runs. A receipt organizer app is most useful when the image, reviewed total, category, and date remain attached to the same expense instead of being split between a camera roll and spreadsheet.", image: "/landing/audiences/scanner-freelancer.webp", alt: "Hand-drawn freelancer scanning a café receipt and reviewing extracted purchase fields" },
    { id: "field-service", title: "Field-service businesses", body: "Capture fuel, hardware, materials, and on-site purchases while the job context is still fresh. A business receipt scanner gives the owner a draft that can be checked before the cost joins the business records, reducing the need to decipher a faded slip days later.", image: "/landing/audiences/scanner-field-service.webp", alt: "Hand-drawn tradesperson scanning a hardware receipt beside a work van" },
    { id: "shop-owners", title: "Shop owners", body: "Scan supplier and operating receipts from the counter, gallery, or web upload. A digital receipt scanner can preserve the source image while proposing totals, tax, dates, and line items that the owner can compare against the paper before saving.", image: "/landing/audiences/scanner-shop-owner.webp", alt: "Hand-drawn shop owner scanning a supplier receipt and organizing extracted details" },
    { id: "operations", title: "Operations teams", body: "Create a repeatable handoff for receipts collected by more than one person. Receipt management software works better when every submitted image reaches the same review step, fields remain editable, and saved records can be found by the details the team already uses.", image: "/landing/audiences/scanner-operations.webp", alt: "Hand-drawn operations team reviewing scanned receipts and organized expense records" },
  ];
  const activeAudience = audiences.find((audience) => audience.id === activeAudienceId) ?? audiences[0];
  const faqItems = [
    ["What does an AI receipt scanner extract?", "Receipt Cycle can propose the merchant, total amount, date, time, payment method, category, currency, subtotal, tax, document type, detected language, confidence, tags, formatted receipt text, and line items when those details are visible. Results depend on the source image and must be reviewed."],
    ["Can I scan a receipt with my phone camera?", "Yes. The mobile flow includes a receipt camera with flash control. You can also choose an existing image from the gallery. On the web, supported receipt images can be uploaded for processing."],
    ["Can I edit the OCR result?", "Yes. The review screen is designed for correction. Check the merchant, amount, date, time, category, payment method, extracted text, and any line items before continuing to save the expense."],
    ["Does the scanner always capture tax and line items?", "No. Tax extraction and line-item extraction depend on what is visible and legible in the receipt image. A short, faded, folded, handwritten, or damaged receipt may return fewer fields or a lower confidence indicator."],
    ["Can I use the receipt scanner for taxes?", "You can use it to organize receipt images and reviewed expense details for later record preparation. Receipt Cycle does not determine deductions, file returns, provide tax advice, or guarantee that a record satisfies a tax authority or audit requirement."],
    ["Does Receipt Cycle support multilingual receipts?", "The scanner is designed to recognize multiple scripts and can display detected languages. Accuracy still varies with image quality, typography, handwriting, layout, and the OCR provider available when the scan runs."],
    ["Can I scan PDF receipts?", "The receipt camera and receipt-image upload flow are intended for supported image formats such as JPG and PNG. PDF statement import belongs to a separate upload workflow and should not be treated as receipt-camera OCR."],
  ];
  const resources = [
    { title: "What a receipt scanner actually does", description: "Understand the difference between capturing an image, reading text, proposing fields, and creating a usable expense record.", href: "/blog/what-is-a-receipt-scanner-freelancers-2026", icon: "fa-receipt" },
    { title: "How OCR reads receipt images", description: "See why lighting, sharpness, contrast, receipt layout, and review affect the quality of extracted details.", href: "/blog/how-ocr-receipt-scanning-works-ai-smarter", icon: "fa-eye" },
    { title: "From receipt scan to expense record", description: "Learn why capture and expense organization solve different parts of the same record-keeping job.", href: "/blog/expense-tracker-receipt-scanner-one-two-punch", icon: "fa-arrow-right-arrow-left" },
  ];

  return <CommercialLandingLayout ctaLabel="Scan your first receipt" ctaHref={primaryCta} announcement="Capture the receipt. Review the details. Save the expense.">
    {seo ? <Seo {...seo} /> : null}

    <section className="relative overflow-hidden bg-[#f7fbf9] py-16 sm:py-20 lg:py-24"><div className="absolute -right-24 top-8 h-80 w-80 rounded-full bg-teal-100/70 blur-3xl" /><div className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 sm:px-8 lg:grid-cols-[0.82fr_1.18fr] lg:gap-16"><div className="max-w-xl"><h1 className="text-balance font-display text-4xl font-bold leading-[1.04] tracking-[-0.04em] sm:text-5xl lg:text-[3.5rem]"><span className="block text-slate-950">AI receipt scanner for</span>{" "}<span className="mt-1 block text-teal-700">faster expense capture</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-600">Photograph or upload a receipt, extract the visible purchase details, and review the expense before it joins your records.</p><div className="mt-8"><LandingPrimaryCta to={primaryCta}>Scan your first receipt</LandingPrimaryCta><p className="mt-3 text-sm font-medium text-slate-500">No credit card required. Cancel paid plans anytime.</p></div></div><ScannerHeroPreview /></div></section>

    <section id="features" className="scroll-mt-28 bg-[#dff5ef] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Spend less time typing what the receipt already shows</h2><p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">Receipt capture should preserve the source, prepare the useful fields, and leave you in control of the final record.</p></div><div className="mt-12 grid gap-4 md:grid-cols-6">{benefits.map(([icon, title, body], index) => <article key={title} className={`rounded-2xl p-6 text-white shadow-sm ${index === 0 ? "bg-teal-950" : index === 1 ? "bg-teal-800" : index === 2 ? "bg-emerald-700" : index === 3 ? "bg-slate-800" : "bg-teal-700"} ${index < 3 ? "md:col-span-2" : index === 3 ? "md:col-span-3" : "md:col-span-3"}`}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/15 text-teal-50"><i className={`fas ${icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-teal-50/85">{body}</p></article>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">From receipt image to reviewed expense draft</h2><p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">Useful receipt scanning software does more than photograph paper. It gives each stage its own visual checkpoint, from capture through correction and saving.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-12">
      <article className="rounded-3xl bg-[#eef8f5] p-6 sm:p-8 lg:col-span-7"><CaptureChoices /><h3 className="mt-7 font-display text-2xl font-bold">Start with the camera or an image you already have</h3><p className="mt-3 text-sm leading-7 text-slate-600">Receipt capture software should meet the document where it is. Use the mobile receipt camera at the point of purchase, select an image from the gallery, or upload a supported receipt image from the web workspace.</p></article>
      <article className="rounded-3xl bg-[#fff1c7] p-6 sm:p-8 lg:col-span-5"><ExtractedFields /><h3 className="mt-7 font-display text-2xl font-bold">Pull the core purchase facts into fields</h3><p className="mt-3 text-sm leading-7 text-slate-700">Receipt OCR software can propose merchant extraction, amount extraction, date extraction, payment method, and currency. The structured draft is easier to check than a page of unlabelled OCR text.</p></article>
      <article className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8 lg:col-span-5"><div className="grid grid-cols-3 gap-2">{[["Subtotal", "$72.00"], ["Tax", "$6.12"], ["Total", "$78.12"]].map(([label, value]) => <div key={label} className="rounded-xl bg-white/10 p-3 text-center"><p className="text-[8px] uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-sm font-black">{value}</p></div>)}</div><h3 className="mt-7 font-display text-2xl font-bold">Separate totals when the receipt makes them visible</h3><p className="mt-3 text-sm leading-7 text-slate-300">Subtotal and tax extraction depend on legibility and layout. The scanner returns available values for review instead of claiming that every receipt contains the same fields.</p></article>
      <article className="rounded-3xl bg-[#e9e3ff] p-6 sm:p-8 lg:col-span-7"><div className="grid gap-5 sm:grid-cols-[0.9fr_1.1fr]"><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-[9px] font-bold uppercase text-slate-400">Line items from scan</p>{[["Studio paper", "2 × $9.00"], ["Ink cartridges", "1 × $42.00"], ["Desk cable", "1 × $12.00"]].map(([item, amount]) => <div key={item} className="mt-3 flex justify-between border-b border-slate-100 pb-2 text-[10px]"><span>{item}</span><strong>{amount}</strong></div>)}</div><div><h3 className="font-display text-2xl font-bold">See line items when OCR can distinguish them</h3><p className="mt-3 text-sm leading-7 text-slate-700">Line-item extraction can include a name, quantity, and price. Long receipts, unusual layouts, folds, glare, or faint printing can reduce what is returned, so compare the list with the image.</p></div></div></article>
      <article className="rounded-3xl bg-[#eef8f5] p-6 sm:p-8 lg:col-span-5"><ConfidencePreview /><h3 className="mt-7 font-display text-2xl font-bold">Use confidence and tags as review signals</h3><p className="mt-3 text-sm leading-7 text-slate-600">A receipt OCR app should tell you when the result deserves attention. Receipt Cycle can surface confidence, detected languages, document type, and conditions such as partial legibility or a missing total.</p></article>
      <article className="rounded-3xl bg-teal-800 p-6 text-white sm:p-8 lg:col-span-7"><ReviewFormPreview /><h3 className="mt-7 font-display text-2xl font-bold">Keep the human review between extraction and saving</h3><p className="mt-3 text-sm leading-7 text-teal-50/85">Automatic categorization is a suggested starting point based on the merchant and visible items. Change the category or any other field when the source record says something different.</p></article>
    </div></div></section>

    <section className="bg-teal-950 py-14 text-white"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-7 px-4 sm:px-6 lg:flex-row lg:items-center"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Turn the receipt in your hand into a record you can review</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-100/80">Capture the image, check the extracted fields, and save the expense while the purchase is still easy to remember.</p></div><LandingPrimaryCta to={primaryCta} inverse>Scan your first receipt</LandingPrimaryCta></div></section>

    <section id="workflow" className="scroll-mt-28 bg-white py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid items-stretch gap-12 lg:grid-cols-[1fr_0.86fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">How a receipt becomes an expense record</h2><p className="mt-5 text-base leading-7 text-slate-600">The receipt scanning app separates four jobs so you can see what the system read and what still needs your judgment.</p><ol className="mt-9 space-y-7">{[
        ["Capture a readable source", "Use the camera, gallery, or web upload. Keep the receipt flat, include every edge, reduce glare, and make sure the total is not hidden by a fold or finger."],
        ["Run OCR and document understanding", "The scanner reads visible text, classifies the document, and proposes structured purchase fields. A formatted text preview preserves more of the receipt context than a total alone."],
        ["Review the proposed fields", "Compare merchant, amount, date, time, category, payment method, currency, tax, subtotal, and line items with the source. Correct anything uncertain before continuing."],
        ["Save the expense with its evidence", "The reviewed values move into the expense flow. The saved transaction can retain the receipt image or structured receipt data so the proof and record stay connected."],
      ].map(([title, body], index) => <li key={title} className="grid grid-cols-[48px_1fr] gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-700 font-display text-lg font-bold text-white">{index + 1}</span><div><h3 className="font-display text-xl font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{body}</p></div></li>)}</ol></div><ScanJourneyVisual /></div></div></section>

    <section className="bg-[#f8f5ee] py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">A better scan starts before OCR runs</h2><p className="mt-4 text-base leading-7 text-slate-600">AI expense capture still depends on the evidence in the image. A few practical checks improve the draft and make the review faster.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{[
      ["Give the camera clean edges", "Place the receipt on a contrasting surface and include the full page. Cropped dates, totals, or merchant headers cannot be reconstructed reliably after capture."],
      ["Control blur, shadows, and glare", "Hold the phone steady and use the flash only when it improves contrast. Glossy paper and folded receipts may need a different angle to keep the printed text visible."],
      ["Expect variation across receipt layouts", "Restaurant, retail, invoice-style, multilingual, and handwritten documents do not present information the same way. Review signals help you decide where to look first."],
      ["Correct the draft instead of trusting it blindly", "If the amount, currency, tax, or category differs from the source, edit it. The purpose of OCR expense tracking is to reduce transcription, not remove responsibility for the record."],
    ].map(([title, body], index) => <article key={title} className={`rounded-3xl p-7 ${index === 0 ? "bg-white" : index === 1 ? "bg-[#dff5ef]" : index === 2 ? "bg-[#fff1c7]" : "bg-[#e9e3ff]"}`}><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-950 text-white"><i className={`fas ${["fa-border-all", "fa-sun", "fa-language", "fa-pen"][index]}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p></article>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid gap-12 lg:grid-cols-[0.82fr_1.18fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Why image capture beats rebuilding every purchase by hand</h2><p className="mt-5 text-base leading-7 text-slate-600">Manual entry can work for a single receipt. It becomes harder when the image, merchant, amount, date, category, and notes live in different places.</p><p className="mt-4 text-base leading-7 text-slate-600">An expense receipt scanner prepares a draft from the evidence you already have. You still review the record, but you start with the document instead of a blank form.</p></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-2 bg-slate-950 px-5 py-4 text-xs font-extrabold text-white sm:px-7"><span>Manual receipt entry</span><span>Receipt Cycle scan</span></div>{[
      ["Type merchant, total, and date from scratch", "Review proposed fields beside the receipt context"],
      ["Keep the image in a separate camera folder", "Carry receipt evidence into the saved transaction"],
      ["Guess which field needs another look", "Use confidence, tags, and visible source details"],
      ["Rebuild line-item notes manually", "Review available item names, quantities, and prices"],
    ].map(([manual, scanner]) => <div key={manual} className="grid grid-cols-2 border-t border-slate-200 text-sm"><p className="p-5 leading-6 text-slate-500 sm:p-6">{manual}</p><p className="border-l border-slate-200 bg-teal-50/50 p-5 font-semibold leading-6 text-slate-800 sm:p-6">{scanner}</p></div>)}</div></div></div></section>

    <section className="bg-teal-950 py-20 text-white sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold sm:text-4xl">Know what each extracted field is for</h2><p className="mt-4 text-base leading-7 text-teal-100/80">A receipt scanner for business should make the draft understandable before you save it. These fields answer different questions about the purchase.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[
      ["Merchant and document type", "Identify who issued the receipt and whether the image looks like a retail receipt, restaurant receipt, invoice, handwritten note, or another document."],
      ["Total, subtotal, and tax", "Separate the final amount from intermediate figures when the layout is clear. Tax values are captured as printed evidence, not evaluated as tax advice."],
      ["Date, time, and payment method", "Place the purchase in time and retain the visible method when it appears. Missing values can be added or corrected during review."],
      ["Currency and detected language", "Keep the amount in the context shown by the receipt and surface the language recognized by the OCR pipeline."],
      ["Category and line items", "Use the suggested category and available items as a starting point. Compare quantities and prices with the original before accepting them."],
      ["Confidence, tags, and formatted text", "See whether the scan may be partly illegible, missing a total, or not a receipt. The formatted text preview keeps a readable document summary close to the fields."],
    ].map(([title, body], index) => <article key={title} className="rounded-2xl border border-white/10 bg-white/10 p-6"><span className="text-sm font-black text-teal-300">0{index + 1}</span><h3 className="mt-4 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-teal-50/80">{body}</p></article>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Receipt scanning for the places purchases happen</h2><p className="mt-4 text-base leading-7 text-slate-600">Choose a work setting to see how the capture and review step fits before expense organization begins.</p></div><div className="mt-12 grid items-stretch gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div id="scanner-audience-panel" role="tabpanel" aria-labelledby={`scanner-audience-tab-${activeAudience.id}`} className="min-w-0 overflow-hidden rounded-3xl border border-teal-100 bg-[#f8f5ee] shadow-sm"><img key={activeAudience.image} src={activeAudience.image} alt={activeAudience.alt} width="1586" height="992" loading="lazy" decoding="async" sizes="(min-width: 1024px) 720px, (min-width: 640px) 90vw, 100vw" className="block h-auto w-full" /></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white px-5 sm:px-6" role="tablist" aria-label="AI receipt scanner audiences">{audiences.map((audience) => { const isActive = audience.id === activeAudience.id; return <div key={audience.id} className="border-b border-slate-200 last:border-b-0"><button id={`scanner-audience-tab-${audience.id}`} type="button" role="tab" aria-selected={isActive} aria-controls="scanner-audience-panel" tabIndex={isActive ? 0 : -1} onClick={() => setActiveAudienceId(audience.id)} onKeyDown={(event) => { const currentIndex = audiences.findIndex((item) => item.id === audience.id); let nextIndex = currentIndex; if (event.key === "ArrowDown" || event.key === "ArrowRight") nextIndex = (currentIndex + 1) % audiences.length; if (event.key === "ArrowUp" || event.key === "ArrowLeft") nextIndex = (currentIndex - 1 + audiences.length) % audiences.length; if (event.key === "Home") nextIndex = 0; if (event.key === "End") nextIndex = audiences.length - 1; if (nextIndex === currentIndex) return; event.preventDefault(); const next = audiences[nextIndex]; setActiveAudienceId(next.id); requestAnimationFrame(() => document.getElementById(`scanner-audience-tab-${next.id}`)?.focus()); }} className="flex min-h-16 w-full items-center justify-between gap-4 py-4 text-left font-display text-lg font-bold text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-teal-500">{audience.title}<span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full transition ${isActive ? "rotate-45 bg-teal-700 text-white" : "bg-teal-50 text-teal-700"}`}><i className="fas fa-plus text-xs" aria-hidden /></span></button>{isActive ? <p className="pb-6 pr-4 text-sm leading-7 text-slate-600">{audience.body}</p> : null}</div>; })}</div></div></div></section>

    <section className="bg-[#eef8f5] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid items-center gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">The scan is the beginning of the expense record</h2><p className="mt-5 text-base leading-7 text-slate-600">Receipt tracking software becomes more useful when capture leads somewhere. After review, the expense can join the transaction workspace where merchant, category, date, type, and amount support search and filtering.</p><p className="mt-4 text-base leading-7 text-slate-600">The receipt image and extracted context remain evidence for the saved purchase. That connection helps when you return later and need to understand why the transaction exists or which document supported it.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/pricing" className="inline-flex min-h-11 items-center rounded-xl bg-teal-700 px-5 text-sm font-bold text-white">Compare plans</Link><Link to="/business-travel-expense-tracker" className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-700">Track business travel expenses</Link><Link to="/freelancer-tax-receipt-tracker" className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-700">Organize freelancer tax records</Link></div></div><SavedRecordPreview /></div></div></section>

    <section className="py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold text-slate-950 sm:text-4xl">Learn more about receipt capture and OCR</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{resources.map((resource) => <article key={resource.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><i className={`fas ${resource.icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{resource.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{resource.description}</p><Link to={resource.href} className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold text-teal-700 hover:text-teal-900">Open resource<i className="fas fa-arrow-right text-xs" aria-hidden /></Link></article>)}</div></div></section>

    <section className="bg-[#f8f5ee] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 lg:grid-cols-2"><div className="p-8 sm:p-10"><h2 className="font-display text-3xl font-bold text-slate-950">Get help when the receipt is difficult to read</h2><p className="mt-4 text-base leading-7 text-slate-600">If a total is missing, the image is partly illegible, or the detected fields do not match the paper, retake the image or correct the draft. For scanner access or account-specific problems, contact the Receipt Cycle team with the device and step where the issue occurred.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex min-h-11 items-center rounded-xl bg-teal-700 px-5 text-sm font-bold text-white">Contact us</Link><Link to="/faq" className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 px-5 text-sm font-bold text-slate-700">Visit the FAQ</Link></div></div><div className="grid gap-px bg-slate-200 sm:grid-cols-3 lg:grid-cols-1">{[["fa-camera-rotate", "Retake the image", "Change the angle, flatten the receipt, and remove glare before running the scan again."], ["fa-pen", "Correct the draft", "Edit extracted text and fields when the source receipt shows a different value."], ["fa-envelope", "Scanner support", "Email support@receiptcycle.com with the device, capture method, and error you saw."]].map(([icon, title, body]) => <div key={title} className="bg-[#f8faf9] p-6"><i className={`fas ${icon} text-teal-700`} aria-hidden /><h3 className="mt-3 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{body}</p></div>)}</div></div></div></section>

    <section id="faq" className="scroll-mt-28 bg-white py-20 sm:py-24"><div className="mx-auto max-w-5xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Frequently Asked Questions</h2><div className="mt-10 divide-y divide-slate-300 border-y border-slate-300">{faqItems.map(([question, answer], index) => <details key={question} className="group py-1" open={index === 0}><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 py-4 text-left text-sm font-extrabold text-slate-900 marker:content-none sm:text-base">{question}<span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-teal-50 text-teal-700 transition group-open:rotate-45"><i className="fas fa-plus text-xs" aria-hidden /></span></summary><p className="max-w-4xl pb-6 pr-12 text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

    <section className="bg-gradient-to-br from-teal-800 via-teal-700 to-emerald-600 py-16 text-white"><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 text-center sm:px-6 lg:grid-cols-[1fr_auto] lg:text-left"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Capture the receipt before the details disappear</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-50/90">Use the camera or upload an image, review the OCR draft, and keep the source connected to the expense you save.</p></div><LandingPrimaryCta to={primaryCta} inverse>Scan your first receipt</LandingPrimaryCta></div></section>
  </CommercialLandingLayout>;
}
