import { useState } from "react";
import { Link } from "react-router-dom";
import { CommercialLandingLayout, LandingPrimaryCta } from "@/components/marketing/CommercialLandingLayout";
import { Seo } from "@/components/Seo";
import { getRouteSeo } from "@/content/routesSeo";

const primaryCta = "/signup?intent=expense";

function TripLedgerPreview() {
  const rows = [
    ["Sep 18", "Northline Air", "Airfare", "$486.00", "fa-plane"],
    ["Sep 18", "CityLink Rail", "Transportation", "$28.40", "fa-train-subway"],
    ["Sep 19", "Harbor Hotel", "Lodging", "$214.00", "fa-bed"],
    ["Sep 19", "Market Table", "Meals", "$46.80", "fa-utensils"],
  ];

  return (
    <div className="relative mx-auto max-w-2xl" role="img" aria-label="Receipt Cycle trip expense records organized by date, category, amount, and receipt status">
      <div className="overflow-hidden rounded-[28px] border border-white/70 bg-white shadow-[0_28px_90px_rgba(15,118,110,0.2)] ring-1 ring-slate-200">
        <div className="flex items-center justify-between border-b border-slate-100 bg-slate-950 px-4 py-3 text-white">
          <div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-rose-300" /><span className="h-2.5 w-2.5 rounded-full bg-amber-300" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-300" /></div>
          <p className="text-[10px] font-bold">Travel expense records</p>
          <i className="fas fa-plane-departure text-teal-300" aria-hidden />
        </div>
        <div className="grid min-h-[430px] bg-[#eef8f5] sm:grid-cols-[0.68fr_1.32fr]">
          <div className="border-b border-teal-100 bg-teal-950 p-5 text-white sm:border-b-0 sm:border-r">
            <p className="text-[9px] font-extrabold uppercase tracking-[0.18em] text-teal-300">Date range</p>
            <p className="mt-2 font-display text-lg font-bold">Sep 18 to Sep 21</p>
            <div className="relative mt-7 space-y-6 before:absolute before:bottom-3 before:left-[13px] before:top-3 before:w-px before:bg-teal-500/40">
              {[["18", "Departure"], ["19", "Client visit"], ["20", "Event day"], ["21", "Return"]].map(([day, label], index) => (
                <div key={day} className="relative flex items-center gap-3">
                  <span className={`z-10 flex h-7 w-7 items-center justify-center rounded-full text-[9px] font-black ${index === 3 ? "bg-white text-teal-900" : "bg-teal-700 text-white"}`}>{day}</span>
                  <span className="text-[10px] font-bold text-teal-50">{label}</span>
                </div>
              ))}
            </div>
            <div className="mt-8 rounded-2xl bg-white/10 p-4">
              <p className="text-[8px] uppercase tracking-wider text-teal-300">Trip spending</p>
              <p className="mt-1 font-display text-2xl font-black">$775.20</p>
              <p className="mt-1 text-[9px] text-teal-100/70">4 recorded expenses</p>
            </div>
          </div>
          <div className="p-4 sm:p-6">
            <div className="flex items-start justify-between gap-3">
              <div><p className="text-[9px] font-extrabold uppercase tracking-wider text-teal-700">Business travel</p><h3 className="mt-1 font-display text-xl font-bold text-slate-950">Review the trip while the context is fresh</h3></div>
              <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-teal-100 text-teal-700"><i className="fas fa-sliders" aria-hidden /></span>
            </div>
            <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white">
              {rows.map(([date, merchant, category, amount, icon]) => (
                <div key={`${date}-${merchant}`} className="grid grid-cols-[34px_1fr_auto] items-center gap-3 border-b border-slate-100 p-3 last:border-b-0">
                  <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-teal-50 text-teal-700"><i className={`fas ${icon} text-[10px]`} aria-hidden /></span>
                  <div className="min-w-0"><p className="truncate text-[10px] font-extrabold text-slate-900">{merchant}</p><p className="text-[8px] text-slate-400">{date} · {category}</p></div>
                  <p className="text-[10px] font-black text-slate-900">{amount}</p>
                </div>
              ))}
            </div>
            <div className="mt-4 flex items-center justify-between rounded-xl bg-emerald-50 px-4 py-3"><div><p className="text-[8px] font-bold uppercase text-emerald-700">Receipt evidence</p><p className="mt-1 text-[10px] font-extrabold text-slate-800">4 records ready to revisit</p></div><i className="fas fa-circle-check text-emerald-600" aria-hidden /></div>
          </div>
        </div>
      </div>
      <div className="absolute -bottom-5 -left-3 hidden items-center gap-3 rounded-2xl bg-white p-3 shadow-xl ring-1 ring-slate-200 sm:flex">
        <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-100 text-amber-700"><i className="fas fa-wallet" aria-hidden /></span>
        <div><p className="text-[8px] font-bold uppercase text-slate-400">Accounts used</p><p className="text-xs font-black">Business card + cash</p></div>
      </div>
    </div>
  );
}

function ReceiptCapturePreview() {
  return <div className="grid gap-3 sm:grid-cols-[0.85fr_1.15fr]"><div className="relative flex min-h-52 items-center justify-center overflow-hidden rounded-2xl bg-slate-950 p-5"><div className="absolute inset-4 rounded-2xl border-2 border-dashed border-teal-300/60" /><div className="relative -rotate-2 rounded-xl bg-white p-4 shadow-xl"><p className="text-center text-[8px] font-black">CITYLINK RAIL</p><div className="my-3 h-px border-t border-dashed border-slate-300" /><p className="text-[8px]">Airport transfer</p><p className="mt-4 text-center text-sm font-black">$28.40</p></div></div><div className="rounded-2xl border border-teal-100 bg-white p-5"><p className="text-[9px] font-bold uppercase tracking-wider text-teal-700">Review before saving</p>{[["Merchant", "CityLink Rail"], ["Category", "Transportation"], ["Account", "Business card"]].map(([label, value]) => <div key={label} className="mt-3 rounded-xl bg-slate-50 p-3"><p className="text-[8px] font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-[10px] font-extrabold">{value}</p></div>)}</div></div>;
}

function DateFilterPreview() {
  return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase text-slate-400">Travel dates</p><p className="mt-1 font-display text-lg font-bold">Sep 18 to Sep 21</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-100 text-teal-700"><i className="fas fa-calendar-days" aria-hidden /></span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-[8px] font-bold text-slate-400">CATEGORY</p><p className="mt-1 text-[10px] font-extrabold">Travel</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[8px] font-bold text-slate-400">ACCOUNT</p><p className="mt-1 text-[10px] font-extrabold">Business card</p></div></div><button type="button" className="mt-4 flex min-h-11 w-full items-center justify-center rounded-xl bg-teal-700 text-[10px] font-extrabold text-white">Show matching records</button></div>;
}

function CategoryPreview() {
  const categories = [["Airfare", "$486", "fa-plane"], ["Lodging", "$214", "fa-bed"], ["Meals", "$46.80", "fa-utensils"], ["Transport", "$28.40", "fa-taxi"]];
  return <div className="grid grid-cols-2 gap-3">{categories.map(([label, amount, icon], index) => <div key={label} className={`rounded-2xl p-4 ${index === 0 ? "bg-teal-950 text-white" : index === 1 ? "bg-[#e9e3ff]" : index === 2 ? "bg-[#fff1c7]" : "bg-[#dff5ef]"}`}><i className={`fas ${icon} text-sm ${index === 0 ? "text-teal-300" : "text-teal-700"}`} aria-hidden /><p className="mt-4 text-[9px] font-bold uppercase tracking-wider opacity-70">{label}</p><p className="mt-1 font-display text-lg font-black">{amount}</p></div>)}</div>;
}

function AccountPreview() {
  return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Accounts used on this trip</p><div className="mt-4 space-y-3">{[["Business card", "$728.40", "fa-credit-card"], ["Cash", "$46.80", "fa-money-bill"], ["Savings", "$0.00", "fa-piggy-bank"]].map(([account, amount, icon], index) => <div key={account} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className={`flex h-9 w-9 items-center justify-center rounded-lg ${index === 0 ? "bg-teal-100 text-teal-700" : "bg-white text-slate-500"}`}><i className={`fas ${icon} text-xs`} aria-hidden /></span><div className="flex-1"><p className="text-[10px] font-extrabold">{account}</p><p className="text-[8px] text-slate-400">Linked activity</p></div><strong className="text-[10px]">{amount}</strong></div>)}</div></div>;
}

function JourneyVisual() {
  const steps = [["fa-camera", "Capture", "Receipt or manual entry"], ["fa-pen", "Review", "Amount, date, and notes"], ["fa-tags", "Organize", "Category and account"], ["fa-magnifying-glass", "Revisit", "Search and date filters"]];
  return <div className="relative flex min-h-[720px] flex-col overflow-hidden rounded-3xl bg-slate-950 p-7 text-white sm:p-9"><div className="absolute -right-24 -top-24 h-64 w-64 rounded-full bg-teal-500/20" /><div className="relative"><p className="text-[10px] font-extrabold uppercase tracking-[0.2em] text-teal-300">A trip record takes shape</p><h3 className="mt-3 font-display text-3xl font-bold">From the first booking to the return journey</h3><p className="mt-3 text-sm leading-7 text-slate-300">Each purchase adds context to the same searchable expense history.</p></div><div className="relative mt-9 flex flex-1 flex-col justify-between gap-5">{steps.map(([icon, title, detail], index) => <div key={title} className="relative flex items-center gap-4 rounded-2xl border border-white/10 bg-white/10 p-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-teal-400/15 text-teal-200"><i className={`fas ${icon}`} aria-hidden /></span><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Stage {index + 1}</p><p className="mt-1 font-display text-lg font-bold">{title}</p><p className="text-xs text-slate-300">{detail}</p></div>{index < steps.length - 1 ? <span className="absolute -bottom-6 left-9 h-6 w-px bg-teal-400/50" /> : null}</div>)}</div><div className="relative mt-8 rounded-2xl bg-white p-5 text-slate-900"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase text-slate-400">Trip review</p><p className="mt-1 font-display text-lg font-bold">Four records, one date range</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><i className="fas fa-check" aria-hidden /></span></div></div></div>;
}

function CsvPreview() {
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between bg-slate-950 px-5 py-4 text-white"><div><p className="text-[9px] font-bold uppercase text-slate-400">Export records</p><p className="mt-1 text-sm font-extrabold">Transactions.csv</p></div><i className="fas fa-file-csv text-2xl text-teal-300" aria-hidden /></div><div className="overflow-hidden p-4"><div className="grid grid-cols-[0.8fr_1.3fr_1fr_0.8fr] gap-2 rounded-lg bg-slate-100 p-2 text-[8px] font-bold uppercase text-slate-500"><span>Date</span><span>Merchant</span><span>Category</span><span>Amount</span></div>{[["09/18", "Northline Air", "Airfare", "486.00"], ["09/19", "Harbor Hotel", "Lodging", "214.00"], ["09/19", "Market Table", "Meals", "46.80"]].map((row) => <div key={row[1]} className="grid grid-cols-[0.8fr_1.3fr_1fr_0.8fr] gap-2 border-b border-slate-100 p-2 text-[8px] text-slate-600 last:border-b-0">{row.map((cell) => <span key={cell} className="truncate">{cell}</span>)}</div>)}</div></div>;
}

export default function BusinessTravelExpenseTrackerLanding() {
  const seo = getRouteSeo("/business-travel-expense-tracker");
  const [activeAudienceId, setActiveAudienceId] = useState("consultants");
  const benefits = [
    ["fa-camera", "Record the purchase where it happens", "Photograph a travel receipt, choose an existing image, or add the expense manually. The record starts while the merchant, business purpose, and payment method are still easy to remember."],
    ["fa-receipt", "Keep the evidence with the expense", "A business receipt tracker is more useful when the receipt and transaction remain connected. Reopen the record later to review its merchant, date, amount, category, account, notes, and available receipt details."],
    ["fa-tags", "Separate each kind of travel spending", "Use expense categories for airfare, lodging, meals, transportation, parking, supplies, or another cost that fits your work. Categories also support budgets and reporting beyond the trip."],
    ["fa-wallet", "Remember how the purchase was paid", "Link expenses to a cash, card, bank, or savings account and retain the payment method. That context helps when a hotel charge and a taxi paid in cash need different follow-up."],
    ["fa-magnifying-glass", "Return to the right trip records", "Search merchants and descriptions, then filter by travel dates, category, account, or expense type. Business travel expense tracking becomes a reviewable history instead of a folder of unrelated files."],
  ];
  const audiences = [
    { id: "consultants", title: "Independent consultants", body: "Client visits often combine airfare, rail, lodging, meals, and small purchases made between meetings. Use Receipt Cycle as a travel expense tracker that preserves the source receipt, the date, the business note, and the account used without turning the trip into an enterprise approval process.", image: "/landing/audiences/travel-consultant.webp", alt: "Hand-drawn consultant recording a business travel expense at an airport gate" },
    { id: "small-teams", title: "Small teams", body: "Trade shows, training days, and customer visits create expenses across more than one traveler. Each person can keep their own reviewed records consistent, while an operations lead can use dates, categories, accounts, and CSV data to prepare a practical post-trip review.", image: "/landing/audiences/travel-small-team.webp", alt: "Hand-drawn small-business team organizing hotel, meal, and transportation receipts" },
    { id: "field-service", title: "Field-service travelers", body: "Fuel, overnight lodging, meals, parking, and materials may appear during the same job. A business trip expense tracker helps preserve those purchases close to the work, including cash or card context and notes that explain why the expense was recorded.", image: "/landing/audiences/travel-field-service.webp", alt: "Hand-drawn field-service professional capturing a fuel receipt during a work trip" },
    { id: "operations", title: "Operations coordinators", body: "Use a consistent transaction record when coworkers return with receipts from different places. Receipt Cycle supports review, search, account activity, and export, but it does not claim policy enforcement, manager approvals, or automatic employee reimbursement.", image: "/landing/audiences/travel-operations.webp", alt: "Hand-drawn operations coordinator reviewing categorized business-trip expenses with coworkers" },
  ];
  const activeAudience = audiences.find((audience) => audience.id === activeAudienceId) ?? audiences[0];
  const faqItems = [
    ["What can I record with a business travel expense tracker?", "Record expenses such as airfare, hotels, meals, ground transportation, parking, fuel, event fees, internet access, and trip supplies when they relate to your work. Each Receipt Cycle transaction can include an amount, merchant, category, date, payment method, linked account, notes, and available receipt evidence."],
    ["Can I scan travel receipts while I am away?", "Yes. Use the mobile receipt camera or choose an image from the gallery, then review the extracted details before saving. You can also upload a supported receipt image on the web or enter the purchase manually when there is no usable image."],
    ["Can I group expenses under a trip name?", "Receipt Cycle does not currently provide a dedicated trip object or trip-name field. Use the travel dates, categories, linked account, merchant search, and transaction notes to retrieve the relevant records. Do not rely on the product for itinerary or booking management."],
    ["Does Receipt Cycle create a business trip expense report?", "Receipt Cycle provides transaction history, date and category filters, report totals, and CSV export when available for the plan and workspace. It does not currently claim a formatted PDF expense report dedicated to one trip."],
    ["Does it handle expense claims and employee reimbursement?", "No. Receipt Cycle can organize the records that may support a claim or reimbursement discussion, but it is not travel expense claims software. It does not submit claims, route manager approvals, enforce travel policy, or repay employees."],
    ["Can a corporate or small team use it for travel expenses?", "Teams can use consistent categories, accounts, notes, receipt evidence, and exports to improve record quality. Receipt Cycle is not positioned as a corporate booking, card-feed, or enterprise travel and expense management platform."],
    ["Does Receipt Cycle reconcile travel expenses automatically?", "No. Business travel expense reconciliation remains a review task. Filters, accounts, payment methods, notes, and receipt attachments help you compare records, but Receipt Cycle does not automatically match card feeds, settle cash advances, or approve discrepancies."],
    ["Can I export my travel transaction records?", "CSV export is available when the account plan and administrator settings permit it. The export includes transaction fields such as date, type, category, amount, merchant, description, payment method, and workspace. PDF travel-report export is not currently claimed."],
  ];
  const resources = [
    { title: "Track business travel expenses", description: "Build a capture habit for flights, hotels, meals, transportation, and the small purchases made between them.", href: "/blog/scan-receipts-for-tax-refund", icon: "fa-plane" },
    { title: "Connect receipt capture and expense records", description: "See why keeping the image and reviewed transaction together reduces post-trip reconstruction.", href: "/blog/expense-tracker-receipt-scanner-one-two-punch", icon: "fa-receipt" },
    { title: "Bring statement activity into your records", description: "Learn how CSV statement import can support transaction review without claiming automatic bank reconciliation.", href: "/blog/import-bank-statements-expense-tracking", icon: "fa-file-csv" },
  ];

  return <CommercialLandingLayout ctaLabel="Track your first travel expense" ctaHref={primaryCta} announcement="Record the trip while the details are still close.">
    {seo ? <Seo {...seo} /> : null}

    <section className="relative overflow-hidden bg-[#f7fbf9] py-16 sm:py-20 lg:py-24"><div className="absolute -right-24 top-8 h-80 w-80 rounded-full bg-teal-100/70 blur-3xl" /><div className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 sm:px-8 lg:grid-cols-[0.86fr_1.14fr] lg:gap-16"><div className="max-w-xl"><h1 className="text-balance font-display text-4xl font-bold leading-[1.04] tracking-[-0.04em] text-slate-950 sm:text-5xl lg:text-[3.4rem]"><span className="block">Business travel expense tracker</span>{" "}<span className="mt-1 block text-teal-700">for the whole trip</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-600">Capture travel receipts, review every purchase, and return to an organized record of airfare, lodging, meals, and transportation.</p><div className="mt-8"><LandingPrimaryCta to={primaryCta}>Track your first travel expense</LandingPrimaryCta><p className="mt-3 text-sm font-medium text-slate-500">No credit card required. Cancel paid plans anytime.</p></div></div><TripLedgerPreview /></div></section>

    <section id="features" className="scroll-mt-28 bg-[#dff5ef] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Do not wait until unpacking to rebuild the trip</h2><p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">Business expense tracking software earns its place by preserving what happened, where the money went, and which evidence belongs with each purchase.</p></div><div className="mt-12 grid gap-4 md:grid-cols-6">{benefits.map(([icon, title, body], index) => <article key={title} className={`rounded-2xl p-6 text-white shadow-sm ${index === 0 ? "bg-teal-950" : index === 1 ? "bg-teal-800" : index === 2 ? "bg-emerald-700" : index === 3 ? "bg-slate-800" : "bg-teal-700"} ${index < 3 ? "md:col-span-2" : "md:col-span-3"}`}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/15 text-teal-50"><i className={`fas ${icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-teal-50/85">{body}</p></article>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Every travel purchase gets its own useful record</h2><p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">Business travel expense software should handle the ordinary details well before it tries to summarize the journey.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-12">
      <article className="rounded-3xl bg-[#eef8f5] p-6 sm:p-8 lg:col-span-7"><ReceiptCapturePreview /><h3 className="mt-7 font-display text-2xl font-bold">Start with the receipt or enter the expense yourself</h3><p className="mt-3 text-sm leading-7 text-slate-600">Use receipt capture when you have a readable image. If a taxi does not provide one or a cash purchase needs context, add the merchant, amount, date, category, payment method, account, and notes manually.</p></article>
      <article className="rounded-3xl bg-[#fff1c7] p-6 sm:p-8 lg:col-span-5"><CategoryPreview /><h3 className="mt-7 font-display text-2xl font-bold">Give travel spending categories that still make sense later</h3><p className="mt-3 text-sm leading-7 text-slate-700">Airfare, lodging, meals, and transportation answer different questions. Expense categorization keeps those costs distinct while allowing custom categories for event fees, connectivity, parking, or trip supplies.</p></article>
      <article className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8 lg:col-span-5"><DateFilterPreview /><h3 className="mt-7 font-display text-2xl font-bold">Use the travel dates to narrow the history</h3><p className="mt-3 text-sm leading-7 text-slate-300">A business trip expense report starts with the right records. Choose a start and end date, then refine the result with category, account, type, search, or sort controls before reviewing what belongs to the journey.</p></article>
      <article className="rounded-3xl bg-[#e9e3ff] p-6 sm:p-8 lg:col-span-7"><AccountPreview /><h3 className="mt-7 font-display text-2xl font-bold">Keep cash and card purchases distinguishable</h3><p className="mt-3 text-sm leading-7 text-slate-700">A hotel may go on the business card while a local taxi is paid in cash. Linking the account and retaining the payment method gives each record the financial context needed for a careful post-trip check.</p></article>
      <article className="rounded-3xl bg-[#eef8f5] p-6 sm:p-8 lg:col-span-5"><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Transaction notes</p><p className="mt-3 text-sm font-extrabold">Airport transfer to client workshop</p><div className="mt-4 flex gap-2"><span className="rounded-full bg-teal-50 px-3 py-1 text-[9px] font-bold text-teal-700">Transportation</span><span className="rounded-full bg-slate-100 px-3 py-1 text-[9px] font-bold text-slate-600">Business card</span></div></div><h3 className="mt-7 font-display text-2xl font-bold">Write down the purpose before it becomes a guess</h3><p className="mt-3 text-sm leading-7 text-slate-600">Notes can identify the client visit, event, destination, or reason for an unusual purchase. Receipt Cycle does not decide whether an expense is reimbursable or tax deductible, but it gives you a place to preserve the context.</p></article>
      <article className="rounded-3xl bg-teal-800 p-6 text-white sm:p-8 lg:col-span-7"><div className="grid gap-3 sm:grid-cols-3">{[["4", "Expenses"], ["4", "Receipts"], ["$775", "Recorded"]].map(([value, label]) => <div key={label} className="rounded-2xl bg-white/10 p-5"><p className="font-display text-2xl font-black text-teal-200">{value}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-wider text-teal-50/70">{label}</p></div>)}</div><h3 className="mt-7 font-display text-2xl font-bold">Finish with a record you can search again</h3><p className="mt-3 text-sm leading-7 text-teal-50/85">An expense tracking app should remain useful after the trip. Merchant search, dates, categories, accounts, amounts, notes, and receipt evidence help you return to the exact purchase without reopening every file.</p></article>
    </div></div></section>

    <section className="bg-teal-950 py-14 text-white"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-7 px-4 sm:px-6 lg:flex-row lg:items-center"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Leave the paper trail better than you found it</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-100/80">Record the expense, attach the evidence, and preserve the trip context before the next meeting begins.</p></div><LandingPrimaryCta to={primaryCta} inverse>Track your first travel expense</LandingPrimaryCta></div></section>

    <section id="workflow" className="scroll-mt-28 bg-white py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid items-stretch gap-12 lg:grid-cols-[1fr_0.86fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Build the trip record from departure to return</h2><p className="mt-5 text-base leading-7 text-slate-600">Travel expense tracking software is most useful when each step answers a practical question, not when everything is postponed until the traveler gets home.</p><ol className="mt-9 space-y-7">{[
        ["Capture the source at the time of purchase", "Photograph a printed receipt, select a saved image, upload from the web, or use manual entry. Keep the amount and merchant close to the evidence instead of relying on memory."],
        ["Review the details before saving", "Check the date, amount, merchant, expense category, payment method, account, and notes. OCR suggestions reduce typing, but the traveler remains responsible for correcting the record."],
        ["Add the context that explains the purchase", "Use notes for the destination, client visit, meeting, or event. Choose the category and account that reflect how the business wants to review the cost later."],
        ["Return to the trip with filters and search", "Choose the travel dates, search a merchant or description, and filter by category or account. The result becomes a working expense history for review or CSV export."],
      ].map(([title, body], index) => <li key={title} className="grid grid-cols-[48px_1fr] gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-700 font-display text-lg font-bold text-white">{index + 1}</span><div><h3 className="font-display text-xl font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{body}</p></div></li>)}</ol></div><JourneyVisual /></div></div></section>

    <section className="bg-[#f8f5ee] py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Give each travel cost enough context to stand on its own</h2><p className="mt-4 text-base leading-7 text-slate-600">The same trip can include pre-booked charges, daily purchases, and expenses paid from different accounts. Treating them as separate records makes the final review easier.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{[
      ["Airfare and long-distance transport", "Record the carrier or provider, purchase date, amount, category, payment account, and the receipt or booking evidence you actually have. Receipt Cycle does not manage the booking itself."],
      ["Hotel and overnight lodging", "Keep the lodging merchant, total, date, account, and notes together. If the folio includes several kinds of charges, review the receipt rather than assuming every line belongs to the same category."],
      ["Meals during the business trip", "Attach the receipt when available and add notes that preserve the business context. Receipt Cycle stores the record but does not determine deductibility, meal limits, or company policy."],
      ["Ground transport and incidentals", "Taxis, rail, fuel, parking, internet access, and small supplies are easy to overlook. Capture them when they happen and choose a category that remains useful in your wider spending history."],
    ].map(([title, body], index) => <article key={title} className={`rounded-3xl p-7 ${index === 0 ? "bg-white" : index === 1 ? "bg-[#dff5ef]" : index === 2 ? "bg-[#fff1c7]" : "bg-[#e9e3ff]"}`}><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-950 text-white"><i className={`fas ${["fa-plane", "fa-bed", "fa-utensils", "fa-taxi"][index]}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p></article>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid gap-12 lg:grid-cols-[0.82fr_1.18fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">A trip folder stores files. An expense record explains the spending.</h2><p className="mt-5 text-base leading-7 text-slate-600">Photos, booking confirmations, and paper receipts are evidence, but they do not automatically become a usable history. A business spending tracker adds the amount, date, category, account, and notes needed to find and understand the purchase.</p><p className="mt-4 text-base leading-7 text-slate-600">Receipt Cycle acts as an expense organizer for these records. It does not replace a booking platform, corporate card feed, travel policy system, or reimbursement service.</p></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-2 bg-slate-950 px-5 py-4 text-xs font-extrabold text-white sm:px-7"><span>Scattered trip files</span><span>Receipt Cycle records</span></div>{[
      ["Receipts remain in a wallet, camera roll, and inbox", "Receipt evidence stays connected to the transaction when available"],
      ["Airfare, lodging, meals, and taxis look like one pile", "Each purchase has its own category, amount, date, and account"],
      ["The business purpose depends on memory", "Notes preserve the destination, client visit, event, or reason"],
      ["Post-trip review starts by opening every file", "Search and filters narrow the history before detailed review"],
    ].map(([before, after]) => <div key={before} className="grid grid-cols-2 border-t border-slate-200 text-sm"><p className="p-5 leading-6 text-slate-500 sm:p-6">{before}</p><p className="border-l border-slate-200 bg-teal-50/50 p-5 font-semibold leading-6 text-slate-800 sm:p-6">{after}</p></div>)}</div></div></div></section>

    <section className="bg-teal-950 py-20 text-white sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid items-center gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Review the trip without pretending the work is automatic</h2><p className="mt-5 text-base leading-7 text-teal-50/80">Date range, category, account, and merchant filters help you isolate likely travel transactions. Receipt attachments and notes help you check them. This supports business travel expense management, but it does not automatically reconcile a card feed or approve a claim.</p><p className="mt-4 text-base leading-7 text-teal-50/80">When you need the underlying transaction data elsewhere, export a CSV if your plan and workspace permit it. Receipt Cycle does not currently promise a dedicated PDF expense report.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/pricing" className="inline-flex min-h-11 items-center rounded-xl bg-white px-5 text-sm font-bold text-teal-900">Compare plans</Link><Link to="/ai-receipt-scanner" className="inline-flex min-h-11 items-center rounded-xl border border-white/20 px-5 text-sm font-bold text-white">Explore receipt scanning</Link></div></div><CsvPreview /></div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Travel records for the way smaller businesses move</h2><p className="mt-4 text-base leading-7 text-slate-600">A small business expense tracker should fit the journey without adding enterprise travel administration. Choose a setting to see what deserves attention before, during, and after the trip.</p></div><div className="mt-12 grid items-stretch gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div id="travel-audience-panel" role="tabpanel" aria-labelledby={`travel-audience-tab-${activeAudience.id}`} className="min-w-0 overflow-hidden rounded-3xl border border-teal-100 bg-[#f8f5ee] shadow-sm"><img key={activeAudience.image} src={activeAudience.image} alt={activeAudience.alt} width="1586" height="992" loading="lazy" decoding="async" sizes="(min-width: 1024px) 720px, (min-width: 640px) 90vw, 100vw" className="block h-auto w-full" /></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white px-5 sm:px-6" role="tablist" aria-label="Business travel expense audiences">{audiences.map((audience) => { const isActive = audience.id === activeAudience.id; return <div key={audience.id} className="border-b border-slate-200 last:border-b-0"><button id={`travel-audience-tab-${audience.id}`} type="button" role="tab" aria-selected={isActive} aria-controls="travel-audience-panel" tabIndex={isActive ? 0 : -1} onClick={() => setActiveAudienceId(audience.id)} onKeyDown={(event) => { const currentIndex = audiences.findIndex((item) => item.id === audience.id); let nextIndex = currentIndex; if (event.key === "ArrowDown" || event.key === "ArrowRight") nextIndex = (currentIndex + 1) % audiences.length; if (event.key === "ArrowUp" || event.key === "ArrowLeft") nextIndex = (currentIndex - 1 + audiences.length) % audiences.length; if (event.key === "Home") nextIndex = 0; if (event.key === "End") nextIndex = audiences.length - 1; if (nextIndex === currentIndex) return; event.preventDefault(); const next = audiences[nextIndex]; setActiveAudienceId(next.id); requestAnimationFrame(() => document.getElementById(`travel-audience-tab-${next.id}`)?.focus()); }} className="flex min-h-16 w-full items-center justify-between gap-4 py-4 text-left font-display text-lg font-bold text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-teal-500">{audience.title}<span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full transition ${isActive ? "rotate-45 bg-teal-700 text-white" : "bg-teal-50 text-teal-700"}`}><i className="fas fa-plus text-xs" aria-hidden /></span></button>{isActive ? <p className="pb-6 pr-4 text-sm leading-7 text-slate-600">{audience.body}</p> : null}</div>; })}</div></div></div></section>

    <section className="bg-[#eef8f5] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold text-slate-950 sm:text-4xl">Keep learning after the journey</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{resources.map((resource) => <article key={resource.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><i className={`fas ${resource.icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{resource.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{resource.description}</p><Link to={resource.href} className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold text-teal-700 hover:text-teal-900">Open resource<i className="fas fa-arrow-right text-xs" aria-hidden /></Link></article>)}</div></div></section>

    <section className="py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 lg:grid-cols-2"><div className="bg-[#fff1c7] p-8 sm:p-10"><h2 className="font-display text-3xl font-bold text-slate-950">Get help before the travel details go cold</h2><p className="mt-4 text-base leading-7 text-slate-600">If a receipt will not scan, enter the expense manually or retake the image. If dates, categories, or accounts do not return the expected records, clear the filters and narrow them one at a time.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex min-h-11 items-center rounded-xl bg-teal-700 px-5 text-sm font-bold text-white">Contact us</Link><Link to="/faq" className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-700">Visit the FAQ</Link></div></div><div className="grid gap-px bg-slate-200 sm:grid-cols-3 lg:grid-cols-1">{[["fa-camera-rotate", "Retake a receipt", "Flatten the paper, improve the light, and check every extracted field before saving."], ["fa-filter-circle-xmark", "Reset the filters", "Start with the travel dates, then add category or account filters one at a time."], ["fa-envelope", "Product support", "Email support@receiptcycle.com with the device, page, and step where the issue occurred."]].map(([icon, title, body]) => <div key={title} className="bg-[#f8faf9] p-6"><i className={`fas ${icon} text-teal-700`} aria-hidden /><h3 className="mt-3 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{body}</p></div>)}</div></div></div></section>

    <section id="faq" className="scroll-mt-28 bg-[#f8f5ee] py-20 sm:py-24"><div className="mx-auto max-w-5xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Frequently Asked Questions</h2><div className="mt-10 divide-y divide-slate-300 border-y border-slate-300">{faqItems.map(([question, answer], index) => <details key={question} className="group py-1" open={index === 0}><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 py-4 text-left text-sm font-extrabold text-slate-900 marker:content-none sm:text-base">{question}<span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-teal-50 text-teal-700 transition group-open:rotate-45"><i className="fas fa-plus text-xs" aria-hidden /></span></summary><p className="max-w-4xl pb-6 pr-12 text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

    <section className="bg-gradient-to-br from-teal-800 via-teal-700 to-emerald-600 py-16 text-white"><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 text-center sm:px-6 lg:grid-cols-[1fr_auto] lg:text-left"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Bring home the trip, not a pile of admin</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-50/90">Capture receipts, review travel expenses, and keep the records ready for the next question.</p></div><LandingPrimaryCta to={primaryCta} inverse>Track your first travel expense</LandingPrimaryCta></div></section>
  </CommercialLandingLayout>;
}
