import { useState } from "react";
import { Link } from "react-router-dom";
import { CommercialLandingLayout, LandingPrimaryCta } from "@/components/marketing/CommercialLandingLayout";
import { Seo } from "@/components/Seo";
import { getRouteSeo } from "@/content/routesSeo";

const clients = [
  { initials: "MC", name: "Marlow Creative", contact: "Ada Mensah", invoices: 5, balance: "$1,240", status: "Active" },
  { initials: "NR", name: "Northline Repair", contact: "Caleb Reed", invoices: 3, balance: "$0", status: "Active" },
  { initials: "OS", name: "Orchard Studio", contact: "Nia Stone", invoices: 2, balance: "$680", status: "Prospect" },
];

function CustomerDirectoryPreview({ compact = false }: { compact?: boolean }) {
  return (
    <div className="relative mx-auto w-full max-w-[680px] rounded-[2rem] bg-teal-950 p-4 shadow-2xl shadow-teal-950/20 sm:p-6" role="img" aria-label="Receipt Cycle customer directory with invoice counts and outstanding balances">
      <div className="overflow-hidden rounded-[1.4rem] bg-[#f8faf9]">
        <div className="flex flex-col gap-3 border-b border-slate-200 bg-white px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5">
          <div><p className="text-[8px] font-black uppercase tracking-[0.18em] text-teal-700">Sales directory</p><p className="mt-1 font-display text-lg font-bold text-slate-950">Customers</p></div>
          <span className="inline-flex min-h-9 items-center justify-center rounded-xl bg-teal-700 px-4 text-[9px] font-extrabold text-white">ADD CUSTOMER</span>
        </div>
        <div className="p-4 sm:p-5">
          <div className="flex min-h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-[10px] text-slate-400"><i className="fas fa-search" aria-hidden />Search customers</div>
          <div className="mt-4 overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200/70">
            {clients.slice(0, compact ? 3 : clients.length).map((client) => (
              <div key={client.name} className="grid grid-cols-[38px_1fr_auto] items-center gap-3 border-b border-slate-100 p-3 last:border-0 sm:grid-cols-[42px_1fr_60px_80px_66px] sm:p-4">
                <span className="flex h-9 w-9 items-center justify-center rounded-full bg-teal-100 text-[9px] font-black text-teal-800">{client.initials}</span>
                <div className="min-w-0"><p className="truncate text-[10px] font-extrabold text-slate-900 sm:text-xs">{client.name}</p><p className="truncate text-[8px] text-slate-400 sm:text-[9px]">{client.contact}</p></div>
                <span className="hidden text-center text-[9px] font-bold text-slate-600 sm:block">{client.invoices}</span>
                <span className="text-right text-[10px] font-black text-slate-900">{client.balance}</span>
                <span className={`hidden rounded-full px-2 py-1 text-center text-[8px] font-extrabold sm:block ${client.status === "Active" ? "bg-emerald-100 text-emerald-700" : "bg-violet-100 text-violet-700"}`}>{client.status}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

function CustomerProfilePreview() {
  return (
    <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200/80">
      <div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-teal-100 text-sm font-black text-teal-800">MC</span><div><p className="font-display text-lg font-bold">Marlow Creative</p><p className="text-[10px] text-slate-500">Ada Mensah · Active</p></div></div>
      <div className="mt-5 grid gap-2 text-[9px] sm:grid-cols-2">{[["Contact", "Ada Mensah"], ["Email", "ada@example.com"], ["Phone", "+1 555 0142"], ["Billing address", "18 Market Street"]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-extrabold text-slate-800">{value}</p></div>)}</div>
      <div className="mt-3 rounded-xl bg-[#eef8f5] p-3"><p className="text-[8px] font-bold uppercase tracking-wide text-teal-700">Internal note</p><p className="mt-1 text-[9px] leading-4 text-slate-600">Send design invoices to the finance contact after approval.</p></div>
    </div>
  );
}

function BillingHistoryPreview() {
  return (
    <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200/80">
      <div className="flex items-end justify-between"><div><p className="text-[8px] font-bold uppercase tracking-wider text-slate-400">Customer billing</p><p className="mt-1 font-display text-lg font-bold">Invoice history</p></div><div className="text-right"><p className="text-[8px] text-slate-400">Outstanding</p><p className="font-display text-xl font-black text-rose-700">$1,240</p></div></div>
      <div className="mt-5 space-y-2">{[["INV-0054", "Due Oct 18", "Sent", "$1,240"], ["INV-0041", "Paid Sep 02", "Paid", "$860"], ["INV-0032", "Paid Aug 08", "Paid", "$540"]].map(([number, date, status, total]) => <div key={number} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 rounded-xl bg-slate-50 p-3 text-[9px]"><div><p className="font-extrabold text-slate-900">{number}</p><p className="text-slate-400">{date}</p></div><span className={`rounded-full px-2 py-1 font-bold ${status === "Paid" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>{status}</span><strong>{total}</strong></div>)}</div>
    </div>
  );
}

function CatalogPreview() {
  const rows = [["Strategy session", "Consulting", "$240"], ["Website maintenance", "Service", "$180"], ["Brand review", "Creative", "$320"]];
  return (
    <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200/80">
      <div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-wider text-teal-700">Items & services</p><p className="mt-1 font-display text-lg font-bold">Reusable catalog</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-100 text-violet-700"><i className="fas fa-layer-group" aria-hidden /></span></div>
      <div className="mt-5 space-y-2">{rows.map(([name, category, price], index) => <div key={name} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${index === 0 ? "bg-teal-100 text-teal-700" : index === 1 ? "bg-sky-100 text-sky-700" : "bg-violet-100 text-violet-700"}`}><i className="fas fa-briefcase text-xs" aria-hidden /></span><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-extrabold">{name}</p><p className="text-[8px] text-slate-400">{category} · Active</p></div><strong className="text-[10px] text-teal-800">{price}</strong></div>)}</div>
    </div>
  );
}

function ClientWorkflowVisual() {
  return (
    <div className="relative flex min-h-[640px] flex-col justify-between overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white shadow-xl sm:p-8">
      <div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-teal-500/20 blur-3xl" />
      <div className="relative rounded-3xl bg-white p-5 text-slate-900"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-teal-100 font-black text-teal-800">AR</span><div><p className="text-[8px] font-bold uppercase tracking-wider text-slate-400">Customer record</p><p className="font-display text-lg font-bold">Aster Road Studio</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-[9px]"><span className="rounded-xl bg-slate-50 p-3">Contact saved</span><span className="rounded-xl bg-teal-50 p-3 text-teal-800">Active customer</span></div></div>
      <div className="relative ml-6 border-l-2 border-dashed border-teal-400/50 py-5 pl-7"><span className="absolute -left-4 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full bg-teal-500 text-xs font-black">2</span><p className="text-[9px] font-bold uppercase tracking-wider text-teal-300">Choose reusable work</p><p className="mt-2 text-sm text-slate-300">Service name, description, and unit price move into the document.</p></div>
      <div className="relative rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-wider text-teal-300">Customer documents</p><p className="mt-1 font-display text-xl font-bold">Estimate to invoice</p></div><i className="fas fa-arrow-right text-teal-300" aria-hidden /></div><div className="mt-4 flex gap-2"><span className="flex-1 rounded-xl bg-white/10 p-3 text-[9px]">EST-0058<br /><b>Accepted</b></span><span className="flex-1 rounded-xl bg-white p-3 text-[9px] text-slate-900">INV-0062<br /><b>Sent</b></span></div></div>
      <div className="relative ml-6 border-l-2 border-dashed border-teal-400/50 py-5 pl-7"><span className="absolute -left-4 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full bg-emerald-500 text-xs font-black">4</span><p className="text-[9px] font-bold uppercase tracking-wider text-emerald-300">Return with context</p><p className="mt-2 text-sm text-slate-300">The customer profile keeps contact details, document history, status, and balance available for the next conversation.</p></div>
      <div className="relative rounded-3xl bg-teal-700 p-5"><p className="text-[8px] font-bold uppercase tracking-wider text-teal-100">Current position</p><div className="mt-3 flex items-end justify-between"><div><p className="font-display text-3xl font-black">$0</p><p className="text-[9px] text-teal-100">Balance after payment</p></div><span className="rounded-full bg-white/15 px-3 py-2 text-[9px] font-extrabold">PAID</span></div></div>
    </div>
  );
}

const faqItems = [
  ["What is client management software for small business?", "It is software for storing useful client details and keeping the work around each relationship easier to find. In Receipt Cycle, that means customer contact and billing information, status, notes, invoice count, outstanding balance, and linked document history. It is focused on billing context rather than a full sales CRM."],
  ["Can I keep customer contact information in Receipt Cycle?", "Yes. A customer record can include the contact name, company, email address, phone number, billing address, status, and internal notes. You can edit the record when details change and search the directory by customer, company, or email."],
  ["Does each customer record show invoice history?", "Yes. The customer workspace connects invoices to the saved customer. You can review invoice numbers, due dates, status, totals, invoice count, and the calculated amount still outstanding. Estimate, invoice, and payment actions remain in their dedicated workspaces."],
  ["Can I save services and prices for later invoices?", "Yes. The Items & Services catalog stores a product or service name, description, category, unit price, type, and active state. Those entries can be selected when building estimates or invoices so common work does not have to be typed again."],
  ["Is Receipt Cycle a customer database software product?", "Receipt Cycle provides a practical customer directory for billing work. It is suitable when you need searchable customer records connected to sales documents and balances. It is not a general-purpose database builder, marketing platform, or enterprise customer-data platform."],
  ["Does Receipt Cycle replace a CRM?", "No. Receipt Cycle does not claim lead scoring, opportunity pipelines, campaign automation, call logging, email-open tracking, or sales forecasting. Use it when the main need is keeping customer information close to estimates, invoices, payments, and reusable billing items."],
  ["Can freelancers use the client management app?", "Yes. Client management for freelancers often begins with a smaller need: keep the correct billing address, remember a useful note, find prior invoices, and reuse a familiar service price. Receipt Cycle supports that focused workflow without forcing a complex sales process."],
  ["Can I track outstanding balances by customer?", "Yes. The customer directory calculates the balance from connected invoices and recorded paid amounts. Open the customer to review the invoice entries behind that figure. Payment recording and receipt generation are explained on the dedicated payment tracking page."],
];

const audiences = [
  { id: "freelancers", title: "Freelancers", body: "Keep a repeat client's billing address, notes, past invoices, and current balance in one record. When the next project begins, select the familiar service from the catalog instead of rebuilding the commercial details from memory.", image: "/landing/audiences/client-freelancer.webp", alt: "Hand-drawn illustration of a freelancer reviewing an organized client profile and billing timeline" },
  { id: "consultants", title: "Consultants", body: "Return to the customer's history before preparing another engagement. Contact details, prior documents, and the current balance provide context, while reusable consulting services make the next estimate or invoice faster to assemble.", image: "/landing/audiences/client-consultant.webp", alt: "Hand-drawn illustration of a consultant reviewing a client document sequence during a meeting" },
  { id: "service-businesses", title: "Service businesses", body: "Save routine services with consistent descriptions and unit prices, then choose them for the right customer. The catalog supports repeatable billing without claiming inventory, scheduling, dispatch, or job-costing features.", image: "/landing/audiences/client-service-business.webp", alt: "Hand-drawn illustration of a service business owner choosing catalog services with a customer" },
  { id: "small-teams", title: "Small teams", body: "Give the person preparing an invoice a clearer record of who the customer is, what has already been billed, and what remains open. Receipt Cycle provides shared billing context without presenting itself as a full enterprise CRM.", image: "/landing/audiences/client-small-team.webp", alt: "Hand-drawn illustration of a small team reviewing customer records and billing status" },
];

export default function ClientManagementSoftwareLanding() {
  const [activeAudienceId, setActiveAudienceId] = useState("freelancers");
  const seo = getRouteSeo("/client-management-software");
  const primaryCta = "/signup?intent=customer";
  const activeAudience = audiences.find((item) => item.id === activeAudienceId) ?? audiences[0];

  const outcomes = [
    ["fa-address-card", "Keep the billing contact ready", "Store the name, company, email, phone, billing address, and notes used when preparing customer documents. Update the record once instead of correcting the same detail in several old files."],
    ["fa-file-lines", "Return to the document history", "Open the customer and review connected invoices with their due dates, status, and totals. Previous billing becomes part of the relationship context rather than a folder search."],
    ["fa-scale-balanced", "See the amount still open", "The customer list combines invoice totals and recorded paid amounts to show the outstanding balance. Open the history when you need to understand what created it."],
    ["fa-layer-group", "Reuse products and services", "Build an item catalog with descriptions, categories, unit prices, and active state. Add a familiar service to an estimate or invoice without typing it from the beginning."],
    ["fa-magnifying-glass", "Find the right record quickly", "Search customers by name, company, or email and separate active customers from prospects. A compact directory makes routine client tracking easier to scan."],
  ];

  return (
    <CommercialLandingLayout ctaLabel="Add a customer" ctaHref={primaryCta} announcement="Keep customer details, billing history, balances, and reusable services connected">
      {seo ? <Seo {...seo} /> : null}

      <section className="relative overflow-hidden bg-[#f8f5ee] py-16 sm:py-20 lg:py-24">
        <div className="absolute -left-24 top-0 h-72 w-72 rounded-full bg-amber-100/70 blur-3xl" /><div className="absolute -right-24 bottom-0 h-80 w-80 rounded-full bg-teal-100/70 blur-3xl" />
        <div className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 sm:px-8 lg:grid-cols-[0.84fr_1.16fr] lg:gap-16">
          <div className="max-w-xl"><h1 className="text-balance font-display text-4xl font-bold leading-[1.04] tracking-[-0.04em] sm:text-5xl lg:text-[3.45rem]"><span className="block text-slate-950">Client management software</span>{" "}<span className="mt-1 block text-teal-700">for small business billing</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-600">Keep customer details, document history, outstanding balances, and reusable services ready for the next estimate or invoice.</p><div className="mt-8"><LandingPrimaryCta to={primaryCta}>Add your first customer</LandingPrimaryCta><p className="mt-3 text-sm font-medium text-slate-500">No credit card required. Cancel paid plans anytime.</p></div></div>
          <CustomerDirectoryPreview compact />
        </div>
      </section>

      <section className="bg-[#dff5ef] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">The customer record behind every billing conversation</h2><p className="mt-4 text-base leading-7 text-slate-600">Customer management software earns its place when it answers practical questions before a document is created, followed up, or marked complete.</p></div><div className="mt-12 grid gap-4 md:grid-cols-6">{outcomes.map(([icon, title, body], index) => <article key={title} className={`rounded-3xl p-6 text-white shadow-sm ${index === 0 ? "bg-teal-950" : index === 1 ? "bg-teal-800" : index === 2 ? "bg-emerald-700" : index === 3 ? "bg-violet-700" : "bg-slate-800"} ${index < 3 ? "md:col-span-2" : "md:col-span-3"}`}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/15"><i className={`fas ${icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-white/80">{body}</p></article>)}</div></div></section>

      <section id="features" className="scroll-mt-28 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Customer details, billing context, and reusable work in one system</h2><p className="mt-4 text-base leading-7 text-slate-600">Receipt Cycle combines a focused customer database with the sales records a small service business uses. Each view has a specific job, so the page does not pretend every customer relationship needs an enterprise CRM.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-12">
        <article className="rounded-3xl bg-[#eef8f5] p-6 sm:p-8 lg:col-span-7"><CustomerDirectoryPreview compact /><h3 className="mt-8 font-display text-2xl font-bold">Scan the customer list before opening a file</h3><p className="mt-3 text-sm leading-7 text-slate-600">The directory puts company, contact, invoice count, outstanding balance, and customer status on one surface. Search reduces the time spent opening old invoices just to confirm which record belongs to the person who called.</p></article>
        <article className="rounded-3xl bg-[#fff1c7] p-6 sm:p-8 lg:col-span-5"><CustomerProfilePreview /><h3 className="mt-8 font-display text-2xl font-bold">Keep contact and billing details together</h3><p className="mt-3 text-sm leading-7 text-slate-700">A useful client record holds the information needed for customer billing: contact name, company, email, phone, billing address, status, and a note. The note can preserve a delivery preference or useful commercial context without becoming a project-management system.</p></article>
        <article className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8 lg:col-span-5"><BillingHistoryPreview /><h3 className="mt-8 font-display text-2xl font-bold">Understand the balance from the documents behind it</h3><p className="mt-3 text-sm leading-7 text-slate-300">A single balance is useful for scanning, but the invoice history explains it. Open a customer to see invoice numbers, due dates, status, and totals, then move to the invoice or payment workspace for the next action.</p></article>
        <article className="rounded-3xl bg-[#e9e3ff] p-6 sm:p-8 lg:col-span-7"><CatalogPreview /><h3 className="mt-8 font-display text-2xl font-bold">Save common work before the next document</h3><p className="mt-3 text-sm leading-7 text-slate-700">The item catalog stores products and services with a description, category, unit price, and active state. Select an entry while building an estimate or invoice, then adjust the document when the current job needs something different.</p></article>
        <article className="rounded-3xl bg-[#f8faf9] p-6 sm:p-8 lg:col-span-5"><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1">{[["Active", "Current billing relationship", "bg-emerald-100 text-emerald-700"], ["Prospect", "Record before work begins", "bg-violet-100 text-violet-700"], ["Inactive", "Retain history without mixing it into current work", "bg-slate-200 text-slate-700"]].map(([label, body, tone]) => <div key={label} className="rounded-2xl bg-white p-4 shadow-sm"><span className={`rounded-full px-3 py-1 text-[9px] font-extrabold ${tone}`}>{label}</span><p className="mt-3 text-xs leading-5 text-slate-500">{body}</p></div>)}</div><h3 className="mt-8 font-display text-2xl font-bold">Use status to keep the directory useful</h3><p className="mt-3 text-sm leading-7 text-slate-600">Customer status separates an active relationship, a prospect, and an inactive record. It is a simple organizing signal, not a sales opportunity pipeline or automated lead score.</p></article>
        <article className="rounded-3xl bg-teal-800 p-6 text-white sm:p-8 lg:col-span-7"><div className="grid gap-3 sm:grid-cols-3">{[["5", "Invoices"], ["$1,240", "Outstanding"], ["Active", "Customer status"]].map(([value, label]) => <div key={label} className="rounded-2xl bg-white/10 p-5"><p className="font-display text-2xl font-black text-teal-100">{value}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-wider text-teal-50/70">{label}</p></div>)}</div><h3 className="mt-8 font-display text-2xl font-bold">Bring the next conversation back to the customer</h3><p className="mt-3 text-sm leading-7 text-teal-50/80">Client invoice management is easier when the customer is more than a name on a PDF. The record provides a starting point for reviewing what has been billed, what is still open, and which details need to appear next time.</p></article>
      </div></div></section>

      <section className="bg-teal-950 py-14 text-white"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-7 px-4 sm:px-6 lg:flex-row lg:items-center"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Start with the customer, then build the document</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-100/80">Save the billing details once, choose the work, and keep the resulting history connected to the relationship.</p></div><LandingPrimaryCta to={primaryCta} inverse>Add your first customer</LandingPrimaryCta></div></section>

      <section id="workflow" className="scroll-mt-28 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid items-stretch gap-12 lg:grid-cols-[1fr_0.86fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">A customer-centered route from first record to paid work</h2><p className="mt-5 text-base leading-7 text-slate-600">A customer management system should reduce repeated setup without hiding the commercial trail. Receipt Cycle keeps each step understandable and sends detailed actions to the correct sales workspace.</p><ol className="mt-9 space-y-8">{[
        ["Create the customer record", "Add the contact and company information needed for billing. Include the billing address, customer status, and a short internal note when that context will matter again."],
        ["Choose a saved product or service", "Open the reusable catalog while building the sales document. Select the name, description, and unit price, then adjust quantities or document-specific details for the current work."],
        ["Prepare the estimate or invoice", "Use the dedicated estimate workflow when work needs approval first, or create the invoice when billing can begin. Each page owns its own document controls, preview, status, and next step."],
        ["Record payment and return to history", "When payment is recorded against an invoice, the paid amount changes the remaining balance. The customer record then gives the next conversation a more complete billing history."],
      ].map(([title, body], index) => <li key={title} className="grid grid-cols-[48px_1fr] gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-700 font-display text-lg font-bold text-white">{index + 1}</span><div><h3 className="font-display text-xl font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{body}</p></div></li>)}</ol></div><ClientWorkflowVisual /></div></div></section>

      <section className="bg-[#f8f5ee] py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid gap-12 lg:grid-cols-2"><div><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">A contact list remembers who. A billing-aware record also remembers what happened.</h2><p className="mt-5 text-base leading-7 text-slate-600">A spreadsheet or phone address book can store a name and email address. That may be enough until the customer asks which invoice is open, whether the last project was paid, or what service price was used before.</p><p className="mt-4 text-base leading-7 text-slate-600">Receipt Cycle connects the client record to the operational context around estimates, invoices, and balances. It does not turn that relationship into an oversized sales process. The distinction matters for freelancers and small businesses that need customer billing software without adopting a full CRM administration workload.</p></div><div className="grid gap-4 sm:grid-cols-2">{[
        ["Basic contact list", "Name, company, phone, email, and perhaps an address. Useful for communication, but separate from the documents that created the balance.", "fa-address-book", "bg-white"],
        ["Receipt Cycle customer record", "Contact and billing details, notes, status, invoice count, document history, totals, and outstanding balance in a focused sales directory.", "fa-link", "bg-[#dff5ef]"],
        ["Generic product list", "A repeated description and price copied from an old document, with no clear active state or category.", "fa-copy", "bg-white"],
        ["Reusable item catalog", "Products and services saved with description, category, unit price, type, and availability for later sales documents.", "fa-layer-group", "bg-[#fff1c7]"],
      ].map(([title, body, icon, tone]) => <article key={title} className={`rounded-3xl p-6 shadow-sm ring-1 ring-slate-200/70 ${tone}`}><i className={`fas ${icon} text-teal-700`} aria-hidden /><h3 className="mt-4 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p></article>)}</div></div></div></section>

      <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Client records for the way small service businesses bill</h2><p className="mt-4 text-base leading-7 text-slate-600">The same customer management app supports different working relationships when the record stays focused. Choose an audience to see how the illustration and use case change together.</p></div><div className="mt-12 grid items-stretch gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div id="client-audience-panel" role="tabpanel" aria-labelledby={`client-audience-tab-${activeAudience.id}`} className="min-w-0 overflow-hidden rounded-3xl border border-teal-100 bg-[#f8f5ee] shadow-sm"><img key={activeAudience.image} src={activeAudience.image} alt={activeAudience.alt} width="1586" height="992" loading="lazy" decoding="async" sizes="(min-width: 1024px) 720px, (min-width: 640px) 90vw, 100vw" className="block h-auto w-full" /></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white px-5 sm:px-6" role="tablist" aria-label="Client management audiences">{audiences.map((audience) => { const isActive = audience.id === activeAudience.id; return <div key={audience.id} className="border-b border-slate-200 last:border-b-0"><button id={`client-audience-tab-${audience.id}`} type="button" role="tab" aria-selected={isActive} aria-controls="client-audience-panel" tabIndex={isActive ? 0 : -1} onClick={() => setActiveAudienceId(audience.id)} onKeyDown={(event) => { const currentIndex = audiences.findIndex((item) => item.id === audience.id); let nextIndex = currentIndex; if (event.key === "ArrowDown" || event.key === "ArrowRight") nextIndex = (currentIndex + 1) % audiences.length; if (event.key === "ArrowUp" || event.key === "ArrowLeft") nextIndex = (currentIndex - 1 + audiences.length) % audiences.length; if (event.key === "Home") nextIndex = 0; if (event.key === "End") nextIndex = audiences.length - 1; if (nextIndex === currentIndex) return; event.preventDefault(); const next = audiences[nextIndex]; setActiveAudienceId(next.id); requestAnimationFrame(() => document.getElementById(`client-audience-tab-${next.id}`)?.focus()); }} className="flex min-h-16 w-full items-center justify-between gap-4 py-4 text-left font-display text-lg font-bold text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-teal-500">{audience.title}<span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full transition ${isActive ? "rotate-45 bg-teal-700 text-white" : "bg-teal-50 text-teal-700"}`}><i className="fas fa-plus text-xs" aria-hidden /></span></button>{isActive ? <p className="pb-6 pr-4 text-sm leading-7 text-slate-600">{audience.body}</p> : null}</div>; })}</div></div></div></section>

      <section className="bg-slate-950 py-20 text-white sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Focused client tracking without an invented CRM layer</h2><p className="mt-5 text-base leading-7 text-slate-300">Receipt Cycle is strongest when the customer record supports estimates, invoices, payments, and the reusable catalog. It is not presented as software for every sales, marketing, support, or project workflow.</p><p className="mt-4 text-base leading-7 text-slate-300">If your buying requirement is pipeline automation or complex account management, choose a dedicated CRM. If it is customer management for small business billing, the narrower workspace can be easier to maintain.</p></div><div className="grid gap-4 sm:grid-cols-2">{[
        ["Included", "Searchable customer profiles, contact and billing details, status, notes, invoice history, invoice count, and outstanding balance.", "fa-circle-check", "text-teal-300"],
        ["Catalog context", "Reusable products and services with descriptions, categories, unit prices, type, and active state.", "fa-boxes-stacked", "text-violet-300"],
        ["Not a sales CRM", "No lead scoring, opportunity pipeline, automated follow-up, campaign management, or sales forecasting claims.", "fa-chart-line", "text-rose-300"],
        ["Not operations software", "No inventory, job scheduling, dispatch, contract management, or project delivery workflow claims.", "fa-screwdriver-wrench", "text-amber-300"],
      ].map(([title, body, icon, tone]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-6"><i className={`fas ${icon} ${tone}`} aria-hidden /><h3 className="mt-4 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{body}</p></article>)}</div></div></div></section>

      <section className="bg-[#eef8f5] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold text-slate-950 sm:text-4xl">Follow the customer through the connected sales cycle</h2><p className="mt-4 text-base leading-7 text-slate-600">The client profile holds the relationship context. The neighboring pages handle the commercial documents and payment record in detail.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[
        ["Prepare the proposed work", "Build a structured estimate with services, quantities, rates, tax, discounts, terms, and a validity period before invoicing begins.", "/estimate-quotation-software/", "Estimate software", "fa-file-signature"],
        ["Create the customer invoice", "Turn approved work into a professional invoice, review line items and totals, and track whether the document is draft, sent, paid, or overdue.", "/invoice-software/", "Invoice software", "fa-file-invoice-dollar"],
        ["Record what was paid", "Add full or partial payments to the invoice, preserve the payment method and reference, update the balance, and produce a receipt.", "/payment-tracking-software/", "Payment tracking", "fa-credit-card"],
      ].map(([title, body, href, label, icon], index) => <article key={title} className={`rounded-3xl p-7 shadow-sm ${index === 0 ? "bg-white" : index === 1 ? "bg-teal-800 text-white" : "bg-[#fff1c7]"}`}><span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${index === 1 ? "bg-white/15 text-white" : "bg-teal-100 text-teal-700"}`}><i className={`fas ${icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className={`mt-3 text-sm leading-7 ${index === 1 ? "text-teal-50/80" : "text-slate-600"}`}>{body}</p><Link to={href} className={`mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold ${index === 1 ? "text-teal-100" : "text-teal-700"}`}>{label}<i className="fas fa-arrow-right text-xs" aria-hidden /></Link></article>)}</div></div></section>

      <section className="py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold text-slate-950 sm:text-4xl">Resources for choosing a practical customer workflow</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[
        ["Compare Receipt Cycle plans", "Review the current plan options and decide which sales and finance workspace fits the way you work.", "/pricing", "fa-tags"],
        ["Read common product answers", "Check account, platform, billing, and workflow questions before creating your first customer record.", "/faq", "fa-circle-question"],
        ["Speak with the team", "Ask a specific question about your customer and invoicing workflow when the public information is not enough.", "/contact", "fa-comments"],
      ].map(([title, body, href, icon]) => <article key={title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><i className={`fas ${icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p><Link to={href} className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold text-teal-700">Open resource<i className="fas fa-arrow-right text-xs" aria-hidden /></Link></article>)}</div></div></section>

      <section className="bg-[#f8f5ee] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 lg:grid-cols-2"><div className="bg-[#fff1c7] p-8 sm:p-10"><h2 className="font-display text-3xl font-bold text-slate-950">Get help when a customer balance or document history looks wrong</h2><p className="mt-4 text-base leading-7 text-slate-600">Open the customer and review the linked invoices first. Check each total, paid amount, and status. If a document belongs to another customer or a payment has not been recorded, correct the source record rather than editing a summary number.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex min-h-11 items-center rounded-xl bg-teal-700 px-5 text-sm font-bold text-white">Contact us</Link><Link to="/faq" className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-700">Visit the FAQ</Link></div></div><div className="grid gap-px bg-slate-200 sm:grid-cols-3 lg:grid-cols-1">{[
        ["fa-user-check", "Confirm the customer", "Make sure the invoice is attached to the intended customer record."],
        ["fa-file-invoice", "Review the source", "The outstanding amount comes from invoice totals and recorded paid amounts."],
        ["fa-envelope", "Product support", "Email support@receiptcycle.com with the page, device, and steps involved."],
      ].map(([icon, title, body]) => <div key={title} className="bg-[#f8faf9] p-6"><i className={`fas ${icon} text-teal-700`} aria-hidden /><h3 className="mt-3 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{body}</p></div>)}</div></div></div></section>

      <section id="faq" className="scroll-mt-28 py-20 sm:py-24"><div className="mx-auto max-w-5xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Frequently Asked Questions</h2><div className="mt-10 divide-y divide-slate-300 border-y border-slate-300">{faqItems.map(([question, answer], index) => <details key={question} className="group py-1" open={index === 0}><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 py-4 text-left text-sm font-extrabold text-slate-900 marker:content-none sm:text-base">{question}<span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-teal-50 text-teal-700 transition group-open:rotate-45"><i className="fas fa-plus text-xs" aria-hidden /></span></summary><p className="max-w-4xl pb-6 pr-12 text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

      <section className="bg-gradient-to-br from-teal-800 via-teal-700 to-emerald-600 py-16 text-white"><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 text-center sm:px-6 lg:grid-cols-[1fr_auto] lg:text-left"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Give the next invoice a complete customer record</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-50/90">Save the contact, keep billing history close, and reuse the products or services your business already knows.</p></div><LandingPrimaryCta to={primaryCta} inverse>Add your first customer</LandingPrimaryCta></div></section>
    </CommercialLandingLayout>
  );
}
