import { useState } from "react";
import { Link } from "react-router-dom";
import { CommercialLandingLayout, LandingPrimaryCta } from "@/components/marketing/CommercialLandingLayout";
import { Seo } from "@/components/Seo";
import { getRouteSeo } from "@/content/routesSeo";

const months = [
  { name: "May", income: 54, expense: 32 },
  { name: "Jun", income: 70, expense: 45 },
  { name: "Jul", income: 62, expense: 51 },
  { name: "Aug", income: 84, expense: 58 },
  { name: "Sep", income: 75, expense: 48 },
  { name: "Oct", income: 92, expense: 61 },
];

function ReportDashboardPreview({ compact = false }: { compact?: boolean }) {
  return (
    <div className="relative mx-auto w-full max-w-[690px] rounded-[2rem] bg-teal-950 p-4 shadow-2xl shadow-teal-950/20 sm:p-6" role="img" aria-label="Receipt Cycle report dashboard showing income, expenses, net movement, outstanding invoices, and monthly cash flow">
      <div className="overflow-hidden rounded-[1.4rem] bg-[#f8faf9]">
        <div className="flex items-center justify-between border-b border-slate-200 bg-white px-4 py-4 sm:px-5"><div><p className="text-[8px] font-black uppercase tracking-[0.18em] text-teal-700">Business reports</p><p className="mt-1 font-display text-lg font-bold text-slate-950">October overview</p></div><span className="rounded-xl bg-teal-50 px-3 py-2 text-[9px] font-extrabold text-teal-800">THIS MONTH</span></div>
        <div className="p-4 sm:p-5">
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 sm:gap-3">{[["Income", "$12,840", "text-teal-700"], ["Expenses", "$7,460", "text-rose-700"], ["Net movement", "$5,380", "text-slate-950"], ["Outstanding", "$2,140", "text-violet-700"]].map(([label, value, tone]) => <div key={label} className="rounded-xl bg-white p-3 shadow-sm ring-1 ring-slate-200/70"><p className="text-[7px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-2 font-display text-sm font-black sm:text-base ${tone}`}>{value}</p></div>)}</div>
          <div className={`mt-4 rounded-2xl bg-white shadow-sm ring-1 ring-slate-200/70 ${compact ? "p-3" : "p-4"}`}><div className="flex items-center justify-between"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">Income vs expenses</p><span className="text-[8px] font-bold text-slate-400">6 MONTHS</span></div><div className="mt-4 flex h-32 items-end gap-3 border-b border-slate-200 px-1 sm:h-40 sm:gap-4">{months.map((month) => <div key={month.name} className="flex h-full flex-1 flex-col justify-end"><div className="flex flex-1 items-end justify-center gap-1"><span className="w-2 rounded-t bg-teal-600 sm:w-3" style={{ height: `${month.income}%` }} /><span className="w-2 rounded-t bg-rose-400 sm:w-3" style={{ height: `${month.expense}%` }} /></div><span className="py-2 text-center text-[7px] font-bold text-slate-400">{month.name}</span></div>)}</div><div className="mt-3 flex justify-center gap-4 text-[8px] text-slate-500"><span><i className="fas fa-square mr-1 text-teal-600" aria-hidden />Income</span><span><i className="fas fa-square mr-1 text-rose-400" aria-hidden />Expenses</span></div></div>
        </div>
      </div>
    </div>
  );
}

function CategoryBreakdownPreview() {
  const categories = [["Software", "$1,820", "42%", "bg-violet-500"], ["Travel", "$1,190", "28%", "bg-teal-600"], ["Supplies", "$760", "18%", "bg-amber-500"], ["Other", "$510", "12%", "bg-rose-400"]];
  return (
    <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200/80"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-wider text-teal-700">Expense distribution</p><p className="mt-1 font-display text-lg font-bold">By category</p></div><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[conic-gradient(#8b5cf6_0_42%,#0d9488_42%_70%,#f59e0b_70%_88%,#fb7185_88%)]"><span className="h-5 w-5 rounded-full bg-white" /></span></div><div className="mt-5 space-y-3">{categories.map(([name, total, share, tone]) => <div key={name}><div className="flex items-center justify-between text-[9px]"><span className="font-extrabold text-slate-800">{name}</span><span className="font-bold text-slate-500">{total} · {share}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${tone}`} style={{ width: share }} /></div></div>)}</div></div>
  );
}

function CashFlowPreview() {
  return (
    <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200/80"><div className="grid grid-cols-3 gap-2">{[["Inflow", "$42.6k", "text-teal-700"], ["Outflow", "$27.4k", "text-rose-700"], ["Net", "$15.2k", "text-slate-950"]].map(([label, value, tone]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-[7px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className={`mt-2 font-display text-sm font-black ${tone}`}>{value}</p></div>)}</div><div className="mt-5 flex h-40 items-end gap-3 border-b border-slate-200">{months.map((month) => <div key={month.name} className="flex h-full flex-1 flex-col justify-end"><div className="flex flex-1 items-end justify-center gap-1"><span className="w-3 rounded-t bg-teal-600" style={{ height: `${month.income}%` }} /><span className="w-3 rounded-t bg-rose-400" style={{ height: `${month.expense}%` }} /></div><span className="py-2 text-center text-[7px] font-bold text-slate-400">{month.name}</span></div>)}</div></div>
  );
}

function AgingPreview() {
  return (
    <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200/80"><div className="flex items-end justify-between"><div><p className="text-[8px] font-bold uppercase tracking-wider text-rose-600">Invoice aging</p><p className="mt-1 font-display text-lg font-bold">Overdue balances</p></div><div className="text-right"><p className="font-display text-xl font-black text-rose-700">$2,140</p><p className="text-[8px] text-slate-400">3 invoices</p></div></div><div className="mt-5 space-y-2">{[["Marlow Creative", "INV-0054", "$1,240", "18 days"], ["Northstar Design", "INV-0048", "$680", "11 days"], ["Field Office", "INV-0043", "$220", "6 days"]].map(([customer, invoice, total, age]) => <div key={invoice} className="grid grid-cols-[1fr_auto] gap-3 rounded-xl bg-rose-50 p-3 text-[9px]"><div><p className="font-extrabold text-slate-900">{customer}</p><p className="mt-1 text-slate-500">{invoice} · {age} late</p></div><strong className="self-center text-rose-700">{total}</strong></div>)}</div></div>
  );
}

function AiAnalysisPreview() {
  return (
    <div className="rounded-2xl bg-slate-950 p-5 text-white shadow-sm"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-violet-500/20 text-violet-300"><i className="fas fa-wand-magic-sparkles" aria-hidden /></span><div><p className="text-[8px] font-bold uppercase tracking-wider text-violet-300">Record-grounded analysis</p><p className="mt-1 font-display text-lg font-bold">Ask about the period</p></div></div><div className="mt-5 rounded-xl bg-white/10 p-4"><p className="text-[9px] font-extrabold text-violet-200">QUESTION</p><p className="mt-2 text-xs leading-5 text-white">Which categories changed most compared with the earlier period?</p></div><div className="mt-3 rounded-xl bg-white p-4 text-slate-900"><p className="text-[9px] font-extrabold text-teal-700">BASED ON SAVED RECORDS</p><div className="mt-3 space-y-2">{[["Software", "+18%", "bg-violet-500"], ["Travel", "+11%", "bg-teal-500"], ["Supplies", "-6%", "bg-amber-500"]].map(([label, value, tone]) => <div key={label} className="flex items-center gap-2 text-[9px]"><span className={`h-2.5 w-2.5 rounded-full ${tone}`} /><span className="flex-1 font-bold">{label}</span><strong>{value}</strong></div>)}</div></div><p className="mt-3 text-[8px] leading-4 text-slate-400">Analysis supports review. It does not alter records or replace professional judgment.</p></div>
  );
}

function ReportingWorkflowVisual() {
  return (
    <div className="relative flex min-h-[720px] flex-col justify-between overflow-hidden rounded-[2rem] bg-teal-950 p-6 text-white shadow-xl sm:p-8"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-violet-500/20 blur-3xl" />
      <div className="relative rounded-3xl bg-white p-5 text-slate-900"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-wider text-teal-700">Saved source records</p><p className="mt-1 font-display text-lg font-bold">Transactions and sales</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-100 text-teal-700"><i className="fas fa-database" aria-hidden /></span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-[8px] font-extrabold"><span className="rounded-xl bg-rose-50 p-3 text-rose-700">EXPENSES</span><span className="rounded-xl bg-teal-50 p-3 text-teal-700">INCOME</span><span className="rounded-xl bg-violet-50 p-3 text-violet-700">INVOICES</span></div></div>
      <div className="relative ml-6 border-l-2 border-dashed border-teal-400/50 py-5 pl-7"><span className="absolute -left-4 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full bg-teal-500 text-xs font-black">2</span><p className="text-[9px] font-bold uppercase tracking-wider text-teal-300">Choose the reporting period</p><p className="mt-2 text-sm leading-6 text-slate-300">Review this month, all loaded history, the last six months, or the current year where the report supports it.</p></div>
      <div className="relative rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur"><p className="text-[8px] font-bold uppercase tracking-wider text-teal-300">Calculated view</p><div className="mt-4 grid grid-cols-3 gap-2">{[["$12.8k", "Income"], ["$7.5k", "Expenses"], ["$5.3k", "Net"]].map(([value, label]) => <div key={label} className="rounded-xl bg-white/10 p-3"><p className="font-display text-base font-black text-white">{value}</p><p className="mt-1 text-[7px] uppercase tracking-wide text-teal-100/70">{label}</p></div>)}</div><div className="mt-4 flex h-24 items-end gap-2 border-b border-white/10">{[38, 65, 48, 78, 56, 88].map((height, index) => <span key={index} className="flex-1 rounded-t bg-teal-400" style={{ height: `${height}%` }} />)}</div></div>
      <div className="relative ml-6 border-l-2 border-dashed border-violet-400/50 py-5 pl-7"><span className="absolute -left-4 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full bg-violet-500 text-xs font-black">4</span><p className="text-[9px] font-bold uppercase tracking-wider text-violet-300">Investigate the movement</p><p className="mt-2 text-sm leading-6 text-slate-300">Open the category, overdue invoice, or underlying record before treating the summary as an explanation.</p></div>
      <div className="relative rounded-3xl bg-[#fff1c7] p-5 text-slate-900"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-wider text-amber-700">Prepared for review</p><p className="mt-1 font-display text-lg font-bold">Explainable business context</p></div><i className="fas fa-circle-check text-2xl text-teal-700" aria-hidden /></div><p className="mt-3 text-[10px] leading-5 text-slate-600">Summary, category detail, invoice exposure, and source records remain connected.</p></div>
    </div>
  );
}

const audiences = [
  { id: "freelancers", title: "Freelancers", body: "Review business income and expenses for the month without rebuilding totals from old receipts and invoices. Category views show where spending concentrated, while the source transactions remain available when a number needs an explanation.", image: "/landing/audiences/report-freelancer.webp", alt: "Hand-drawn illustration of a freelancer reviewing monthly income, expenses, and category reports" },
  { id: "owners", title: "Small-business owners", body: "Compare inflow and outflow, check net movement, see payments received, and keep overdue invoice exposure visible. The report helps frame the next question without claiming to replace formal accounting statements.", image: "/landing/audiences/report-small-business-owner.webp", alt: "Hand-drawn illustration of a small-business owner reviewing cash movement and overdue invoices" },
  { id: "administrators", title: "Operations administrators", body: "Prepare a consistent period review from saved records, then follow category totals, payment history, or invoice status back to the underlying entries. Export supported transaction data when another review tool needs it.", image: "/landing/audiences/report-operations-admin.webp", alt: "Hand-drawn illustration of an operations administrator tracing report summaries to source records" },
  { id: "advisers", title: "Accountants and advisers", body: "Receive a more organized starting point with transaction history, category totals, cash-flow context, and invoice exposure. Receipt Cycle improves the handoff, but the professional still determines the accounting, tax, and reporting treatment.", image: "/landing/audiences/report-accountant-adviser.webp", alt: "Hand-drawn illustration of an adviser reviewing organized reports and source records with a business owner" },
];

const faqItems = [
  ["What does Receipt Cycle expense report software show?", "The reporting workspace summarizes saved income and expense records for the selected period. It shows income, expenses, net movement, record count, category distribution, cash-flow comparisons, payments received, paid-invoice counts, outstanding invoices, and overdue invoice context where those records are available."],
  ["Can I review monthly income and expense reports?", "Yes. The main report can focus on the current month or all available records. The cash-flow report can compare the last six months or the current year using monthly income and expense bars, total inflow, total outflow, and net cash movement."],
  ["Does the expense reporting app show category spending?", "Yes. Receipt Cycle groups saved expense records by category, calculates category totals and transaction counts, and shows the largest categories in a distribution view. Open the transaction workspace when a category needs correction or record-level review."],
  ["Can it report on invoices and payments?", "The report dashboard includes outstanding invoice value, payments received, and paid-invoice counts. A separate overdue view shows overdue amount, invoice count, average days overdue, customer, balance, and due status. Recording a payment remains part of the dedicated payment workflow."],
  ["Does Receipt Cycle create automated expense reports?", "The totals and charts recalculate from the saved records available to the selected period, so routine summaries do not need to be rebuilt manually. Receipt Cycle does not claim automatic employee claim submission, approval routing, reimbursement processing, scheduled email delivery, or automatic filing."],
  ["Can I export a business expense report?", "Supported plans and workspaces can export transaction data as CSV for use in a spreadsheet or professional review. The export is structured transaction data, not a generated tax return, statutory financial statement, PDF claim packet, or guaranteed bundle of receipt images."],
  ["What can the AI analysis do with my reports?", "AI-assisted analysis can use a limited structured slice of saved transaction fields to answer questions about category totals, merchant patterns, period comparisons, recurring charges, possible duplicate entries, unusual patterns, and plain-language activity summaries. It does not alter records or make regulated financial decisions."],
  ["Is this financial reporting software for small business accounting?", "Receipt Cycle provides operational reporting for saved transactions and connected sales records. It does not claim a general ledger, balance sheet, statutory profit-and-loss statement, bank reconciliation, payroll, inventory accounting, audit assurance, or automatic tax filing."],
];

export default function ExpenseReportingSoftwareLanding() {
  const [activeAudienceId, setActiveAudienceId] = useState("freelancers");
  const seo = getRouteSeo("/expense-reporting-software");
  const primaryCta = "/signup?intent=report";
  const activeAudience = audiences.find((item) => item.id === activeAudienceId) ?? audiences[0];
  const outcomes = [
    ["fa-chart-column", "Read the period at a glance", "See income, expenses, net movement, transaction count, and outstanding invoice value before deciding which part of the business needs a closer look."],
    ["fa-chart-pie", "Explain where spending went", "Category analysis turns one expense total into named groups with amounts and record counts. The original transactions remain available when a category needs checking."],
    ["fa-wave-square", "Compare cash movement over time", "Monthly bars put income and expenses side by side across six months or the current year. Inflow, outflow, and net cash flow show the period's direction."],
    ["fa-file-circle-exclamation", "Keep invoice exposure visible", "Outstanding and overdue invoices stay near the expense and income picture. Review balances, due status, and age without treating invoiced revenue as received cash."],
    ["fa-wand-magic-sparkles", "Ask a question grounded in records", "Use supported AI analysis for category totals, merchant patterns, period comparisons, or possible spending anomalies. Answers remain limited to the records supplied."],
  ];

  return (
    <CommercialLandingLayout ctaLabel="Create a reporting workspace" ctaHref={primaryCta} announcement="Review spending, income, cash movement, payments, and invoice exposure from connected records">
      {seo ? <Seo {...seo} /> : null}

      <section className="relative overflow-hidden bg-[#f8f5ee] py-16 sm:py-20 lg:py-24"><div className="absolute -left-24 top-0 h-72 w-72 rounded-full bg-amber-100/70 blur-3xl" /><div className="absolute -right-24 bottom-0 h-80 w-80 rounded-full bg-teal-100/70 blur-3xl" /><div className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 sm:px-8 lg:grid-cols-[0.82fr_1.18fr] lg:gap-16"><div className="max-w-xl"><h1 className="text-balance font-display text-4xl font-bold leading-[1.04] tracking-[-0.04em] sm:text-5xl lg:text-[3.45rem]"><span className="block text-slate-950">Expense report software</span>{" "}<span className="mt-1 block text-teal-700">for a complete business view</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-600">Review income, expenses, category spending, cash movement, payments, and overdue invoices without rebuilding the month by hand.</p><div className="mt-8"><LandingPrimaryCta to={primaryCta}>Create your reporting workspace</LandingPrimaryCta><p className="mt-3 text-sm font-medium text-slate-500">No credit card required. Cancel paid plans anytime.</p></div></div><ReportDashboardPreview compact /></div></section>

      <section className="bg-[#dff5ef] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">A useful report answers the next business question</h2><p className="mt-4 text-base leading-7 text-slate-600">Business expense reporting software should do more than display a large total. It should show what changed, where the amount came from, and which record deserves attention.</p></div><div className="mt-12 grid gap-4 md:grid-cols-6">{outcomes.map(([icon, title, body], index) => <article key={title} className={`rounded-3xl p-6 text-white shadow-sm ${index === 0 ? "bg-teal-950" : index === 1 ? "bg-teal-800" : index === 2 ? "bg-emerald-700" : index === 3 ? "bg-rose-700" : "bg-violet-700"} ${index < 3 ? "md:col-span-2" : "md:col-span-3"}`}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/15"><i className={`fas ${icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-white/80">{body}</p></article>)}</div></div></section>

      <section id="features" className="scroll-mt-28 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Reporting views for the totals and the records behind them</h2><p className="mt-4 text-base leading-7 text-slate-600">Receipt Cycle brings expense management and reporting into the same workspace, so a chart can lead back to the transaction, invoice, or payment that shaped it.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-12">
        <article className="rounded-3xl bg-[#eef8f5] p-6 sm:p-8 lg:col-span-7"><ReportDashboardPreview compact /><h3 className="mt-8 font-display text-2xl font-bold">Begin with the whole period</h3><p className="mt-3 text-sm leading-7 text-slate-600">The financial dashboard summarizes income, expenses, net movement, outstanding invoices, and the number of saved records. Switch between the current month and all available history before deciding which figure needs investigation.</p></article>
        <article className="rounded-3xl bg-[#e9e3ff] p-6 sm:p-8 lg:col-span-5"><CategoryBreakdownPreview /><h3 className="mt-8 font-display text-2xl font-bold">Turn the expense total into a spending breakdown</h3><p className="mt-3 text-sm leading-7 text-slate-700">Category totals and transaction counts show whether software, travel, supplies, or another group drove the period. An expense report app cannot correct a weak category automatically, so the source records remain editable in the transaction workspace.</p></article>
        <article className="rounded-3xl bg-[#fff1c7] p-6 sm:p-8 lg:col-span-7"><CashFlowPreview /><h3 className="mt-8 font-display text-2xl font-bold">Compare inflow and outflow across recent months</h3><p className="mt-3 text-sm leading-7 text-slate-700">The cash-flow report shows total inflow, total outflow, net movement, and monthly bars for the last six months or the current year. It describes saved cash activity; it is not a bank reconciliation or forecast.</p></article>
        <article className="rounded-3xl bg-rose-50 p-6 sm:p-8 lg:col-span-5"><AgingPreview /><h3 className="mt-8 font-display text-2xl font-bold">Separate earned work from received cash</h3><p className="mt-3 text-sm leading-7 text-slate-700">Invoice reports keep outstanding and overdue balances visible beside transaction reporting. Filter overdue, due-soon, and paid records, then open the invoice or prepare a reminder email from the dedicated aging view.</p></article>
        <article className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8 lg:col-span-5"><AiAnalysisPreview /><h3 className="mt-8 font-display text-2xl font-bold">Use AI financial insights as a review aid</h3><p className="mt-3 text-sm leading-7 text-slate-300">Ask about category totals, merchant patterns, changes between periods, recurring charges, duplicate entries, or unusual spending. The analysis uses a limited structured slice of saved records and does not rewrite the ledger.</p></article>
        <article className="rounded-3xl bg-teal-800 p-6 text-white sm:p-8 lg:col-span-7"><div className="grid gap-3 sm:grid-cols-3">{[["$9,420", "Payments received"], ["7", "Paid invoices"], ["$2,140", "Still outstanding"]].map(([value, label]) => <div key={label} className="rounded-2xl bg-white/10 p-5"><p className="font-display text-2xl font-black text-teal-100">{value}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-wider text-teal-50/70">{label}</p></div>)}</div><h3 className="mt-8 font-display text-2xl font-bold">Add payment and invoice context to business spending reports</h3><p className="mt-3 text-sm leading-7 text-teal-50/80">Expense data explains money leaving the business. Payment and invoice summaries show what customers have paid and what remains open. Keeping both views nearby prevents sales documents from being mistaken for cash already received.</p></article>
      </div></div></section>

      <section className="bg-teal-950 py-14 text-white"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-7 px-4 sm:px-6 lg:flex-row lg:items-center"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Know the total, then follow it back to the record</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-100/80">Use the report to find the question. Use the source entry to understand and correct the answer.</p></div><LandingPrimaryCta to={primaryCta} inverse>Create your reporting workspace</LandingPrimaryCta></div></section>

      <section id="workflow" className="scroll-mt-28 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid items-stretch gap-12 lg:grid-cols-[1fr_0.86fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Move from saved activity to an explainable business report</h2><p className="mt-5 text-base leading-7 text-slate-600">Small business expense reporting becomes trustworthy through a repeatable review routine. The summary is calculated from the records, and the records remain available when the summary raises a question.</p><ol className="mt-9 space-y-8">{[
        ["Capture and classify the source activity", "Save income and expense transactions with the right date, type, category, account, merchant, and description. Attach receipt evidence where available, and keep sales documents connected to customers and payments."],
        ["Choose the period that matches the decision", "Review the current month for operating questions, all available records for a wider view, or the cash-flow periods for a six-month or current-year comparison."],
        ["Read the headline position", "Start with income, expenses, net movement, record count, payments received, outstanding invoice value, and the direction of recent cash movement."],
        ["Open the part that changed", "Use category analysis, transaction lists, invoice aging, or AI-assisted questions to identify the records responsible for an unusual total or a movement between periods."],
        ["Correct the record or prepare the handoff", "Edit inaccurate source data before relying on the report. Export supported CSV fields when a spreadsheet, adviser, or another approved review process needs the transaction data."],
      ].map(([title, body], index) => <li key={title} className="grid grid-cols-[48px_1fr] gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-700 font-display text-lg font-bold text-white">{index + 1}</span><div><h3 className="font-display text-xl font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{body}</p></div></li>)}</ol></div><ReportingWorkflowVisual /></div></div></section>

      <section className="bg-[#f8f5ee] py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid gap-12 lg:grid-cols-[0.92fr_1.08fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Reporting quality begins before the chart appears</h2><p className="mt-5 text-base leading-7 text-slate-600">A polished chart cannot repair a transaction saved with the wrong amount, date, type, or category. Business financial reports reflect the records available to them. That makes capture and review part of the reporting process, not a separate housekeeping task.</p><p className="mt-4 text-base leading-7 text-slate-600">Receipt Cycle keeps the high-level view close to the records that produced it. When travel spending rises, open the category. When cash movement changes, compare the monthly bars and transactions. When outstanding value grows, inspect invoice aging rather than treating the total as cash.</p><p className="mt-4 text-base leading-7 text-slate-600">This relationship between summary and source is what makes the report useful for a decision. It also creates a clearer handoff when a bookkeeper, accountant, or adviser needs to apply professional rules outside Receipt Cycle.</p></div><div className="grid gap-4 sm:grid-cols-2">{[
        ["Source record", "Date, amount, income or expense type, category, merchant, account, payment method, description, and available receipt evidence.", "fa-receipt", "bg-white"],
        ["Calculated summary", "Period income, expenses, net movement, transaction count, category totals, and cash-flow comparisons.", "fa-calculator", "bg-[#dff5ef]"],
        ["Sales context", "Payments received, paid-invoice count, outstanding balance, overdue value, and invoice aging.", "fa-file-invoice-dollar", "bg-[#fff1c7]"],
        ["Human interpretation", "Why the number changed, whether the record is correct, and what accounting, tax, or operating action should follow.", "fa-user-check", "bg-[#e9e3ff]"],
      ].map(([title, body, icon, tone]) => <article key={title} className={`rounded-3xl p-6 shadow-sm ring-1 ring-slate-200/70 ${tone}`}><i className={`fas ${icon} text-teal-700`} aria-hidden /><h3 className="mt-4 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p></article>)}</div></div></div></section>

      <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Reporting for the people who ask different questions</h2><p className="mt-4 text-base leading-7 text-slate-600">A financial reporting software view can support several roles without pretending they share the same responsibility. Choose an audience to change both the use case and the illustration.</p></div><div className="mt-12 grid items-stretch gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div id="report-audience-panel" role="tabpanel" aria-labelledby={`report-audience-tab-${activeAudience.id}`} className="min-w-0 overflow-hidden rounded-3xl border border-teal-100 bg-[#f8f5ee] shadow-sm"><img key={activeAudience.image} src={activeAudience.image} alt={activeAudience.alt} width="1586" height="992" loading="lazy" decoding="async" sizes="(min-width: 1024px) 720px, (min-width: 640px) 90vw, 100vw" className="block h-auto w-full" /></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white px-5 sm:px-6" role="tablist" aria-label="Expense reporting audiences">{audiences.map((audience) => { const isActive = audience.id === activeAudience.id; return <div key={audience.id} className="border-b border-slate-200 last:border-b-0"><button id={`report-audience-tab-${audience.id}`} type="button" role="tab" aria-selected={isActive} aria-controls="report-audience-panel" tabIndex={isActive ? 0 : -1} onClick={() => setActiveAudienceId(audience.id)} onKeyDown={(event) => { const currentIndex = audiences.findIndex((item) => item.id === audience.id); let nextIndex = currentIndex; if (event.key === "ArrowDown" || event.key === "ArrowRight") nextIndex = (currentIndex + 1) % audiences.length; if (event.key === "ArrowUp" || event.key === "ArrowLeft") nextIndex = (currentIndex - 1 + audiences.length) % audiences.length; if (event.key === "Home") nextIndex = 0; if (event.key === "End") nextIndex = audiences.length - 1; if (nextIndex === currentIndex) return; event.preventDefault(); const next = audiences[nextIndex]; setActiveAudienceId(next.id); requestAnimationFrame(() => document.getElementById(`report-audience-tab-${next.id}`)?.focus()); }} className="flex min-h-16 w-full items-center justify-between gap-4 py-4 text-left font-display text-lg font-bold text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-teal-500">{audience.title}<span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full transition ${isActive ? "rotate-45 bg-teal-700 text-white" : "bg-teal-50 text-teal-700"}`}><i className="fas fa-plus text-xs" aria-hidden /></span></button>{isActive ? <p className="pb-6 pr-4 text-sm leading-7 text-slate-600">{audience.body}</p> : null}</div>; })}</div></div></div></section>

      <section className="bg-slate-950 py-20 text-white sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Operational reporting without unsupported accounting promises</h2><p className="mt-5 text-base leading-7 text-slate-300">Receipt Cycle helps a small business review saved activity, categories, cash movement, payments, and invoice exposure. Those are useful management views, but they are not the same as statutory financial statements or an audited accounting system.</p><p className="mt-4 text-base leading-7 text-slate-300">If you need employee claims, approval chains, reimbursements, consolidated entities, formal ledgers, or regulatory filing, choose software designed for that scope. Clear boundaries make this expense report management page more trustworthy.</p></div><div className="grid gap-4 sm:grid-cols-2">{[
        ["Reporting included", "Period summaries, category analysis, cash-flow views, payment totals, invoice status, aging, and source-record access.", "fa-circle-check", "text-teal-300"],
        ["Analysis included", "Record-grounded questions and supported reviews for category, merchant, period, recurring, duplicate, and unusual patterns.", "fa-magnifying-glass-chart", "text-violet-300"],
        ["Claims not included", "No employee claim submission, approval routing, reimbursement processing, policy enforcement, or corporate card controls.", "fa-user-shield", "text-rose-300"],
        ["Accounting not included", "No general ledger, balance sheet, statutory profit-and-loss statement, bank reconciliation, payroll, audit, or tax filing.", "fa-scale-balanced", "text-amber-300"],
      ].map(([title, body, icon, tone]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-6"><i className={`fas ${icon} ${tone}`} aria-hidden /><h3 className="mt-4 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{body}</p></article>)}</div></div></div></section>

      <section className="bg-[#eef8f5] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold text-slate-950 sm:text-4xl">Connect reporting to the records that make it useful</h2><p className="mt-4 text-base leading-7 text-slate-600">Reports sit downstream from capture, expense organization, budgets, and customer payments. Strengthen the source workflow that matters most to the question you are asking.</p></div><div className="mt-10 grid gap-5 md:grid-cols-4">{[
        ["Capture expense evidence", "Extract supported receipt details, review the fields, and save the transaction before it becomes part of category reporting.", "/ai-receipt-scanner/", "AI receipt scanner", "fa-camera"],
        ["Organize travel activity", "Keep airfare, hotels, meals, transportation, and trip receipts easier to filter and review within the expense history.", "/business-travel-expense-tracker/", "Travel expense tracking", "fa-plane"],
        ["Compare spending with limits", "Set monthly category budgets and inspect the transactions behind the amount spent and remaining.", "/business-budgeting-software/", "Business budgeting", "fa-chart-pie"],
        ["Keep payment status current", "Record full or partial customer payments so invoice balances, receipts, and reporting context reflect the saved payment history.", "/payment-tracking-software/", "Payment tracking", "fa-credit-card"],
      ].map(([title, body, href, label, icon], index) => <article key={title} className={`rounded-3xl p-6 shadow-sm ${index === 0 ? "bg-teal-900 text-white" : index === 2 ? "bg-[#fff1c7]" : "bg-white"}`}><span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${index === 0 ? "bg-white/15 text-white" : "bg-teal-100 text-teal-700"}`}><i className={`fas ${icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className={`mt-3 text-sm leading-7 ${index === 0 ? "text-teal-50/80" : "text-slate-600"}`}>{body}</p><Link to={href} className={`mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold ${index === 0 ? "text-teal-100" : "text-teal-700"}`}>{label}<i className="fas fa-arrow-right text-xs" aria-hidden /></Link></article>)}</div></div></section>

      <section className="py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold text-slate-950 sm:text-4xl">Resources for a more reliable reporting routine</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[
        ["Prepare better expense records", "Use a consistent record-review routine before a monthly or professional reporting handoff.", "/blog/freelancers-guide-tracking-business-expenses", "fa-list-check"],
        ["Understand AI finance analysis", "See where AI can help summarize financial records and where human review remains essential.", "/blog/ai-in-finance-personal-business-money-management", "fa-wand-magic-sparkles"],
        ["Compare Receipt Cycle plans", "Review current access to reporting, AI features, editing, and supported CSV export before choosing a plan.", "/pricing", "fa-tags"],
      ].map(([title, body, href, icon]) => <article key={title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><i className={`fas ${icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p><Link to={href} className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold text-teal-700">Open resource<i className="fas fa-arrow-right text-xs" aria-hidden /></Link></article>)}</div></div></section>

      <section className="bg-[#f8f5ee] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 lg:grid-cols-2"><div className="bg-[#fff1c7] p-8 sm:p-10"><h2 className="font-display text-3xl font-bold text-slate-950">Check the source when a report does not match expectation</h2><p className="mt-4 text-base leading-7 text-slate-600">Confirm the selected period, then review the transaction type, date, amount, and category behind the total. For invoice differences, check the invoice total and recorded payments. Correct the source record before relying on the summary.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex min-h-11 items-center rounded-xl bg-teal-700 px-5 text-sm font-bold text-white">Contact us</Link><Link to="/faq" className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-700">Visit the FAQ</Link></div></div><div className="grid gap-px bg-slate-200 sm:grid-cols-3 lg:grid-cols-1">{[
        ["fa-calendar-check", "Confirm the period", "A correctly saved record outside the selected dates will not belong to that report."],
        ["fa-tags", "Inspect the classification", "An expense with the wrong type or category changes the wrong summary."],
        ["fa-envelope", "Ask for product help", "Email support@receiptcycle.com with the report, device, and steps involved."],
      ].map(([icon, title, body]) => <div key={title} className="bg-[#f8faf9] p-6"><i className={`fas ${icon} text-teal-700`} aria-hidden /><h3 className="mt-3 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{body}</p></div>)}</div></div></div></section>

      <section id="faq" className="scroll-mt-28 py-20 sm:py-24"><div className="mx-auto max-w-5xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Frequently Asked Questions</h2><div className="mt-10 divide-y divide-slate-300 border-y border-slate-300">{faqItems.map(([question, answer], index) => <details key={question} className="group py-1" open={index === 0}><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 py-4 text-left text-sm font-extrabold text-slate-900 marker:content-none sm:text-base">{question}<span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-teal-50 text-teal-700 transition group-open:rotate-45"><i className="fas fa-plus text-xs" aria-hidden /></span></summary><p className="max-w-4xl pb-6 pr-12 text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

      <section className="bg-gradient-to-br from-teal-800 via-teal-700 to-emerald-600 py-16 text-white"><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 text-center sm:px-6 lg:grid-cols-[1fr_auto] lg:text-left"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Turn saved activity into a report you can explain</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-50/90">Review the period, inspect the category or balance that changed, and keep the underlying records within reach.</p></div><LandingPrimaryCta to={primaryCta} inverse>Create your reporting workspace</LandingPrimaryCta></div></section>
    </CommercialLandingLayout>
  );
}
