import { useState } from "react";
import { Link } from "react-router-dom";
import { CommercialLandingLayout, LandingPrimaryCta } from "@/components/marketing/CommercialLandingLayout";
import { Seo } from "@/components/Seo";
import { getRouteSeo } from "@/content/routesSeo";

function TaxYearHeroPreview() {
  return (
    <div className="relative mx-auto w-full max-w-[620px] rounded-[2rem] bg-teal-950 p-4 shadow-2xl shadow-teal-950/20 sm:p-6">
      <div className="rounded-[1.4rem] bg-white p-4 sm:p-5">
        <div className="flex items-center justify-between border-b border-slate-200 pb-4">
          <div><p className="text-[9px] font-black uppercase tracking-[0.18em] text-teal-700">Expense records</p><p className="mt-1 font-display text-lg font-bold text-slate-950">Year-to-date review</p></div>
          <span className="rounded-full bg-teal-50 px-3 py-2 text-[10px] font-extrabold text-teal-800">JAN TO SEP</span>
        </div>
        <div className="mt-4 grid gap-3 sm:grid-cols-[0.8fr_1.2fr]">
          <div className="rounded-2xl bg-[#eef8f5] p-4">
            <p className="text-[9px] font-bold uppercase tracking-wider text-slate-500">Expense total</p>
            <p className="mt-2 font-display text-2xl font-black text-slate-950">$8,462.40</p>
            <div className="mt-5 flex h-24 items-end gap-2" aria-hidden>
              {[34, 52, 43, 70, 58, 82, 63, 76, 90].map((height, index) => <span key={index} className="flex-1 rounded-t-md bg-teal-600/80" style={{ height: `${height}%` }} />)}
            </div>
            <p className="mt-3 text-[9px] font-semibold text-slate-500">Nine months of reviewed records</p>
          </div>
          <div className="space-y-2">
            {[
              ["Studio Supply Co.", "Office supplies", "$84.20", "fa-pen-ruler", "bg-violet-100 text-violet-700"],
              ["Cloud Desk", "Software", "$29.00", "fa-laptop", "bg-teal-100 text-teal-700"],
              ["Northside Print", "Marketing", "$146.50", "fa-print", "bg-amber-100 text-amber-700"],
            ].map(([merchant, category, amount, icon, tone]) => <div key={merchant} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${tone}`}><i className={`fas ${icon} text-xs`} aria-hidden /></span><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-extrabold text-slate-900">{merchant}</p><p className="mt-0.5 text-[9px] font-semibold text-slate-500">{category} · Receipt saved</p></div><p className="text-[11px] font-black text-slate-900">{amount}</p></div>)}
            <div className="rounded-xl bg-slate-950 p-3 text-white"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-wider text-teal-300">Review status</p><p className="mt-1 text-[11px] font-extrabold">Records filtered and ready to export</p></div><span className="flex h-9 w-9 items-center justify-center rounded-full bg-teal-500/20 text-teal-300"><i className="fas fa-file-csv" aria-hidden /></span></div></div>
          </div>
        </div>
      </div>
    </div>
  );
}

function ReceiptEvidencePreview() {
  return <div className="grid gap-3 sm:grid-cols-[0.85fr_1.15fr]"><div className="rotate-[-2deg] rounded-2xl bg-white p-4 shadow-md"><p className="text-center text-[10px] font-black">STUDIO SUPPLY CO.</p><div className="my-3 border-t border-dashed border-slate-300" /><div className="space-y-2 text-[9px] text-slate-500"><p className="flex justify-between"><span>Paper stock</span><span>$42.00</span></p><p className="flex justify-between"><span>Ink set</span><span>$36.00</span></p><p className="flex justify-between"><span>Tax</span><span>$6.20</span></p></div><div className="my-3 border-t border-dashed border-slate-300" /><p className="flex justify-between text-[11px] font-black"><span>Total</span><span>$84.20</span></p></div><div className="rounded-2xl bg-teal-950 p-4 text-white"><p className="text-[8px] font-bold uppercase tracking-wider text-teal-300">Editable record</p>{[["Merchant", "Studio Supply Co."], ["Date", "Sep 12"], ["Category", "Office supplies"]].map(([label, value]) => <div key={label} className="mt-3 rounded-lg bg-white/10 px-3 py-2"><p className="text-[7px] font-bold uppercase text-teal-200/70">{label}</p><p className="mt-1 text-[10px] font-extrabold">{value}</p></div>)}</div></div>;
}

function CategoryPreview() {
  return <div className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">Expense categories</p><span className="text-[9px] font-bold text-teal-700">Sep</span></div><div className="mt-4 space-y-3">{[["Software", 74, "$312"], ["Workspace", 56, "$238"], ["Supplies", 42, "$179"], ["Client work", 29, "$124"]].map(([name, width, amount], index) => <div key={name}><div className="mb-1 flex justify-between text-[9px] font-bold"><span>{name}</span><span>{amount}</span></div><div className="h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${index % 2 ? "bg-violet-500" : "bg-teal-600"}`} style={{ width: `${width}%` }} /></div></div>)}</div></div>;
}

function FilterPreview() {
  return <div className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">Find a purchase again</p><div className="mt-3 flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-[10px] text-slate-500"><i className="fas fa-magnifying-glass text-teal-700" aria-hidden />Search merchant, amount, or category</div><div className="mt-3 grid grid-cols-2 gap-2">{["Jan 1 to Sep 30", "Expenses", "Business card", "Newest first"].map((item) => <span key={item} className="rounded-lg bg-[#eef8f5] px-3 py-2 text-[9px] font-bold text-teal-900">{item}</span>)}</div><div className="mt-4 rounded-xl border border-slate-200 p-3"><div className="flex justify-between text-[10px] font-extrabold"><span>Cloud Desk</span><span>$29.00</span></div><p className="mt-1 text-[8px] text-slate-500">Software · Sep 03 · Card</p></div></div>;
}

function CsvHandoffPreview() {
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between bg-slate-950 px-4 py-3 text-white"><p className="text-[9px] font-black uppercase tracking-wider">Transaction export</p><i className="fas fa-file-csv text-teal-300" aria-hidden /></div><div className="grid grid-cols-4 border-b border-slate-200 bg-slate-50 px-3 py-2 text-[7px] font-bold uppercase text-slate-400"><span>Date</span><span>Merchant</span><span>Category</span><span className="text-right">Amount</span></div>{[["09/12", "Studio Supply", "Supplies", "$84.20"], ["09/03", "Cloud Desk", "Software", "$29.00"], ["08/26", "City Print", "Marketing", "$146.50"]].map((row) => <div key={row[1]} className="grid grid-cols-4 border-b border-slate-100 px-3 py-3 text-[8px] text-slate-600 last:border-b-0"><span>{row[0]}</span><span className="truncate font-bold text-slate-800">{row[1]}</span><span className="truncate">{row[2]}</span><span className="text-right font-bold">{row[3]}</span></div>)}</div>;
}

function WorkflowCompanion() {
  return <div className="relative min-h-[560px] overflow-hidden rounded-3xl bg-gradient-to-b from-teal-950 to-teal-800 p-6 text-white sm:p-8"><div className="absolute -right-20 -top-16 h-56 w-56 rounded-full bg-teal-400/20" /><p className="relative text-[10px] font-black uppercase tracking-[0.2em] text-teal-300">A maintained record</p><div className="relative mt-7 space-y-4">{[
    ["Receipt image", "Source evidence kept with the purchase", "fa-receipt"],
    ["Reviewed fields", "Merchant, amount, date, category, and notes", "fa-pen-to-square"],
    ["Year filter", "Return to the period you need", "fa-calendar-days"],
    ["CSV data", "Prepare transaction details for the next review", "fa-table"],
  ].map(([title, body, icon], index) => <div key={title} className="rounded-2xl border border-white/10 bg-white/10 p-5 backdrop-blur"><div className="flex items-center justify-between gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-amber-300 text-[11px] font-black text-slate-950">{index + 1}</span><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/10 text-teal-300"><i className={`fas ${icon}`} aria-hidden /></span></div><p className="mt-4 font-display text-lg font-bold">{title}</p><p className="mt-2 text-xs leading-5 text-teal-50/75">{body}</p></div>)}</div><div className="relative mt-5 rounded-2xl bg-amber-200 p-5 text-slate-950"><p className="text-[9px] font-black uppercase tracking-wider text-amber-800">Your judgment still matters</p><p className="mt-2 text-sm font-bold leading-6">Review every record and ask a qualified professional which expenses belong on your return.</p></div></div>;
}

export default function FreelancerTaxReceiptTrackerLanding() {
  const seo = getRouteSeo("/freelancer-tax-receipt-tracker");
  const primaryCta = "/signup?intent=expense";
  const [activeAudienceId, setActiveAudienceId] = useState("creative");

  const benefits = [
    ["fa-camera", "Preserve the purchase while the details are available", "Photograph a paper receipt or choose an existing image before the ink fades, the email is buried, or the reason for the purchase becomes difficult to remember."],
    ["fa-eye", "Review the record instead of trusting an automatic guess", "Check the merchant, amount, date, category, payment method, tax, and available line items. Correcting the draft now gives you a more dependable record later."],
    ["fa-layer-group", "Keep freelancer expenses in useful groups", "Categories make a long transaction list easier to inspect. Separate software, workspace costs, supplies, marketing, professional services, and other purchases according to how you review the business."],
    ["fa-note-sticky", "Keep the business reason close to the expense", "A merchant name rarely tells the whole story. Notes and descriptions can preserve the client, project, event, equipment purpose, or other context you may need months later."],
    ["fa-magnifying-glass", "Return to the right record without opening every image", "Search and filters narrow the history by date, category, account, type, amount, or merchant, so a question becomes a focused review instead of a folder-by-folder hunt."],
  ];

  const audiences = [
    { id: "creative", title: "Creative freelancers", body: "Designers, photographers, writers, and independent creators often pay for software, equipment, materials, printing, workspace, and client-related purchases. A freelancer receipt tracker keeps the evidence and editable expense record connected without deciding how any item should be treated on a return.", image: "/landing/audiences/tax-creative-freelancer.webp", alt: "Hand-drawn freelance designer capturing a business receipt in a bright home studio" },
    { id: "consultant", title: "Independent consultants", body: "Consultants may combine subscriptions, coworking, professional services, meals, and client expenses across several payment methods. Monthly review helps preserve the business purpose while the engagement is still familiar and makes the annual history easier to explain.", image: "/landing/audiences/tax-independent-consultant.webp", alt: "Hand-drawn independent consultant reviewing categorized business receipts at a coworking table" },
    { id: "contractor", title: "Self-employed contractors", body: "A self-employed expense tracker can keep tool, supply, fuel, phone, and service purchases visible beside their supporting receipts. The user still decides what belongs to the business and should consult a qualified adviser about deductible expenses.", image: "/landing/audiences/tax-service-contractor.webp", alt: "Hand-drawn self-employed service contractor recording a hardware purchase at the workshop" },
    { id: "accountant", title: "Accountant handoffs", body: "When an accountant asks for a period, category, merchant, or transaction explanation, organized records reduce the amount of reconstruction. Filter the history, check the underlying details, and export supported transaction data while keeping tax judgments with the professional reviewing the return.", image: "/landing/audiences/tax-accountant-handoff.webp", alt: "Hand-drawn freelancer and accountant reviewing organized expense records together" },
  ];
  const activeAudience = audiences.find((audience) => audience.id === activeAudienceId) ?? audiences[0];

  const faqItems = [
    ["What does a freelancer tax tracker do?", "Receipt Cycle helps freelancers capture receipts, record business expenses, review transaction details, organize categories, search a date range, and export supported transaction data. It prepares records for review. It does not calculate a return, file taxes, or determine which purchases qualify under tax law."],
    ["Can I scan tax receipts with my phone?", "Yes. The mobile app supports receipt capture with the camera or an image from the gallery. The web workspace supports compatible image uploads. OCR can propose visible purchase details, and you should review every field before saving the expense."],
    ["Does Receipt Cycle decide which expenses are tax deductions?", "No. Receipt Cycle is not a tax deduction tracker that decides eligibility. Categories, notes, receipt evidence, and transaction history can help you present the facts, but you or a qualified tax professional must decide how an expense should be treated."],
    ["Can I use it as a receipt tracker for taxes throughout the year?", "Yes. Capture records as purchases happen, then review them weekly or monthly. A consistent habit gives you a stronger starting point than waiting until a filing deadline to rebuild the year from paper, email, and card statements."],
    ["Can I organize both expenses and income?", "Receipt Cycle supports expense and income transaction types. Reports and workspace totals can provide broader context, but the product does not claim to calculate taxable income, estimated payments, or tax owed."],
    ["Can I give my accountant a CSV export?", "CSV export is available when the plan and administrator settings permit it. The file can include transaction fields such as date, type, category, amount, merchant, description, payment method, and workspace. Confirm the export contents and any additional evidence your accountant needs."],
    ["Does the CSV include every receipt image?", "Do not assume it does. CSV is a structured transaction-data format, not a bundle of image attachments. Receipt evidence may remain with the saved transaction, so review your handoff process before sending records elsewhere."],
    ["Does Receipt Cycle replace tax software or an accountant?", "No. Receipt Cycle is a record-organization workspace. It does not prepare or submit tax forms, provide legal or accounting advice, guarantee compliance, calculate savings, or replace the professional responsible for tax decisions."],
  ];

  const resources = [
    { title: "A freelancer's guide to tracking business expenses", description: "Build a repeatable record-keeping routine around real purchases instead of a once-a-year cleanup.", href: "/blog/freelancers-guide-tracking-business-expenses", icon: "fa-list-check" },
    { title: "Choosing an expense tracker for freelance work", description: "Compare the practical features that matter when receipts, categories, and review all need to stay connected.", href: "/blog/best-expense-tracker-for-freelancers", icon: "fa-scale-balanced" },
    { title: "Why receipt capture and expense tracking belong together", description: "See how a saved source document becomes more useful when it stays attached to an editable transaction.", href: "/blog/expense-tracker-receipt-scanner-one-two-punch", icon: "fa-link" },
  ];
  const costCategories = [
    { title: "Software and online services", body: "Design tools, cloud storage, scheduling, hosting, communication, research, and other recurring services can be grouped so you can review the pattern and supporting records.", icon: "fa-cloud", examples: ["Subscriptions", "Hosting", "Cloud tools"], tone: "bg-teal-950 text-white", iconTone: "bg-teal-300 text-teal-950", chipTone: "bg-white/10 text-teal-50" },
    { title: "Workspace and office costs", body: "Coworking fees, desk supplies, printing, postage, and equipment purchases often come from different merchants. Consistent categories make the history easier to scan.", icon: "fa-house-laptop", examples: ["Coworking", "Printing", "Desk supplies"], tone: "bg-[#e9e3ff] text-slate-950", iconTone: "bg-violet-700 text-white", chipTone: "bg-white/60 text-violet-950" },
    { title: "Tools and materials", body: "Independent trades and makers can record tools, parts, consumables, protective equipment, and job materials with the receipt and a useful description.", icon: "fa-screwdriver-wrench", examples: ["Equipment", "Parts", "Job materials"], tone: "bg-[#fff1c7] text-slate-950", iconTone: "bg-amber-500 text-slate-950", chipTone: "bg-white/60 text-amber-950" },
    { title: "Marketing and client acquisition", body: "Website services, advertising, portfolio printing, event fees, and promotional materials can retain the campaign or client context in a note.", icon: "fa-bullhorn", examples: ["Website", "Advertising", "Events"], tone: "bg-[#dff5ef] text-slate-950", iconTone: "bg-teal-700 text-white", chipTone: "bg-white/70 text-teal-950" },
    { title: "Professional services", body: "Bookkeeping, legal, consulting, and other professional costs benefit from a clear merchant, date, amount, category, payment account, and saved evidence.", icon: "fa-user-tie", examples: ["Bookkeeping", "Legal", "Consulting"], tone: "bg-slate-900 text-white", iconTone: "bg-violet-300 text-violet-950", chipTone: "bg-white/10 text-slate-100" },
    { title: "Business travel and transport", body: "When a purchase belongs to a trip, the dedicated business travel expense tracker provides the fuller workflow for airfare, lodging, meals, and transportation.", icon: "fa-route", examples: ["Airfare", "Lodging", "Transport"], tone: "bg-teal-700 text-white", iconTone: "bg-white text-teal-800", chipTone: "bg-white/10 text-teal-50", href: "/business-travel-expense-tracker" },
  ];

  return <CommercialLandingLayout ctaLabel="Organize a tax receipt" ctaHref={primaryCta} announcement="Keep the proof behind each business purchase">
    {seo ? <Seo {...seo} /> : null}

    <section className="relative overflow-hidden bg-[#f8f5ee] py-16 sm:py-20 lg:py-24"><div className="absolute -left-24 top-4 h-72 w-72 rounded-full bg-amber-100/70 blur-3xl" /><div className="relative mx-auto grid max-w-6xl items-center gap-12 px-6 sm:px-8 lg:grid-cols-[0.84fr_1.16fr] lg:gap-16"><div className="max-w-xl"><h1 className="text-balance font-display text-4xl font-bold leading-[1.04] tracking-[-0.04em] sm:text-5xl lg:text-[3.5rem]"><span className="block text-slate-950">Freelancer tax tracker for</span>{" "}<span className="mt-1 block text-teal-700">receipts and expense records</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-600">Capture business purchases as they happen, preserve the supporting receipt, and prepare an organized record for tax-time review.</p><div className="mt-8"><LandingPrimaryCta to={primaryCta}>Organize your first tax receipt</LandingPrimaryCta><p className="mt-3 text-sm font-medium text-slate-500">No credit card required. Cancel paid plans anytime.</p></div></div><TaxYearHeroPreview /></div></section>

    <section id="features" className="scroll-mt-28 bg-[#dff5ef] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Keep the evidence behind every business purchase</h2><p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">Good records begin long before a filing deadline. Capture, review, classify, and revisit the details while you can still explain them.</p></div><div className="mt-12 grid gap-4 md:grid-cols-6">{benefits.map(([icon, title, body], index) => <article key={title} className={`rounded-2xl p-6 text-white shadow-sm ${index === 0 ? "bg-teal-950" : index === 1 ? "bg-teal-800" : index === 2 ? "bg-violet-700" : index === 3 ? "bg-slate-800" : "bg-teal-700"} ${index < 3 ? "md:col-span-2" : "md:col-span-3"}`}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/15 text-teal-50"><i className={`fas ${icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-teal-50/85">{body}</p></article>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">The record-keeping tools freelancers need before tax preparation</h2><p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">A useful freelancer expense tracker keeps the source document, editable facts, business context, and retrieval tools within the same practical workflow.</p></div><div className="mt-12 grid auto-rows-auto gap-5 lg:grid-cols-12">
      <article className="rounded-3xl bg-[#eef8f5] p-6 sm:p-8 lg:col-span-7"><ReceiptEvidencePreview /><h3 className="mt-7 font-display text-2xl font-bold">Keep the receipt beside the numbers it supports</h3><p className="mt-3 text-sm leading-7 text-slate-600">Receipt OCR can propose the visible merchant, total, date, payment method, category, currency, subtotal, tax, and line items. You remain responsible for checking the image and correcting the record before saving it.</p></article>
      <article className="rounded-3xl bg-[#f1ecff] p-6 sm:p-8 lg:col-span-5"><CategoryPreview /><h3 className="mt-7 font-display text-2xl font-bold">Use categories that make sense when you return</h3><p className="mt-3 text-sm leading-7 text-slate-600">Organize software, workspace, materials, marketing, professional services, and other costs according to the way you review the business. Categories improve retrieval, but they do not decide tax treatment.</p></article>
      <article className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8 lg:col-span-5"><div className="grid grid-cols-2 gap-3">{[["Business card", "Card"], ["Studio cash", "Cash"], ["Checking", "Bank"], ["Reserve", "Savings"]].map(([name, type], index) => <div key={name} className="rounded-2xl bg-white/10 p-4"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${index % 2 ? "bg-violet-400/20 text-violet-200" : "bg-teal-400/20 text-teal-200"}`}><i className={`fas ${index === 0 ? "fa-credit-card" : index === 1 ? "fa-money-bill" : index === 2 ? "fa-building-columns" : "fa-piggy-bank"}`} aria-hidden /></span><p className="mt-3 text-xs font-extrabold">{name}</p><p className="mt-1 text-[9px] uppercase tracking-wider text-slate-400">{type}</p></div>)}</div><h3 className="mt-7 font-display text-2xl font-bold">Preserve how the purchase was paid</h3><p className="mt-3 text-sm leading-7 text-slate-300">Linking an account and payment method helps distinguish card, bank, savings, and cash activity. It gives the transaction context without claiming automatic bank-feed reconciliation.</p></article>
      <article className="rounded-3xl bg-[#fff1c7] p-6 sm:p-8 lg:col-span-7"><FilterPreview /><h3 className="mt-7 font-display text-2xl font-bold">Answer a question with filters, not a memory test</h3><p className="mt-3 text-sm leading-7 text-slate-700">Use a date range for the period under review, then narrow by category or account. Search can help locate a merchant, description, category, or amount when the question begins with one specific purchase.</p></article>
      <article className="rounded-3xl bg-[#e9e3ff] p-6 sm:p-8 lg:col-span-7"><CsvHandoffPreview /><h3 className="mt-7 font-display text-2xl font-bold">Export transaction data when another tool needs it</h3><p className="mt-3 text-sm leading-7 text-slate-700">CSV export can move supported transaction fields into a spreadsheet or professional review process when your plan and workspace allow it. Confirm what your accountant expects, because a CSV is not a tax return or a bundle of receipt images.</p></article>
      <article className="rounded-3xl bg-teal-800 p-6 text-white sm:p-8 lg:col-span-5"><div className="rounded-2xl bg-white/10 p-5"><p className="text-[9px] font-bold uppercase tracking-wider text-teal-200">Transaction note</p><p className="mt-3 font-display text-lg font-bold">Large-format proofs for client presentation</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-2 text-[9px] font-bold">Marketing</span><span className="rounded-full bg-white/10 px-3 py-2 text-[9px] font-bold">Business card</span><span className="rounded-full bg-white/10 px-3 py-2 text-[9px] font-bold">Receipt attached</span></div></div><h3 className="mt-7 font-display text-2xl font-bold">Write down why the expense belongs to the work</h3><p className="mt-3 text-sm leading-7 text-teal-50/85">A short note can preserve the client, project, event, or purpose that a merchant name cannot. Receipt Cycle stores the context you enter. It does not judge whether that context satisfies a tax rule.</p></article>
    </div></div></section>

    <section className="bg-teal-950 py-14 text-white"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-7 px-4 text-center sm:px-6 lg:flex-row lg:text-left"><div><h2 className="font-display text-3xl font-bold">Make record keeping a habit before the deadline</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-50/80">Save the receipt, check the record, and keep the year understandable one purchase at a time.</p></div><LandingPrimaryCta to={primaryCta} inverse>Organize your first tax receipt</LandingPrimaryCta></div></section>

    <section id="workflow" className="scroll-mt-28 bg-[#f8faf9] py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid items-stretch gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">Build the year while the work is still familiar</h2><div className="mt-8 space-y-7">{[
      ["Capture the source", "Photograph the paper receipt, choose a saved image, upload a supported file on the web, or add the expense manually when no usable image exists."],
      ["Check the purchase details", "Compare the image with the proposed merchant, total, date, category, payment method, tax, and available line items. Correct omissions before saving."],
      ["Add the business context", "Choose the category and account, then record a description or note that explains the purchase in language you will understand later."],
      ["Review on a regular schedule", "Filter the current month or quarter, look for missing evidence and vague descriptions, and correct the record while the purchase remains easy to verify."],
      ["Prepare the handoff", "Select the relevant period, inspect the totals and records, then export supported transaction data if your plan and workspace permit it. Keep receipt-sharing requirements separate from the CSV."],
    ].map(([title, body], index) => <div key={title} className="grid grid-cols-[auto_1fr] gap-4"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-teal-700 text-sm font-black text-white">{index + 1}</span><div><h3 className="font-display text-xl font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{body}</p></div></div>)}</div></div><WorkflowCompanion /></div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">Organize common freelance costs without labeling them deductions</h2><p className="mt-4 text-base leading-7 text-slate-600">A business expense tracker for taxes should help you describe what happened. Tax eligibility is a separate decision based on your facts, location, and professional guidance.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{costCategories.map((category, index) => <article key={category.title} className={`group relative overflow-hidden rounded-3xl p-6 shadow-sm ring-1 ring-black/5 transition duration-300 hover:-translate-y-1 hover:shadow-xl ${category.tone}`}><div className="absolute -right-10 -top-10 h-32 w-32 rounded-full bg-white/10 transition duration-300 group-hover:scale-110" aria-hidden /><div className="relative flex items-start justify-between gap-4"><span className={`flex h-12 w-12 items-center justify-center rounded-2xl shadow-sm ${category.iconTone}`}><i className={`fas ${category.icon}`} aria-hidden /></span><span className="font-display text-4xl font-black leading-none opacity-10">0{index + 1}</span></div><h3 className="relative mt-6 font-display text-xl font-bold">{category.title}</h3><div className="relative mt-4 flex flex-wrap gap-2">{category.examples.map((example) => <span key={example} className={`rounded-full px-3 py-1.5 text-[9px] font-extrabold uppercase tracking-wide ${category.chipTone}`}>{example}</span>)}</div><p className={`relative mt-5 text-sm leading-7 ${category.tone.includes("text-white") ? "text-white/80" : "text-slate-700"}`}>{category.body}</p>{category.href ? <Link to={category.href} className="relative mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold text-white">Open the travel workflow<i className="fas fa-arrow-right text-xs" aria-hidden /></Link> : null}</article>)}</div></div></section>

    <section className="bg-[#eef8f5] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid overflow-hidden rounded-3xl border border-slate-200 bg-white lg:grid-cols-2"><figure className="relative min-h-[360px] overflow-hidden bg-slate-950 sm:min-h-[480px] lg:min-h-full"><img src="/landing/freelancer-deadline-reconstruction.webp" alt="A freelancer sorting faded receipts, cash purchases, card records, and an unfinished spreadsheet near a deadline" className="absolute inset-0 h-full w-full object-cover" loading="lazy" decoding="async" /></figure><div className="p-7 sm:p-10"><h2 className="font-display text-3xl font-bold text-slate-950">Each purchase keeps enough context to be reviewed</h2><div className="mt-7 space-y-4">{["Receipt evidence stays connected to the saved transaction when available.", "Editable merchant, amount, date, category, account, method, and notes explain the record.", "Date, category, account, and search tools narrow the period under review.", "Income and expense views provide business context without calculating tax owed.", "CSV export moves supported transaction fields into the next stage of review."].map((item) => <p key={item} className="flex gap-3 text-sm leading-6 text-slate-600"><i className="fas fa-check mt-1 text-teal-700" aria-hidden />{item}</p>)}</div></div></div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid items-center gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><h2 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">Know what a tax receipt tracker prepares, and what it cannot decide</h2><p className="mt-5 text-base leading-7 text-slate-600">Receipt Cycle can help you preserve transaction facts, organize tax receipts, revisit a period, and prepare data for review. A self-employed expense tracker can improve the record, but it cannot make the tax decision.</p><p className="mt-4 text-base leading-7 text-slate-600">The platform does not decide whether a purchase is ordinary, necessary, personal, capital, reimbursable, or deductible. It does not map categories to tax forms, estimate tax owed, guarantee tax-ready records, or submit a return.</p><p className="mt-4 text-base leading-7 text-slate-600">Use the product to improve the record. Use current guidance and a qualified professional to decide what the record means for you.</p></div><div className="grid gap-4 sm:grid-cols-2">{[
      ["Receipt Cycle prepares", "Images and structured receipt details", "fa-receipt", "bg-teal-50 text-teal-800"],
      ["Receipt Cycle prepares", "Editable transaction fields and notes", "fa-pen-to-square", "bg-violet-50 text-violet-800"],
      ["You decide", "Whether a purchase belongs to the business", "fa-user-check", "bg-amber-50 text-amber-800"],
      ["A professional decides", "How current tax rules apply to your facts", "fa-scale-balanced", "bg-slate-100 text-slate-800"],
    ].map(([label, body, icon, tone]) => <article key={body} className={`rounded-3xl p-6 ${tone}`}><i className={`fas ${icon} text-xl`} aria-hidden /><p className="mt-5 text-[10px] font-black uppercase tracking-wider opacity-70">{label}</p><h3 className="mt-2 font-display text-xl font-bold leading-7">{body}</h3></article>)}</div></div></div></section>

    <section className="bg-[#f8f5ee] py-20 sm:py-28"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Freelancer records for the way independent work is paid for</h2><p className="mt-4 text-base leading-7 text-slate-600">Choose a working style to see how the same record-keeping foundation adapts without pretending every freelancer has the same purchases.</p></div><div className="mt-12 grid items-stretch gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div id="tax-audience-panel" role="tabpanel" aria-labelledby={`tax-audience-tab-${activeAudience.id}`} className="min-w-0 overflow-hidden rounded-3xl border border-teal-100 bg-white shadow-sm"><img key={activeAudience.image} src={activeAudience.image} alt={activeAudience.alt} width="1586" height="992" loading="lazy" decoding="async" sizes="(min-width: 1024px) 720px, (min-width: 640px) 90vw, 100vw" className="block h-auto w-full" /></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white px-5 sm:px-6" role="tablist" aria-label="Freelancer tax record audiences">{audiences.map((audience) => { const isActive = audience.id === activeAudience.id; return <div key={audience.id} className="border-b border-slate-200 last:border-b-0"><button id={`tax-audience-tab-${audience.id}`} type="button" role="tab" aria-selected={isActive} aria-controls="tax-audience-panel" tabIndex={isActive ? 0 : -1} onClick={() => setActiveAudienceId(audience.id)} onKeyDown={(event) => { const currentIndex = audiences.findIndex((item) => item.id === audience.id); let nextIndex = currentIndex; if (event.key === "ArrowDown" || event.key === "ArrowRight") nextIndex = (currentIndex + 1) % audiences.length; if (event.key === "ArrowUp" || event.key === "ArrowLeft") nextIndex = (currentIndex - 1 + audiences.length) % audiences.length; if (event.key === "Home") nextIndex = 0; if (event.key === "End") nextIndex = audiences.length - 1; if (nextIndex === currentIndex) return; event.preventDefault(); const next = audiences[nextIndex]; setActiveAudienceId(next.id); requestAnimationFrame(() => document.getElementById(`tax-audience-tab-${next.id}`)?.focus()); }} className="flex min-h-16 w-full items-center justify-between gap-4 py-4 text-left font-display text-lg font-bold text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-teal-500">{audience.title}<span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full transition ${isActive ? "rotate-45 bg-teal-700 text-white" : "bg-teal-50 text-teal-700"}`}><i className="fas fa-plus text-xs" aria-hidden /></span></button>{isActive ? <p className="pb-6 pr-4 text-sm leading-7 text-slate-600">{audience.body}</p> : null}</div>; })}</div></div></div></section>

    <section className="bg-teal-950 py-20 text-white sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid items-center gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Give the expense history its wider business context</h2><p className="mt-5 text-base leading-7 text-teal-50/80">Freelancers often need to review income and expenses across the same period. Receipt Cycle supports both transaction types, account activity, category views, totals, and reports so the expense history does not sit in isolation.</p><p className="mt-4 text-base leading-7 text-teal-50/80">This context can help you inspect the business, but it does not calculate taxable profit, quarterly payments, deductions, or a refund. Export supported CSV data when available and confirm the rest of the handoff with your accountant.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/pricing" className="inline-flex min-h-11 items-center rounded-xl bg-white px-5 text-sm font-bold text-teal-900">Compare plans</Link><Link to="/ai-receipt-scanner" className="inline-flex min-h-11 items-center rounded-xl border border-white/20 px-5 text-sm font-bold text-white">Explore receipt scanning</Link></div></div><CsvHandoffPreview /></div></div></section>

    <section className="bg-[#eef8f5] py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold text-slate-950 sm:text-4xl">Practical guides for better freelancer records</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{resources.map((resource) => <article key={resource.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><i className={`fas ${resource.icon}`} aria-hidden /></span><h3 className="mt-5 font-display text-xl font-bold">{resource.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{resource.description}</p><Link to={resource.href} className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold text-teal-700 hover:text-teal-900">Open resource<i className="fas fa-arrow-right text-xs" aria-hidden /></Link></article>)}</div></div></section>

    <section className="py-20 sm:py-24"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="grid overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 lg:grid-cols-2"><div className="bg-[#fff1c7] p-8 sm:p-10"><h2 className="font-display text-3xl font-bold text-slate-950">Fix the record while the source is still available</h2><p className="mt-4 text-base leading-7 text-slate-600">If a receipt will not scan, improve the lighting, flatten the paper, or enter the transaction manually. If a category, account, or date looks wrong, edit the record before relying on it for a later review.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/contact" className="inline-flex min-h-11 items-center rounded-xl bg-teal-700 px-5 text-sm font-bold text-white">Contact us</Link><Link to="/faq" className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-5 text-sm font-bold text-slate-700">Visit the FAQ</Link></div></div><div className="grid gap-px bg-slate-200 sm:grid-cols-3 lg:grid-cols-1">{[["fa-camera-rotate", "Retake the image", "Use even light, include the full receipt, and check that important lines are readable."], ["fa-pen", "Correct the fields", "Compare the source with the merchant, total, date, category, account, and notes before saving."], ["fa-envelope", "Ask for product help", "Email support@receiptcycle.com with the device, page, and step where the issue occurred."]].map(([icon, title, body]) => <div key={title} className="bg-[#f8faf9] p-6"><i className={`fas ${icon} text-teal-700`} aria-hidden /><h3 className="mt-3 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{body}</p></div>)}</div></div></div></section>

    <section id="faq" className="scroll-mt-28 bg-[#f8f5ee] py-20 sm:py-24"><div className="mx-auto max-w-5xl px-4 sm:px-6"><h2 className="text-center font-display text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Frequently Asked Questions</h2><div className="mt-10 divide-y divide-slate-300 border-y border-slate-300">{faqItems.map(([question, answer], index) => <details key={question} className="group py-1" open={index === 0}><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 py-4 text-left text-sm font-extrabold text-slate-900 marker:content-none sm:text-base">{question}<span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-teal-50 text-teal-700 transition group-open:rotate-45"><i className="fas fa-plus text-xs" aria-hidden /></span></summary><p className="max-w-4xl pb-6 pr-12 text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>

    <section className="bg-gradient-to-br from-teal-800 via-teal-700 to-emerald-600 py-16 text-white"><div className="mx-auto grid max-w-6xl items-center gap-8 px-4 text-center sm:px-6 lg:grid-cols-[1fr_auto] lg:text-left"><div><h2 className="font-display text-3xl font-bold sm:text-4xl">Let tax preparation begin with records you recognize</h2><p className="mt-3 max-w-2xl text-base leading-7 text-teal-50/90">Capture receipts, check freelancer expenses, and keep the facts available for your next review.</p></div><LandingPrimaryCta to={primaryCta} inverse>Organize your first tax receipt</LandingPrimaryCta></div></section>
  </CommercialLandingLayout>;
}
