import { useState } from "react";
import { Link } from "react-router-dom";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { CommercialFooter, CommercialHeader, LandingPrimaryCta } from "@/components/marketing/CommercialLandingLayout";
import { Seo } from "@/components/Seo";
import { getRouteSeo } from "@/content/routesSeo";

const asset = (name: string) => `${import.meta.env.BASE_URL.replace(/\/?$/, "/")}landing/${name}`;
const PLAY_STORE_URL = (import.meta.env.VITE_PLAY_STORE_URL as string | undefined)?.trim() || "https://play.google.com/store/apps/details?id=com.anonymous.receiptcyclemobile";

const audiences = [
  { name: "Freelancers", title: "Keep the admin from taking over the work", copy: "Capture the cost of a job, prepare the customer documents, and keep the record ready for the day you need it again.", href: "/freelancer-tax-receipt-tracker/" },
  { name: "Consultants", title: "Take a project from proposal to payment", copy: "Price the work, keep the client details close, issue the invoice, and record what has been paid without starting over at each step.", href: "/estimate-quotation-software/" },
  { name: "Small businesses", title: "See where the business stands today", copy: "Bring purchases, customer billing, budgets, and reports together so the next decision starts with a complete record.", href: "/business-budgeting-software/" },
  { name: "Operations teams", title: "Make every review easier to explain", copy: "Organize evidence as the work happens, then move from a report total back to the receipt, payment, or customer activity behind it.", href: "/expense-reporting-software/" },
];

const faqs = [
  ["What can I do with Receipt Cycle?", "You can capture receipts, organize expenses, maintain customer details, prepare estimates and invoices, record payments, set budgets, review reports, and ask questions based on saved business records."],
  ["Is Receipt Cycle a complete accounting system?", "Receipt Cycle is a practical workspace for spending, customer billing, and business records. It does not replace a complete accounting system, a qualified accountant, or professional tax advice."],
  ["Can I use the same account on mobile and web?", "Yes. Capture information from your phone and return to the web workspace when a larger screen is better for reviewing documents, budgets, or reports."],
  ["What does the AI do?", "AI can help extract receipt details and answer questions using the activity you have saved. You remain in control of corrections, classifications, and business decisions."],
  ["Do I need a credit card to get started?", "No. You can create an account without entering a credit card. If you decide to upgrade later, current plan details are available on the pricing page."],
] as const;

function PhoneMockup() {
  return <div className="relative mx-auto w-[220px] rounded-[34px] border-[7px] border-slate-950 bg-slate-950 p-1 shadow-2xl sm:w-[250px]">
    <div className="absolute left-1/2 top-2 z-10 h-5 w-20 -translate-x-1/2 rounded-full bg-slate-950" />
    <div aria-label="Receipt Cycle mobile dashboard" className="aspect-[9/18] overflow-hidden rounded-[24px] bg-gradient-to-b from-white to-teal-50 p-3 pt-8 text-slate-900">
      <div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-teal-700 text-[10px] text-white"><i className="fas fa-arrows-rotate" /></span><div><p className="text-[9px] font-black leading-none">Receipt Cycle</p><p className="mt-1 text-[7px] text-slate-400">Dashboard</p></div></div><i className="far fa-bell text-[10px] text-slate-500" /></div>
      <p className="mt-5 text-[11px] font-black">Good morning, there</p><p className="mt-1 text-[7px] text-slate-400">Here is your snapshot for today</p>
      <div className="mt-3 bg-gradient-to-br from-teal-700 to-teal-500 p-3 text-white shadow"><p className="text-[7px] font-bold text-teal-100">NET THIS MONTH</p><p className="mt-1 text-xl font-black">$5,235</p><p className="mt-2 text-[7px]">28.4% savings rate</p></div>
      <p className="mt-4 text-[9px] font-black">Quick actions</p><div className="mt-2 grid grid-cols-4 gap-1">{[["fa-camera","Scan"],["fa-plus","Add"],["fa-microphone","Voice"],["fa-file-arrow-up","Import"]].map(([i,t])=><div key={t} className="bg-white p-1.5 text-center shadow-sm"><i className={`fas ${i} text-[9px] text-teal-700`} /><p className="mt-1 text-[6px] font-bold">{t}</p></div>)}</div>
      <div className="mt-4 flex justify-between"><p className="text-[9px] font-black">Recent transactions</p><p className="text-[7px] font-bold text-teal-700">View all</p></div>{[["Office Depot","Supplies","-$86.40"],["Client payment","Income","+$1,400"],["Fuel station","Transport","-$54.20"]].map(([m,c,a])=><div key={m} className="mt-2 flex items-center bg-white p-2 shadow-sm"><span className="mr-2 flex h-6 w-6 items-center justify-center rounded-full bg-teal-50 text-[8px] text-teal-700"><i className="fas fa-receipt" /></span><div><p className="text-[7px] font-black">{m}</p><p className="text-[6px] text-slate-400">{c}</p></div><p className={`ml-auto text-[7px] font-black ${a.startsWith("+")?"text-emerald-600":"text-rose-600"}`}>{a}</p></div>)}
    </div>
  </div>;
}

function MiniDocument({ type }: { type: "invoice" | "receipt" | "report" }) {
  if (type === "receipt") return <div className="rounded-2xl bg-white p-5 shadow-lg"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-100 text-orange-600"><i className="fas fa-receipt" /></span><div><p className="text-xs font-bold text-slate-400">PURCHASE</p><p className="font-black">Office supplies</p></div><p className="ml-auto font-black">$86.40</p></div><div className="mt-4 flex gap-2"><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-700">Receipt attached</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">Categorized</span></div></div>;
  if (type === "report") return <div className="rounded-2xl bg-white p-5 shadow-lg"><div className="flex items-end justify-between gap-2"><div><p className="text-xs font-bold text-slate-400">THIS MONTH</p><p className="mt-1 text-2xl font-black">Business activity</p></div><span className="rounded-lg bg-teal-50 px-3 py-2 text-xs font-black text-teal-700">View report</span></div><div className="mt-5 flex h-24 items-end gap-2">{[42,68,50,88,62,96,74].map((h,i)=><span key={i} className="flex-1 rounded-t-md bg-teal-600" style={{height:`${h}%`,opacity:.35+i*.08}} />)}</div></div>;
  return <div className="rounded-2xl bg-white p-5 shadow-lg"><div className="flex justify-between"><div><p className="text-xs font-black text-teal-700">INVOICE</p><p className="mt-1 font-black">Web design project</p></div><span className="h-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-700">Sent</span></div><div className="mt-5 space-y-2 border-y py-4 text-sm"><div className="flex justify-between text-slate-500"><span>Project services</span><span>$1,400</span></div><div className="flex justify-between font-black"><span>Balance</span><span>$1,400</span></div></div></div>;
}

export default function MarketingLanding() {
  const seo = getRouteSeo("/");
  const [audience, setAudience] = useState(0);
  return <div className="min-h-screen overflow-x-hidden bg-white text-[#08244a]">
    {seo && <Seo title={seo.title} description={seo.description} path="/" structuredData={seo.structuredData} />}
    <CommercialHeader ctaLabel="Start free" ctaHref="/signup?intent=home" />
    <main>
      <section className="relative overflow-hidden bg-[#eef8f7]">
        <div className="mx-auto grid min-h-[650px] max-w-6xl items-center gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:py-20">
          <div className="relative z-20 max-w-xl">
            <h1 className="font-display text-5xl font-black leading-[1.04] tracking-[-.045em] sm:text-6xl">The simpler way to run your business finances</h1>
            <p className="mt-6 text-lg leading-8 text-slate-600">Keep receipts, expenses, customer work, payments, budgets, and reports in one place. Receipt Cycle helps you stay on top of the details without letting the paperwork take over your day.</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><LandingPrimaryCta to="/signup?intent=home" className="px-8">Start for free</LandingPrimaryCta><a href={PLAY_STORE_URL} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-3 border-2 border-[#08244a] bg-white px-6 py-3 text-sm font-black text-[#08244a] transition hover:bg-slate-50"><i className="fab fa-google-play text-lg" />Download the mobile app</a></div>
            <p className="mt-3 text-sm font-semibold text-slate-500">No credit card required for the web app. One account works across mobile and web.</p>
          </div>
          <div className="relative min-h-[500px]">
            <img src={asset("home/home-hero-founder.webp")} alt="A small business owner using Receipt Cycle on her phone" className="absolute inset-0 h-full w-full rounded-[38px] object-cover shadow-xl" />
            <div className="absolute -bottom-8 left-3 z-10 sm:left-8"><PhoneMockup /></div>
            <div className="absolute right-3 top-7 w-52 rounded-2xl border border-white/80 bg-white/95 p-4 shadow-xl backdrop-blur sm:right-7 sm:w-60"><p className="text-xs font-black uppercase tracking-wider text-teal-700">Ready to review</p><p className="mt-2 text-lg font-black">Your latest receipt is saved</p><div className="mt-3 flex items-center gap-2 text-sm text-slate-500"><i className="fas fa-circle-check text-teal-600" /><span>Details extracted</span></div></div>
          </div>
        </div>
      </section>

      <section className="py-20 lg:py-28">
        <div className="mx-auto max-w-6xl px-5 sm:px-8">
          <div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-4xl font-black tracking-tight sm:text-5xl">Everything you need for the paperwork behind the work</h2><p className="mt-5 text-lg leading-8 text-slate-600">Create the documents customers expect, capture the receipts your business collects, and keep spending ready for budgets, reports, and tax-time review.</p></div>
          <div className="mx-auto mt-14 grid max-w-5xl gap-4 lg:grid-cols-2">
            <article className="grid overflow-hidden bg-[#f7f3ec] sm:grid-cols-[.85fr_1.15fr]"><div className="p-7"><h3 className="text-2xl font-black">Invoicing</h3><p className="mt-3 leading-7 text-slate-600">Create a polished invoice, add taxes or discounts, send it to the customer, and keep its payment status visible.</p><Link to="/invoice-software/" className="mt-5 inline-block font-black text-teal-700">Explore invoicing</Link></div><div className="self-end p-5 pl-0"><MiniDocument type="invoice" /></div></article>
            <article className="overflow-hidden bg-[#087fdb] p-7 text-white"><h3 className="text-2xl font-black">Estimates and quotations</h3><p className="mt-3 leading-7 text-blue-50">Describe the job, price each line, set a validity period, and move accepted work toward an invoice.</p><Link to="/estimate-quotation-software/" className="mt-5 inline-block font-black text-white">Explore estimates</Link><div className="mt-6 border border-white/25 bg-white/10 p-4"><div className="flex justify-between text-sm"><span>Kitchen repair estimate</span><strong>Awaiting reply</strong></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span className="bg-white/10 p-2">Materials $320</span><span className="bg-white/10 p-2">Labour $480</span></div></div></article>
            <article className="overflow-hidden bg-[#eaf5ff]"><div className="p-7"><h3 className="text-2xl font-black">AI receipt scanning</h3><p className="mt-3 leading-7 text-slate-600">Photograph or upload a receipt, extract the merchant, date, amount, tax, and line items, then review before saving.</p><Link to="/ai-receipt-scanner/" className="mt-5 inline-block font-black text-teal-700">Explore AI scanning</Link></div><div className="px-7 pb-7"><MiniDocument type="receipt" /></div></article>
            <article className="grid overflow-hidden bg-[#092f6d] text-white sm:grid-cols-[.9fr_1.1fr]"><div className="p-7"><h3 className="text-2xl font-black">Expense tracking</h3><p className="mt-3 leading-7 text-blue-100">Keep purchases categorized, search the history, attach evidence, and understand where the business is spending.</p><Link to="/business-travel-expense-tracker/" className="mt-5 inline-block font-black text-white">Explore expense tracking</Link></div><div className="self-end p-5 pl-0 text-slate-900"><MiniDocument type="report" /></div></article>
            <article className="bg-[#fff4d8] p-7"><h3 className="text-2xl font-black">Business budgeting</h3><p className="mt-3 leading-7 text-slate-700">Set monthly limits by category, compare budget with actual spending, and see the amount remaining before another purchase.</p><Link to="/business-budgeting-software/" className="mt-5 inline-block font-black text-teal-700">Explore budgeting</Link><div className="mt-6 border-t border-amber-300 pt-4"><div className="flex justify-between text-sm font-black"><span>Tools and supplies</span><span>68% used</span></div><div className="mt-3 h-3 bg-white"><div className="h-3 w-2/3 bg-amber-500" /></div></div></article>
            <article className="bg-[#ffd43b] p-7"><h3 className="text-2xl font-black">Reports and AI analysis</h3><p className="mt-3 leading-7 text-slate-700">Review income and expenses by period, then ask focused questions grounded in the records saved to your workspace.</p><div className="mt-5 flex flex-wrap gap-5 font-black"><Link to="/expense-reporting-software/">Explore reports</Link><Link to="/ai-financial-assistant/">Explore Ask AI</Link></div><div className="mt-6 grid grid-cols-3 gap-2 text-center text-xs font-black">{["Income","Expenses","Cash flow"].map(x=><span key={x} className="bg-white/60 p-3">{x}</span>)}</div></article>
          </div>
        </div>
      </section>

      <section className="relative overflow-hidden bg-[#f9f5e9] pt-16">
        <div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="grid items-end gap-8 lg:grid-cols-[.7fr_1.3fr]"><div className="pb-10"><h2 className="font-display text-4xl font-black sm:text-5xl">Made for people who have real work to finish</h2><p className="mt-4 text-lg leading-8 text-slate-600">Whether you send estimates from a job site, invoice clients from a studio, or sort a month of receipts before tax time, Receipt Cycle keeps the paperwork attached to the work it belongs to.</p></div><img src={asset("home/home-small-team.webp")} alt="A small team reviewing business work together" className="h-[390px] w-full object-cover" loading="lazy" /></div>
          <div className="relative z-10 -mt-10 grid bg-[#082f6b] sm:grid-cols-2 lg:grid-cols-4">{audiences.map((item,index)=><button key={item.name} onClick={()=>setAudience(index)} className={`border-b border-r border-white/10 p-6 text-left text-white transition ${audience===index?"bg-[#0b4193]":"hover:bg-white/5"}`}><span className="text-lg font-black">{item.name}</span><span className="mt-3 block text-sm leading-6 text-blue-100">{item.copy}</span></button>)}</div>
          <div className="mx-auto max-w-3xl py-12 text-center"><h3 className="text-3xl font-black">{audiences[audience].title}</h3><Link to={audiences[audience].href} className="mt-5 inline-flex items-center gap-2 font-black text-teal-700">See how Receipt Cycle fits <i className="fas fa-arrow-right text-xs" /></Link></div>
        </div>
      </section>

      <section className="py-20 lg:py-28"><div className="mx-auto max-w-5xl px-5 sm:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><article className="bg-[#fff4d8] p-7 lg:row-span-2"><h2 className="font-display text-4xl font-black">Spend less time rebuilding your paperwork</h2><p className="mt-5 leading-7 text-slate-600">A receipt saved today can support an expense report later. An accepted estimate can supply the details for an invoice. A recorded payment can update the balance you discuss with a customer. Receipt Cycle keeps that trail intact.</p><LandingPrimaryCta to="/signup?intent=home-middle" className="mt-7">Start for free</LandingPrimaryCta></article>{[["fa-mobile-screen","Capture it before it gets lost","Save receipts and quick details from your phone while the purchase is still fresh."],["fa-display","Handle detailed work on the web","Use a larger screen for estimates, invoices, budgets, reports, and careful review."],["fa-link","Keep the evidence with the number","Connect the receipt, customer, payment reference, or note to the record it explains."],["fa-shield-halved","Review before you rely on it","Check extracted details and AI-assisted answers before using them in a business decision."]].map(([i,t,b],x)=><article key={t} className={`p-7 ${x%2?"bg-[#087fdb] text-white":"bg-[#092f6d] text-white"}`}><i className={`fas ${i} text-2xl text-teal-200`} /><h3 className="mt-8 text-xl font-black">{t}</h3><p className="mt-3 text-sm leading-6 text-blue-100">{b}</p></article>)}</div></div></section>

      <section className="bg-[#edf7ff] py-20"><div className="mx-auto grid max-w-5xl overflow-hidden bg-white shadow-sm lg:grid-cols-2"><img src={asset("home/home-support-specialist.webp")} alt="Receipt Cycle customer support specialist" className="h-full min-h-[420px] w-full object-cover" loading="lazy" /><div className="flex flex-col justify-center p-8 sm:p-12"><h2 className="font-display text-4xl font-black">Support from people who want you to succeed</h2><p className="mt-5 text-lg leading-8 text-slate-600">When you have a question about the product or your account, you should not have to search through a maze of generic answers. Start with the help center or contact our team directly.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/contact" className="bg-teal-700 px-5 py-3 text-sm font-black text-white">Contact us</Link><Link to="/faq" className="border-2 border-slate-200 px-5 py-3 text-sm font-black">Visit the help center</Link></div></div></div></section>

      <section className="py-20"><div className="mx-auto max-w-4xl px-4 sm:px-6"><h2 className="text-center font-display text-4xl font-black">Frequently asked questions</h2><Accordion type="single" collapsible className="mt-10 space-y-3">{faqs.map(([q,a],i)=><AccordionItem value={`home-${i}`} key={q} className="rounded-xl border-0 bg-[#edf7ff] px-5"><AccordionTrigger className="text-left font-black hover:no-underline">{q}</AccordionTrigger><AccordionContent className="leading-7 text-slate-600">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>

      <section className="relative overflow-hidden bg-[#063c91] py-16 text-white"><div className="absolute -bottom-40 -left-20 h-96 w-96 rounded-full border-[70px] border-blue-400/15" /><div className="relative mx-auto grid max-w-6xl items-center gap-10 px-5 sm:px-8 lg:grid-cols-2"><div><h2 className="font-display text-4xl font-black sm:text-5xl">Ready to spend less time on the paperwork?</h2><p className="mt-4 max-w-xl text-lg leading-8 text-blue-100">Create your workspace, add the next receipt, estimate, or invoice, and keep the details ready for payment follow-up, budgeting, reporting, and tax-time preparation.</p><LandingPrimaryCta to="/signup?intent=home-final" inverse className="mt-7">Start for free</LandingPrimaryCta></div><div className="relative hidden h-64 lg:block"><div className="absolute right-12 top-0 w-72 rotate-3"><MiniDocument type="invoice" /></div><div className="absolute bottom-0 left-6 w-64 -rotate-3"><MiniDocument type="report" /></div></div></div></section>
    </main>
    <CommercialFooter />
  </div>;
}
