import { useCallback, useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { compressImage } from "@/lib/compressImage";
import { useAction, useMutation, useQuery } from "@mobile-lib/api";
import { api } from "@mobile-lib/api";
import type { Id } from "@mobile-lib/api";
import { useLocation, useNavigate } from "react-router-dom";
import { AppChrome } from "@/components/layout/AppChrome";
import { VoiceQuickAddWeb, type VoiceDraft } from "@/components/dashboard/VoiceQuickAddWeb";
import { TransactionEditDialog } from "@/components/transactions/TransactionEditDialog";
import { Drawer, EmptyState, Field, IconBox, inputClass, Modal, PrimaryButton, SecondaryButton, Segmented, StatusPill, Surface, SurfaceHeader, textareaClass, WorkspaceHeader } from "@/components/workspace/DesktopWorkspaceUI";
import { useWebAuth } from "@/contexts/WebAuthContext";
import { useWebPreferences } from "@/contexts/WebPreferencesContext";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import type { Transaction } from "@/types/transaction";

type EntryMode = "manual" | "ai" | "upload";
type EntryType = "expense" | "income";
type Draft = { amount: string; merchant: string; category: string; date: string; accountId: string; description: string; paymentMethod: string; type: EntryType };
type Filters = { search: string; type: "all" | EntryType; category: string; accountId: string; start: string; end: string; sort: "newest" | "oldest" | "highest" };
const freshDraft = (type: EntryType = "expense"): Draft => ({ amount: "", merchant: "", category: type === "expense" ? "Food & Dining" : "Salary", date: new Date().toISOString().slice(0,10), accountId: "", description: "", paymentMethod: "Cash", type });
const blankFilters: Filters = { search: "", type: "all", category: "", accountId: "", start: "", end: "", sort: "newest" };

function normalizeExtracted(data: unknown) { if (!data || typeof data !== "object") return {}; const root = data as Record<string, unknown>; const source = root.data && typeof root.data === "object" ? root.data as Record<string, unknown> : root.extracted_data && typeof root.extracted_data === "object" ? root.extracted_data as Record<string, unknown> : root; const number = typeof source.total_amount === "number" ? source.total_amount : Number(String(source.total_amount ?? "").replace(/[^0-9.-]/g,"")); return { amount: Number.isFinite(number) ? String(number) : "", merchant: typeof source.merchant_name === "string" ? source.merchant_name : "", category: typeof source.category === "string" ? source.category : "", date: typeof source.date === "string" ? source.date : "", paymentMethod: typeof source.payment_method === "string" ? source.payment_method : "" }; }
async function fileToBase64(file: File) { return await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => { const value = String(reader.result ?? ""); resolve(value.includes(",") ? value.split(",")[1]! : value); }; reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); }

export default function TransactionWorkspace() {
  const { workspace, ready } = useWorkspace(); const { user, token } = useWebAuth(); const { formatMoney, formatDate } = useWebPreferences(); const runtime = useQuery(api.admin.publicConfig, {});
  const location = useLocation(); const navigate = useNavigate();
  const rows = useQuery(api.transactions.list, ready && user ? { workspace, userId: user.id } : "skip") as Transaction[] | undefined;
  const categories = useQuery(api.categories.list, ready ? { workspace } : "skip"); const accounts = useQuery(api.accounts.list, ready ? { workspace } : "skip");
  const createTx = useMutation(api.transactions.create); const removeTx = useMutation(api.transactions.remove); const scan = useAction(api.scanReceipt.scanFromBase64); const uploadReceipt = useAction(api.receipts.upload);
  const [addOpen, setAddOpen] = useState(false); const [mode, setMode] = useState<EntryMode>("manual"); const [entrySource, setEntrySource] = useState<"manual" | "upload">("manual"); const [draft, setDraft] = useState<Draft>(() => freshDraft()); const [filters, setFilters] = useState<Filters>(blankFilters); const [filterOpen, setFilterOpen] = useState(false); const [selected, setSelected] = useState<Transaction | null>(null); const [editing, setEditing] = useState<Transaction | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [processing, setProcessing] = useState(false); const [processStep, setProcessStep] = useState(0); const [fileName, setFileName] = useState(""); const [receiptFile, setReceiptFile] = useState<File | null>(null);
  useEffect(() => { if (location.hash === "#add-transaction") setAddOpen(true); }, [location.hash]);
  useEffect(() => {
    const openFromShell = () => setAddOpen(true);
    window.addEventListener("receipt-cycle:add-transaction", openFromShell);
    return () => window.removeEventListener("receipt-cycle:add-transaction", openFromShell);
  }, []);
  const categoryNames = (categories ?? []).filter((category) => category.kind === draft.type).map((category) => category.name);
  const hints = { expenseCategories: (categories ?? []).filter((c) => c.kind === "expense").map((c) => c.name), incomeCategories: (categories ?? []).filter((c) => c.kind === "income").map((c) => c.name), accountNames: (accounts ?? []).map((a) => a.name) };
  const shown = useMemo(() => { const query = filters.search.trim().toLowerCase(); return [...(rows ?? [])].filter((row) => !query || `${row.merchant ?? ""} ${row.description ?? ""} ${row.category}`.toLowerCase().includes(query)).filter((row) => filters.type === "all" || row.type === filters.type).filter((row) => !filters.category || row.category === filters.category).filter((row) => !filters.accountId || row.accountId === filters.accountId).filter((row) => !filters.start || row.date >= filters.start).filter((row) => !filters.end || row.date <= filters.end).sort((a,b) => filters.sort === "oldest" ? a.date.localeCompare(b.date) : filters.sort === "highest" ? b.amount - a.amount : b.date.localeCompare(a.date)); }, [rows, filters]);
  const activeFilterCount = [filters.type !== "all", Boolean(filters.category), Boolean(filters.accountId), Boolean(filters.start), Boolean(filters.end)].filter(Boolean).length;

  const openAdd = (type: EntryType = "expense", nextMode: EntryMode = "manual") => { setReceiptFile(null); setDraft(freshDraft(type)); setMode(nextMode); setEntrySource("manual"); setMessage(null); setAddOpen(true); };
  const closeAdd = () => { setAddOpen(false); if (location.hash) navigate("/transactions", { replace: true }); };
  const applyVoiceDraft = useCallback((parsed: VoiceDraft) => { if (parsed.intent !== "transaction") { setMessage("This workspace is ready for a transaction. Open Budgets to save a budget limit."); return; } setDraft((current) => ({ ...current, type: parsed.type, amount: parsed.amount ? String(parsed.amount) : current.amount, merchant: parsed.merchant ?? "", category: parsed.category || current.category, date: parsed.date ?? current.date, description: parsed.description ?? "", paymentMethod: parsed.payment_method ?? current.paymentMethod })); setMode("manual"); setMessage("AI filled the form. Review each field before saving."); }, []);
  async function save(e: FormEvent) { e.preventDefault(); const amount = Number(draft.amount); if (!user || !token || !Number.isFinite(amount) || amount <= 0) { setMessage("Enter a valid amount and make sure you are signed in."); return; } setBusy(true); setMessage(null); try { let receiptKey: string | undefined; if (receiptFile) { try { receiptKey = (await uploadReceipt({ file: receiptFile, fileName: receiptFile.name })).key; } catch { receiptKey = undefined; } } await createTx({ workspace, userId: user.id, token, amount, type: draft.type, category: draft.category, merchant: draft.merchant.trim() || undefined, date: draft.date, description: draft.description.trim() || undefined, payment_method: draft.paymentMethod || undefined, accountId: draft.accountId ? draft.accountId as Id<"accounts"> : undefined, tags: [], is_recurring: false, entrySource, receipt_url: receiptKey }); setReceiptFile(null); setDraft(freshDraft(draft.type)); closeAdd(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save transaction."); } finally { setBusy(false); } }
  async function upload(e: ChangeEvent<HTMLInputElement>) { const picked = e.target.files?.[0]; e.target.value = ""; if (!picked) return; const file = await compressImage(picked); setFileName(file.name); if (file.type === "application/pdf") { setMessage("PDF statement import is available in Upload Statement. Receipt OCR currently accepts JPG, PNG, and other images."); return; } if (!token) return; setProcessing(true); setProcessStep(1); try { const base64 = await fileToBase64(file); setProcessStep(2); if (runtime?.scannerEnabled === false) throw new Error("Receipt scanner is currently unavailable."); const result = await scan({ imageBase64: base64, mimeType: file.type || "image/jpeg", sessionToken: token }); setProcessStep(3); if ("error" in result && result.error) throw new Error(result.error); const extracted = normalizeExtracted(result.extracted_data); setDraft((current) => ({ ...current, amount: extracted.amount || current.amount, merchant: extracted.merchant || current.merchant, category: extracted.category || current.category, date: extracted.date || current.date, paymentMethod: extracted.paymentMethod || current.paymentMethod })); setEntrySource("upload"); setReceiptFile(file); setProcessStep(4); setMode("manual"); setMessage("Receipt fields extracted. Review the draft before saving."); window.setTimeout(() => setProcessing(false), 650); } catch (error) { setProcessing(false); setMessage(error instanceof Error ? error.message : "Could not process the document."); } }
  async function remove(row: Transaction) { if (!user || !token || !window.confirm(`Delete ${row.merchant || row.category}?`)) return; await removeTx({ id: row.id as Id<"transactions">, userId: user.id, token }); setSelected(null); }

  return <AppChrome><div className="min-h-full text-slate-900"><WorkspaceHeader eyebrow="Records workspace" title="Transactions" description="Search, capture, review, edit, and filter every saved business record." actions={<><SecondaryButton icon="fa-wand-magic-sparkles" onClick={() => openAdd("expense", "ai")}>AI entry</SecondaryButton><PrimaryButton onClick={() => openAdd()}>Add transaction</PrimaryButton></>} />
    <Surface><div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row lg:items-center"><div className="relative flex-1"><i className="fas fa-search absolute left-3 top-3 text-xs text-slate-400" /><input className={`${inputClass} mt-0 pl-9`} placeholder="Search transactions, merchants, categories…" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /></div><Segmented options={[{ value: "all", label: "All" }, { value: "expense", label: "Expenses" }, { value: "income", label: "Income" }] as const} value={filters.type} onChange={(type) => setFilters({ ...filters, type })} /><SecondaryButton icon="fa-sliders" onClick={() => setFilterOpen(true)}>Filters{activeFilterCount ? ` (${activeFilterCount})` : ""}</SecondaryButton></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="w-10 px-4 py-3"><input type="checkbox" /></th><th>Date</th><th>Description</th><th>Category</th><th>Account</th><th>Type</th><th className="text-right">Amount</th><th className="w-10" /></tr></thead><tbody className="divide-y divide-slate-100">{shown.map((row) => { const account = (accounts ?? []).find((a) => String(a.id) === row.accountId); return <tr key={row.id} onClick={() => setSelected(row)} className="cursor-pointer hover:bg-slate-50"><td className="px-4 py-3" onClick={(e) => e.stopPropagation()}><input type="checkbox" /></td><td className="whitespace-nowrap text-slate-500">{formatDate(row.date)}</td><td><p className="font-bold text-slate-900">{row.merchant || row.description || row.category}</p><p className="max-w-[260px] truncate text-xs text-slate-400">{row.description}</p></td><td>{row.category}</td><td>{account?.name ?? "—"}</td><td><StatusPill status={row.type} /></td><td className={`text-right font-extrabold tabular-nums ${row.type === "income" ? "text-emerald-700" : "text-rose-700"}`}>{row.type === "income" ? "+" : "-"}{formatMoney(row.amount)}</td><td><i className="fas fa-chevron-right text-xs text-slate-400" /></td></tr>; })}</tbody></table>{shown.length === 0 ? <EmptyState icon="fa-receipt" title="No matching transactions" description="Adjust the filters or add a new expense or income record." /> : null}</div>
    </Surface>
    <Drawer open={addOpen} onClose={closeAdd} title={draft.type === "expense" ? "Add expense" : "Add income"} description="Save directly to the same ledger used by mobile" width="max-w-2xl"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><Segmented options={[{ value: "expense", label: "Expense" }, { value: "income", label: "Income" }] as const} value={draft.type} onChange={(type) => setDraft({ ...draft, type, category: type === "expense" ? "Food & Dining" : "Salary" })} /><Segmented options={[{ value: "manual", label: "Manual" }, { value: "ai", label: "AI voice / text" }, { value: "upload", label: "Upload" }] as const} value={mode} onChange={(value) => setMode(value as EntryMode)} /></div>
      {mode === "ai" ? <VoiceQuickAddWeb disabled={busy} hints={hints} onParsed={applyVoiceDraft} /> : null}
      {mode === "upload" ? <Surface className="border-dashed border-teal-300 bg-teal-50/50 p-7 text-center"><IconBox icon="fa-cloud-arrow-up" className="mx-auto h-14 w-14 text-lg" /><h3 className="mt-3 text-base font-extrabold">Drop files here or browse</h3><p className="mt-1 text-xs text-slate-500">JPG, PNG, or receipt image. PDF statements use the statement-import workflow.</p><label className="mt-4 inline-flex h-10 cursor-pointer items-center rounded-lg bg-teal-700 px-4 text-sm font-bold text-white"><input type="file" accept="image/*,.pdf" onChange={(e) => void upload(e)} hidden />Choose file</label>{fileName ? <p className="mt-3 text-xs font-bold text-teal-800">{fileName}</p> : null}</Surface> : null}
      {mode === "manual" ? <form onSubmit={(e) => void save(e)}><Surface className="p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Amount" required><input className={inputClass} type="number" inputMode="decimal" value={draft.amount} onChange={(e) => setDraft({ ...draft, amount: e.target.value })} /></Field><Field label={draft.type === "income" ? "Source" : "Merchant"}><input className={inputClass} value={draft.merchant} onChange={(e) => setDraft({ ...draft, merchant: e.target.value })} /></Field><Field label="Category"><select className={inputClass} value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })}>{categoryNames.length ? categoryNames.map((name) => <option key={name}>{name}</option>) : <option>{draft.category}</option>}</select></Field><Field label="Date"><input className={inputClass} type="date" value={draft.date} onChange={(e) => setDraft({ ...draft, date: e.target.value })} /></Field><Field label="Account"><select className={inputClass} value={draft.accountId} onChange={(e) => setDraft({ ...draft, accountId: e.target.value })}><option value="">No linked account</option>{(accounts ?? []).map((account) => <option key={String(account.id)} value={String(account.id)}>{account.name}</option>)}</select></Field><Field label="Paid from / account"><input className={inputClass} value={draft.paymentMethod} onChange={(e) => setDraft({ ...draft, paymentMethod: e.target.value })} /></Field><Field label="Notes" className="sm:col-span-2"><textarea className={textareaClass} value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /></Field></div></Surface>{message ? <p className="mt-3 rounded-lg bg-teal-50 px-3 py-2 text-xs font-semibold text-teal-800">{message}</p> : null}<div className="mt-5 flex justify-end gap-2"><SecondaryButton onClick={() => setAddOpen(false)}>Cancel</SecondaryButton><PrimaryButton type="submit" icon="fa-check" disabled={busy}>{busy ? "Saving…" : "Save transaction"}</PrimaryButton></div></form> : message ? <p className="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800">{message}</p> : null}
    </Drawer>
    <Drawer open={filterOpen} onClose={() => setFilterOpen(false)} title="Advanced filters" description="Narrow records without leaving the workspace"><div className="space-y-4"><Field label="Category"><select className={inputClass} value={filters.category} onChange={(e) => setFilters({ ...filters, category: e.target.value })}><option value="">All categories</option>{(categories ?? []).map((category) => <option key={String(category.id)}>{category.name}</option>)}</select></Field><Field label="Account"><select className={inputClass} value={filters.accountId} onChange={(e) => setFilters({ ...filters, accountId: e.target.value })}><option value="">All accounts</option>{(accounts ?? []).map((account) => <option key={String(account.id)} value={String(account.id)}>{account.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="From"><input type="date" className={inputClass} value={filters.start} onChange={(e) => setFilters({ ...filters, start: e.target.value })} /></Field><Field label="To"><input type="date" className={inputClass} value={filters.end} onChange={(e) => setFilters({ ...filters, end: e.target.value })} /></Field></div><Field label="Sort"><select className={inputClass} value={filters.sort} onChange={(e) => setFilters({ ...filters, sort: e.target.value as Filters["sort"] })}><option value="newest">Date: newest first</option><option value="oldest">Date: oldest first</option><option value="highest">Amount: highest first</option></select></Field><div className="flex justify-end gap-2"><SecondaryButton onClick={() => setFilters({ ...blankFilters, search: filters.search })}>Reset</SecondaryButton><PrimaryButton icon="fa-check" onClick={() => setFilterOpen(false)}>Show results ({shown.length})</PrimaryButton></div></div></Drawer>
    <Drawer open={Boolean(selected)} onClose={() => setSelected(null)} title="Transaction detail" description={selected?.id}>{selected ? <><div className="mb-5 rounded-xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{selected.type}</p><p className={`mt-1 text-3xl font-black ${selected.type === "income" ? "text-emerald-300" : "text-rose-300"}`}>{selected.type === "income" ? "+" : "-"}{formatMoney(selected.amount)}</p><p className="mt-2 text-sm font-bold">{selected.merchant || selected.category}</p><p className="text-xs text-slate-400">{formatDate(selected.date)}</p></div><Surface><div className="grid divide-y divide-slate-100"><Detail label="Category" value={selected.category} icon="fa-tags" /><Detail label="Account" value={(accounts ?? []).find((account) => String(account.id) === selected.accountId)?.name ?? "No linked account"} icon="fa-wallet" /><Detail label="Payment method" value={selected.payment_method || "Not specified"} icon="fa-credit-card" /><Detail label="Notes" value={selected.description || "No notes"} icon="fa-note-sticky" /></div></Surface>{selected.receipt_url || selected.receipt_data ? <Surface className="mt-4 p-4"><SurfaceHeader title="Receipt attachment" /><div className="mt-3 flex h-40 items-center justify-center rounded-lg bg-slate-100 text-slate-400"><i className="fas fa-receipt text-4xl" /></div></Surface> : null}<div className="mt-5 flex gap-2"><PrimaryButton icon="fa-pen" onClick={() => setEditing(selected)}>Edit transaction</PrimaryButton><SecondaryButton danger icon="fa-trash" onClick={() => void remove(selected)}>Delete</SecondaryButton></div></> : null}</Drawer>
    <TransactionEditDialog open={Boolean(editing)} transaction={editing} onClose={() => setEditing(null)} workspace={workspace} userId={user?.id ?? ""} token={token} />
    <Modal open={processing} onClose={() => {}} title="Processing receipt" description={fileName}><div className="grid gap-5 sm:grid-cols-[180px_1fr]"><div className="flex h-64 items-center justify-center rounded-xl bg-[linear-gradient(135deg,#f8fafc,#e2e8f0)]"><div className="rotate-[-3deg] rounded bg-white p-5 text-center shadow"><i className="fas fa-receipt text-4xl text-slate-400" /><p className="mt-3 text-xs font-bold">{fileName}</p></div></div><div className="space-y-4">{["Analyzing image", "Detecting receipt text", "Extracting fields", "Preparing review"].map((label,index) => <div key={label} className="flex items-center gap-3"><div className={`flex h-8 w-8 items-center justify-center rounded-full ${processStep > index ? "bg-teal-600 text-white" : processStep === index ? "bg-teal-100 text-teal-700" : "bg-slate-100 text-slate-400"}`}>{processStep > index ? <i className="fas fa-check text-xs" /> : processStep === index ? <i className="fas fa-circle-notch fa-spin text-xs" /> : index + 1}</div><p className={`text-sm font-bold ${processStep >= index ? "text-slate-900" : "text-slate-400"}`}>{label}</p></div>)}</div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600 transition-all" style={{ width: `${processStep * 25}%` }} /></div></Modal>
  </div></AppChrome>;
}

function Detail({ label, value, icon }: { label: string; value: string; icon: string }) { return <div className="flex items-center gap-3 px-4 py-3"><IconBox icon={icon} tone="blue" /><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-0.5 text-sm font-semibold text-slate-800">{value}</p></div></div>; }
