/**
 * Blog posts imported from user-provided DOCX content.
 */
export type BlogBlock =
  | { kind: "p"; text: string }
  | { kind: "h2"; text: string; id: string }
  | { kind: "h3"; text: string; id: string }
  | { kind: "links"; title: string; items: Array<{ label: string; href: string; external?: boolean }> }
  | { kind: "ul"; items: string[] }
  | { kind: "ol"; items: string[] }
  | { kind: "quote"; text: string; cite?: string }
  | { kind: "callout"; title: string; text: string };

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  featuredImage: string;
  datePublished: string;
  dateModified: string;
  author: string;
  readMinutes: number;
  tags: string[];
  tldr: string;
  body: BlogBlock[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "maximize-tax-refund-by-scanning-receipts",
    title: "How to Maximize Your Tax Refund by Scanning Receipts",
    description: "Most people miss tax deductions because they lose receipts. This guide shows how to scan once, store digitally, and claim every legitimate expense with confidence.",
    featuredImage: "/landing/feature-blog-maximize-tax-refund-by-scanning-receipts.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 9,
    tags: ["tax refund", "receipt scanning", "freelancer", "audit", "bookkeeping"],
    tldr: "Every year, millions of people leave money on the table at tax time, not because they didn't spend on legitimate deductions, but because they lost the receipts to prove it.",
    body: [
      { kind: "p", text: "Every year, millions of people leave money on the table at tax time, not because they didn't spend on legitimate deductions, but because they lost the receipts to prove it." },
      { kind: "p", text: "A crumpled coffee receipt here. A faded pharmacy slip there. A work dinner you're almost sure you paid for but can't confirm. Before you know it, you've handed back hundreds, sometimes thousands, of dollars that were rightfully yours to claim." },
      { kind: "p", text: "The good news? Keeping your receipts no longer means stuffing a shoebox under your desk and hoping for the best." },
      { kind: "h2", text: "Why Most People Leave Money on the Table", id: "why-most-people-leave-money-on-the-table" },
      { kind: "p", text: "Here's the honest truth: most people don't miss deductions because they're careless. They miss them because managing paper receipts is genuinely inconvenient. Ink fades. Paper tears. You're in a rush at checkout, and the receipt ends up at the bottom of your bag." },
      { kind: "p", text: "By the time tax season rolls around, that evidence is gone and so is your refund." },
      { kind: "p", text: "The IRS and most tax authorities don't require you to keep paper copies of receipts. Digital records are fully accepted, as long as they clearly show the vendor, amount, date, and nature of the expense. That changes everything. Because scanning receipts the moment you get them is quick, easy, and permanent." },
      { kind: "h2", text: "What Actually Qualifies as a Tax Deduction?", id: "what-actually-qualifies-as-a-tax-deduction" },
      { kind: "p", text: "Before you start scanning, it helps to know what you're looking for. The list of qualifying deductions is longer than most people realize." },
      { kind: "h3", text: "If you're self-employed or run a small business", id: "self-employed-small-business-deductions" },
      {
        kind: "ul",
        items: [
          "Office supplies and equipment",
          "Software subscriptions used for work",
          "Business travel — flights, hotels, transport",
          "Client meals (typically 50% deductible)",
          "Home office expenses",
          "Phone and internet (the portion used for business)",
          "Professional development and courses",
        ],
      },
      { kind: "h3", text: "If you're an employee", id: "employee-deductions" },
      {
        kind: "ul",
        items: [
          "Unreimbursed work expenses (depending on your country and situation)",
          "Charitable donations",
          "Medical expenses above a certain threshold",
          "Childcare costs in some circumstances",
        ],
      },
      { kind: "p", text: "The rule of thumb is simple: if you spent money to earn money, or to support a legitimate life expense your tax authority recognizes, it's worth tracking. A receipt scanner turns that rule into a habit." },
      { kind: "h2", text: "The Problem With Paper Receipts", id: "the-problem-with-paper-receipts" },
      { kind: "p", text: "Think about the last time you actually filed all your receipts properly. For most people, the honest answer involves a pile on the kitchen counter, a few in the car glove compartment, and a vague memory of \"I think I kept that one.\"" },
      { kind: "p", text: "Paper receipts are designed to be temporary. Thermal paper — the shiny kind most retailers use — fades within months. Humidity, heat, and friction accelerate that process. By the time your accountant needs to see documentation, the receipt you held onto is often unreadable." },
      { kind: "p", text: "There's also the time problem. Manually entering expense data into a spreadsheet, or sorting through months of paper before a filing deadline, costs you hours you don't have." },
      { kind: "p", text: "Scanning receipts solves both problems at once." },
      { kind: "h2", text: "How Scanning Receipts With ReceiptCycle Works", id: "how-scanning-receipts-with-receiptcycle-works" },
      { kind: "p", text: "ReceiptCycle is built around one simple idea: scan once, claim your refund." },
      { kind: "p", text: "Here's how it works in practice:" },
      { kind: "p", text: "You get a receipt — at a restaurant, a store, a gas station, anywhere." },
      { kind: "p", text: "You open ReceiptCycle and snap a photo — it takes about ten seconds." },
      { kind: "p", text: "The app reads the receipt automatically — pulling out the vendor name, date, amount, and category using AI." },
      { kind: "p", text: "Your expense is stored securely in the cloud — organized, searchable, and ready whenever you need it." },
      { kind: "p", text: "That's it. No spreadsheets. No shoeboxes. No frantic searching the night before your accountant meeting." },
      { kind: "p", text: "At the end of the tax year, you have a clean, categorized record of every deductible expense you captured throughout the year. You can export it, share it, or hand it straight to your accountant." },
      { kind: "h2", text: "FAQ: Common Questions About Digital Receipts and Taxes", id: "faq-common-questions-about-digital-receipts-and-taxes" },
      { kind: "h3", text: "Do digital receipts count for tax purposes?", id: "do-digital-receipts-count-for-tax-purposes" },
      { kind: "p", text: "Yes. The IRS and most tax authorities worldwide accept digital images of receipts as valid documentation, provided the image clearly shows the relevant details. ReceiptCycle stores high-quality scans that meet this standard." },
      { kind: "h3", text: "How long do I need to keep my receipts?", id: "how-long-do-i-need-to-keep-my-receipts" },
      { kind: "p", text: "The IRS recommends keeping records for at least three years from the date you filed your return, though six years is safer if there's any chance you underreported income. ReceiptCycle stores your scans indefinitely in secure cloud storage." },
      { kind: "h3", text: "What if I lose my phone?", id: "what-if-i-lose-my-phone" },
      { kind: "p", text: "Your receipts are backed up to the cloud, not stored locally on your device. If you lose your phone, your records are completely safe." },
      { kind: "h3", text: "Do I need receipts for small purchases?", id: "do-i-need-receipts-for-small-purchases" },
      { kind: "p", text: "The IRS generally requires receipts for business expenses over $75, but keeping records of smaller amounts is a good habit — they add up faster than you think." },
      { kind: "h2", text: "Start Small, Win Big", id: "start-small-win-big" },
      { kind: "p", text: "You don't need to overhaul your entire financial system to start seeing results. The simplest shift you can make is this: the next time you get a receipt, scan it before you pocket it." },
      { kind: "p", text: "That one habit — repeated consistently — adds up to a more complete tax return, a bigger refund, and a lot less stress every April." },
      { kind: "p", text: "ReceiptCycle makes it easy to start. Scan your first receipt free and see how simple organized expenses can be." },
      { kind: "p", text: "Your refund is waiting. You just need to keep the evidence." },
      {
        kind: "links",
        title: "Helpful resources",
        items: [
          { label: "How to go paperless with receipts", href: "/blog/go-paperless-with-receipts" },
          { label: "Freelancer expense tracking guide", href: "/blog/freelancers-guide-tracking-business-expenses" },
          { label: "IRS recordkeeping overview", href: "https://www.irs.gov/businesses/small-businesses-self-employed/what-kind-of-records-should-i-keep", external: true },
        ],
      },
    ],
  },
  {
    slug: "best-receipt-scanner-app-small-business-2026",
    title: "Best Receipt Scanner App for Small Businesses in 2026",
    description: "An honest comparison of receipt scanner apps in 2026 and how to choose the right one for your small business workflow, budget, and tax goals.",
    featuredImage: "/landing/feature-blog-best-receipt-scanner-app-small-business-2026.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 8,
    tags: ["receipt scanner app", "small business", "expense tracking", "OCR", "tax prep"],
    tldr: "If you've ever Googled \"receipt scanner app\" and found yourself staring at a dozen options with no clear idea which one to choose, you're not alone.",
    body: [
      { kind: "p", text: "If you've ever Googled \"receipt scanner app\" and found yourself staring at a dozen options with no clear idea which one to choose, you're not alone." },
      { kind: "p", text: "The market is crowded. Some tools are built for large enterprise teams. Others are too basic to be useful. A few are just expensive spreadsheets with a camera button." },
      { kind: "p", text: "This guide cuts through the noise. We looked at the most popular options in 2026, compared them honestly, and broke down exactly who each one is best for so you can stop researching and start scanning." },
      { kind: "h2", text: "What to Look for in a Receipt Scanner App", id: "what-to-look-for-in-a-receipt-scanner-app" },
      { kind: "p", text: "Before you compare specific apps, it helps to know what actually matters. Not every feature on a spec sheet is worth paying for." },
      { kind: "p", text: "Here's what makes a real difference for small businesses:" },
      {
        kind: "ul",
        items: [
          "Accuracy of the scan — Can the app reliably read a crumpled or faded receipt? Poor OCR (text recognition) means more manual corrections, which defeats the purpose.",
          "Automatic categorization — Does the app sort your expenses into categories automatically, or do you have to do it yourself every time?",
          "Cloud storage — Are your receipts backed up securely so you can access them from any device, and never lose them?",
          "Export options — Can you share reports easily with your accountant or import into your accounting software?",
          "Price — Is the cost justified for a small operation, or are you paying for enterprise features you'll never use?",
        ],
      },
      { kind: "p", text: "With those criteria in mind, here's how the leading apps stack up." },
      { kind: "h3", text: "ReceiptCycle — Best for: Tax-focused simplicity", id: "receiptcycle-best-for-tax-focused-simplicity" },
      { kind: "p", text: "ReceiptCycle was built around one promise: scan once, claim your refund. For small business owners who want to capture every deductible expense without learning a complex piece of software, it's the most focused tool available." },
      { kind: "p", text: "The app scans receipts with your phone camera, automatically extracts the vendor, amount, date, and category, and stores everything in secure cloud storage. At tax time, you export a clean report and hand it to your accountant — or file it yourself." },
      { kind: "p", text: "What makes ReceiptCycle stand out is that it doesn't try to do everything. It does receipt capture and expense organization exceptionally well, and it keeps the experience simple enough that you'll actually use it consistently." },
      { kind: "p", text: "Best for: Freelancers, sole traders, small business owners who want a clean, affordable way to track expenses for tax purposes." },
      { kind: "h3", text: "Expensify — Best for: Larger teams with travel expense needs", id: "expensify-best-for-larger-teams" },
      { kind: "p", text: "Expensify is one of the most well-known names in expense management, and for good reason. It handles receipt scanning, mileage tracking, corporate card integration, and multi-level approval workflows — all under one roof." },
      { kind: "p", text: "The trade-off is complexity and cost. Expensify is designed for companies with teams of employees submitting expenses for approval. If you're a sole trader or a small operation with a handful of people, you'll likely find yourself paying for features you never touch." },
      { kind: "p", text: "Best for: Businesses with 10+ employees, frequent travelers, and teams that need structured approval workflows." },
      { kind: "h3", text: "Shoeboxed — Best for: Paper-heavy businesses", id: "shoeboxed-best-for-paper-heavy-businesses" },
      { kind: "p", text: "Shoeboxed takes a unique approach: you can mail your physical receipts to their processing center, and they'll scan and digitize them for you. It's a genuinely useful service for businesses that deal with large volumes of paper — construction, trades, retail." },
      { kind: "p", text: "The downside is that it's slower than scanning yourself, and the pricing gets steep as your volume increases." },
      { kind: "p", text: "Best for: Businesses that generate lots of paper receipts and want a hands-off approach to digitizing them." },
      { kind: "h3", text: "Wave — Best for: Free accounting with light receipt scanning", id: "wave-best-for-free-accounting" },
      { kind: "p", text: "Wave is primarily a free accounting platform, and receipt scanning is one of its supporting features. If you're already using Wave for invoicing or bookkeeping, the receipt scanning capability is a decent addition." },
      { kind: "p", text: "On its own, though, Wave's receipt features are more limited than dedicated apps. It's a good starting point for businesses just beginning to track expenses, but you may outgrow it quickly." },
      { kind: "p", text: "Best for: Sole traders and very small businesses already using Wave for accounting who want basic receipt capture." },
      { kind: "h2", text: "Quick Comparison: Which App Is Right for You?", id: "quick-comparison-which-app-is-right-for-you" },
      { kind: "h2", text: "So, Which One Should You Choose?", id: "so-which-one-should-you-choose" },
      { kind: "p", text: "Here's an honest way to think about it." },
      { kind: "p", text: "If you're running a small business, freelancing, or self-employed — and your main goal is to capture every receipt, stay organized, and make tax time less painful — ReceiptCycle is the right fit. It's built for exactly that job, it won't overwhelm you with features you don't need, and it's priced for businesses at your scale." },
      { kind: "p", text: "If you're managing a team of employees with complex expense workflows and corporate cards, Expensify may be worth the investment." },
      { kind: "p", text: "If you're buried in paper and the idea of scanning every receipt yourself sounds exhausting, Shoeboxed's mail-in service solves a real problem." },
      { kind: "p", text: "And if you're just getting started and want free tools to dip your toes in, Wave is a reasonable place to begin — just know you'll likely want something more focused as your business grows." },
      { kind: "p", text: "The best receipt scanner app isn't the one with the most features. It's the one you'll actually use every day. For most small business owners, that means something simple, fast, and purpose-built for staying tax-ready all year." },
      { kind: "h2", text: "Making the Switch Is Easier Than You Think", id: "making-the-switch-is-easier-than-you-think" },
      { kind: "p", text: "Switching from a shoebox — or no system at all — to a dedicated receipt scanner takes about five minutes. You download the app, scan your first receipt, and the system does the rest." },
      { kind: "p", text: "The real cost isn't the subscription. It's every deductible expense you've been missing because you had no consistent way to capture it." },
      { kind: "p", text: "Try ReceiptCycle free for 30 days and see what a difference an organized expense habit makes. No credit card required to get started." },
      { kind: "p", text: "The right tool, used consistently, makes tax time something you actually look forward to. Or at least something you stop dreading." },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Maximize tax refund by scanning receipts", href: "/blog/maximize-tax-refund-by-scanning-receipts" },
          { label: "Freelancer expense tracking guide", href: "/blog/freelancers-guide-tracking-business-expenses" },
          { label: "HMRC expenses and allowances", href: "https://www.gov.uk/expenses-if-youre-self-employed", external: true },
        ],
      },
    ],
  },
  {
    slug: "freelancers-guide-tracking-business-expenses",
    title: "The Freelancer's Complete Guide to Tracking Business Expenses",
    description: "A practical expense-tracking system for freelancers: what to deduct, what records to keep, and how to build a two-minute daily habit that saves money at tax time.",
    featuredImage: "/landing/feature-blog-freelancers-guide-tracking-business-expenses.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 10,
    tags: ["freelancer taxes", "business expenses", "receipt tracking", "schedule c", "bookkeeping"],
    tldr: "Here's something most freelancers figure out the hard way: the money you save on taxes is just as real as the money you earn from clients.",
    body: [
      { kind: "p", text: "Here's something most freelancers figure out the hard way: the money you save on taxes is just as real as the money you earn from clients." },
      { kind: "p", text: "You could land a great project this month, do excellent work, get paid on time, and then hand a bigger chunk than necessary back to the government in April, simply because you didn't keep track of what you spent to do that work." },
      { kind: "p", text: "Expense tracking isn't just an accounting task. For freelancers, it's one of the most direct ways to increase your take-home income without working an extra hour." },
      { kind: "p", text: "This guide will show you how to build a receipt habit that works, what you should be tracking, and how to set up ReceiptCycle so the whole process takes minutes a week instead of hours a month." },
      { kind: "h2", text: "Why Freelancers Overpay Taxes More Than Anyone Else", id: "why-freelancers-overpay-taxes-more-than-anyone-else" },
      { kind: "p", text: "When you work for an employer, someone else handles the complicated parts of your taxes. Deductions are applied automatically. Your W-2 arrives in January. You plug in the numbers, and you're done." },
      { kind: "p", text: "When you're freelancing, you're the employer and the employee. That means every deductible expense is your responsibility to claim — and if you don't, you don't get it back." },
      { kind: "p", text: "The IRS and most tax authorities allow self-employed people to deduct a wide range of legitimate business expenses from their taxable income. The catch is that you need to document them. No receipt, no deduction. And with no system to capture those receipts in real time, most freelancers end up filing with incomplete records and paying more tax than they should." },
      { kind: "p", text: "Studies consistently show that self-employed individuals leave thousands of dollars in deductions unclaimed each year, not because they didn't qualify, but because they couldn't prove they spent the money." },
      { kind: "h2", text: "What Counts as a Deductible Business Expense for Freelancers?", id: "what-counts-as-a-deductible-business-expense-for-freelancers" },
      { kind: "p", text: "The list is more generous than most people realise. If you spent money in the process of running your freelance business, there's a good chance it qualifies — at least in part." },
      { kind: "p", text: "Here are the most commonly overlooked categories:" },
      {
        kind: "ul",
        items: [
          "Home office. If you work from home and have a dedicated space — even a corner of a room used exclusively for work — you may be able to deduct a portion of your rent or mortgage, utilities, and internet.",
          "Software and subscriptions. Design tools, project management apps, accounting software, cloud storage, and stock photo subscriptions. If you use it for work, track it.",
          "Hardware and equipment. Laptops, monitors, cameras, microphones, and keyboards. The percentage of time you use equipment for work versus personal use matters, but work-related use is deductible.",
          "Professional development. Online courses, books, industry memberships, conference tickets. Staying sharp in your field is a legitimate business expense.",
          "Client meals and entertainment. If you take a client to lunch or meet someone for coffee to discuss a project, that expense is typically 50% deductible. Keep the receipt and note who you met with.",
          "Travel. If you travel for work to meet clients, attend events, or complete a project, flights, accommodation, and transport are deductible. Even the miles you drive to a client meeting add up.",
          "Phone and internet. You can deduct the portion of your phone and internet bill that you use for business. Estimate honestly, and document the basis for your estimate.",
        ],
      },
      { kind: "h2", text: "How to Build a Receipt Habit That Takes 2 Minutes a Day", id: "how-to-build-a-receipt-habit-that-takes-2-minutes-a-day" },
      { kind: "p", text: "The biggest barrier to expense tracking isn't complexity — it's consistency. Most freelancers start strong in January and fade out by March." },
      { kind: "p", text: "The secret is making the habit as frictionless as possible." },
      { kind: "p", text: "Here's a simple system that works:" },
      { kind: "h3", text: "Step 1: Scan instantly", id: "freelancer-step-1-scan-instantly" },
      { kind: "p", text: "Scan the receipt the moment you get it. Don't wait until you get home. Don't stack them on your desk to deal with later. Open ReceiptCycle, take a photo of the receipt before you pocket it, and you're done. The whole thing takes ten seconds." },
      { kind: "h3", text: "Step 2: Keep categories consistent", id: "freelancer-step-2-keep-categories-consistent" },
      { kind: "p", text: "Keep your categories consistent. ReceiptCycle auto-categorizes most expenses, but it helps to use the same categories throughout the year. If you call it \"software\" in January, call it \"software\" in October. Consistency makes your year-end report much easier to read." },
      { kind: "h3", text: "Step 3: Weekly five-minute review", id: "freelancer-step-3-weekly-review" },
      { kind: "p", text: "Do a five-minute weekly review. Once a week — Friday afternoon works well — open the app and scroll through what you captured. Check that the amounts look right and the categories make sense. Catching a misread receipt takes thirty seconds. Catching twelve of them in December takes an afternoon." },
      { kind: "h3", text: "Step 4: Forward digital receipts", id: "freelancer-step-4-forward-digital-receipts" },
      { kind: "p", text: "Forward digital receipts immediately. For online purchases, email confirmations, and subscription renewals, ReceiptCycle lets you forward receipts directly to a dedicated email address. They're processed automatically, so you never have to think about them." },
      { kind: "p", text: "That's the whole system. Four steps. No spreadsheets. No end-of-year chaos." },
      { kind: "h2", text: "Setting Up ReceiptCycle for Freelance Expense Tracking", id: "setting-up-receiptcycle-for-freelance-expense-tracking" },
      { kind: "p", text: "Getting started takes about five minutes." },
      { kind: "p", text: "Download the app and create your account. During setup, you can choose categories that reflect your freelance work — feel free to customize them. The default categories cover most common freelance expenses, but you might want to add specific ones for your industry." },
      { kind: "p", text: "From there, the workflow is simple: scan, confirm, move on. The app reads the key information from each receipt automatically. You review it, adjust the category if needed, and save." },
      { kind: "p", text: "At any point during the year, you can pull up a dashboard showing your total expenses by category, your spending trends over time, and any receipts that might need attention. When tax season arrives, you export the report in whatever format your accountant prefers — PDF or CSV — and share it directly from the app." },
      { kind: "h2", text: "How to Generate an Expense Report for Your Accountant", id: "how-to-generate-an-expense-report-for-your-accountant" },
      { kind: "p", text: "One of the most appreciated things you can do for your accountant — and for yourself — is arrive at tax time with organized records." },
      { kind: "p", text: "ReceiptCycle generates a complete expense report with one tap. The report includes:" },
      { kind: "h3", text: "What your report should include", id: "freelancer-report-should-include" },
      {
        kind: "ul",
        items: [
          "Every captured receipt with a digital image",
          "Vendor name, date, amount, and category for each expense",
          "Subtotals by category for the period you select",
          "A summary of total deductible expenses",
        ],
      },
      { kind: "p", text: "Export it as a PDF to share directly, or as a CSV if your accountant wants to import it into their own software. Either way, you walk into the conversation prepared — which typically means a shorter meeting and a bigger refund." },
      { kind: "h2", text: "End-of-Year Checklist: Receipts Every Freelancer Should Have", id: "end-of-year-checklist-receipts-every-freelancer-should-have" },
      { kind: "p", text: "Before you file, run through this list and make sure you have documentation for each category that applies to you:" },
      { kind: "p", text: "Home office expenses (rent/mortgage portion, utilities, internet)" },
      { kind: "p", text: "All software and app subscriptions for the year" },
      { kind: "p", text: "Hardware or equipment purchased for work" },
      { kind: "p", text: "Professional development — courses, books, events" },
      { kind: "p", text: "Client meals and the names of who you met with" },
      { kind: "p", text: "Business travel — flights, hotels, transport, mileage" },
      { kind: "p", text: "Phone bill (business-use portion)" },
      { kind: "p", text: "Any professional services — accountants, lawyers, contractors" },
      { kind: "p", text: "If you've been scanning consistently throughout the year, most of this is already organized in ReceiptCycle. The checklist is just a final sweep to make sure nothing slipped through." },
      { kind: "p", text: "ReceiptCycle exists to make sure you never leave that money behind. Start tracking your freelance expenses free today — and go into your next tax filing knowing you claimed every dollar you earned." },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Best receipt scanner app for small business", href: "/blog/best-receipt-scanner-app-small-business-2026" },
          { label: "Go paperless with receipts", href: "/blog/go-paperless-with-receipts" },
          { label: "Schedule C instructions (IRS)", href: "https://www.irs.gov/forms-pubs/about-schedule-c-form-1040", external: true },
        ],
      },
    ],
  },
  {
    slug: "go-paperless-with-receipts",
    title: "How to Go Paperless With Your Receipts (And Never Lose One Again)",
    description: "Paper receipts fade and disappear. Learn the legal, practical, and technical workflow for moving to secure digital receipts with zero tax-season chaos.",
    featuredImage: "/landing/feature-blog-go-paperless-with-receipts.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 9,
    tags: ["paperless receipts", "digital receipts", "tax records", "cloud backup", "OCR"],
    tldr: "Picture this: it's the week before your tax deadline. You're sitting at the kitchen table surrounded by a pile of receipts, some faded, some torn, one that's been through the wash.",
    body: [
      { kind: "p", text: "Picture this: it's the week before your tax deadline. You're sitting at the kitchen table surrounded by a pile of receipts, some faded, some torn, one that's been through the wash." },
      { kind: "p", text: "You're squinting at a thermal slip trying to read whether that charge was $14 or $44, and you're pretty sure you've lost the receipt for the biggest business purchase you made all year." },
      { kind: "p", text: "Sound familiar? You're in good company. But it doesn't have to be this way." },
      { kind: "p", text: "Going paperless with your receipts is simpler than most people expect, and the payoff is less stress, better records, and a bigger tax refund, making it one of the smartest financial habits you can build." },
      { kind: "h2", text: "The Real Cost of Losing a Receipt", id: "the-real-cost-of-losing-a-receipt" },
      { kind: "p", text: "Most people think of a lost receipt as a minor inconvenience. In reality, it has a direct financial cost." },
      { kind: "p", text: "Every receipt you can't produce at tax time is a deduction you can't claim. At an average tax rate of 22–25%, a $200 expense you can't document costs you $44 to $50 in unclaimed refund money. Lose ten receipts like that across a year, and you've given back $400 to $500 that was rightfully yours." },
      { kind: "p", text: "There's also the audit risk. If the IRS or your tax authority questions a deduction and you can't produce the receipt, the deduction is typically disallowed — and you may face penalties on top. Digital records that are well-organized and date-stamped are actually stronger evidence than crumpled paper, because they're harder to fabricate or alter after the fact." },
      { kind: "p", text: "Going paperless isn't just tidier. It's financially smarter." },
      { kind: "h2", text: "Are Digital Receipts Legally Valid?", id: "are-digital-receipts-legally-valid" },
      { kind: "p", text: "This is the question most people ask first, and the answer is a clear yes." },
      { kind: "p", text: "The IRS has explicitly accepted digital images of receipts as valid documentation since Revenue Procedure 98-25 — which means this has been settled policy for over 25 years. You are not required to keep paper originals as long as your digital records are legible, accurate, and include the key details: vendor name, date, amount, and the nature of the purchase." },
      { kind: "p", text: "The same is true in the UK under HMRC guidance, in Canada under CRA rules, and in most other major tax jurisdictions around the world." },
      { kind: "p", text: "What matters is the quality of your records, not the format they're stored in. A clear phone photo of a receipt, properly organized and backed up, meets the standard." },
      { kind: "h2", text: "Step 1: Scan Every Receipt the Moment You Get It", id: "step-1-scan-every-receipt-the-moment-you-get-it" },
      { kind: "p", text: "This is the step that makes or breaks the whole system." },
      { kind: "p", text: "The temptation is to save receipts and scan them in batches later. The problem is that \"later\" becomes the weekend, the weekend becomes the end of the month, and by then receipts are lost, faded, or stuffed in three different pockets of three different jackets." },
      { kind: "p", text: "The most effective approach is also the simplest: scan immediately." },
      { kind: "p", text: "When you get a receipt — at a restaurant, a store, a gas station — open ReceiptCycle before you put the receipt away and take a photo. The app reads the information automatically. The whole process takes about ten seconds." },
      { kind: "p", text: "Ten seconds at the moment of purchase beats thirty minutes of frustrating receipt archaeology at the end of the month." },
      { kind: "h2", text: "Step 2: Let ReceiptCycle Categorize and Organize", id: "step-2-let-receiptcycle-categorize-and-organize" },
      { kind: "p", text: "Once you scan a receipt, ReceiptCycle's AI does the rest." },
      { kind: "p", text: "It reads the vendor name, transaction date, total amount, and any tax details from the image, then assigns the expense to a category automatically. You can review the result, adjust the category if needed, and move on." },
      { kind: "p", text: "Over time, the system learns your patterns. If you always categorize receipts from the same coffee shop as \"client meals,\" it will start doing that automatically." },
      { kind: "p", text: "The result is an organized expense log that builds itself throughout the year. By the time you need it for tax purposes, the work is already done." },
      { kind: "h2", text: "Step 3: Store in the Cloud — Access Anywhere, Any Time", id: "step-3-store-in-the-cloud-access-anywhere-any-time" },
      { kind: "p", text: "One of the biggest advantages of digital receipts over paper is that they live in the cloud, not in your desk drawer." },
      { kind: "p", text: "ReceiptCycle stores every scan securely in encrypted cloud storage. That means:" },
      {
        kind: "ul",
        items: [
          "You can't lose your records — a lost phone, a flooded office, or a fire won't erase your receipt archive.",
          "You can access them from any device — pull up a receipt on your laptop, tablet, or a colleague's phone when you need it.",
          "You can share directly with accountants — export a report or grant read access without printing or emailing attachments.",
        ],
      },
      { kind: "p", text: "Cloud storage also means your records are automatically backed up. There's no \"I think I saved that file\" — it's just there, whenever you need it." },
      { kind: "h2", text: "How Long Should You Keep Digital Receipts?", id: "how-long-should-you-keep-digital-receipts" },
      { kind: "p", text: "The general rule in the US is to keep tax-related records for three years from the date you filed your return. That covers the standard IRS audit window." },
      { kind: "h3", text: "Exceptions worth knowing", id: "paperless-exceptions-worth-knowing" },
      {
        kind: "ul",
        items: [
          "If you underreported income by more than 25%, the IRS has six years to audit.",
          "For employment tax records, keep records for at least four years.",
          "If you file a claim for a loss, you may need records going back further.",
        ],
      },
      { kind: "p", text: "Because ReceiptCycle stores your scans indefinitely in the cloud, you don't need to actively manage this. Your records are there when you need them, for as long as you need them. You can also export and download a full archive at any point if you want a local backup." },
      { kind: "h2", text: "FAQ: 5 Common Questions About Digital Receipts", id: "faq-5-common-questions-about-digital-receipts" },
      { kind: "h3", text: "Can I throw away paper receipts after scanning them?", id: "can-i-throw-away-paper-receipts-after-scanning-them" },
      { kind: "p", text: "Yes, in most cases. Once you've scanned a receipt and confirmed the image is clear and complete, the paper original serves no additional purpose from a tax or legal standpoint. The digital copy is your record." },
      { kind: "h3", text: "What if the scan is blurry or the text is hard to read?", id: "what-if-the-scan-is-blurry-or-the-text-is-hard-to-read" },
      { kind: "p", text: "ReceiptCycle will flag receipts where it can't extract information reliably. Retake the photo in better light, or manually enter the details. The app prompts you before saving an incomplete record." },
      { kind: "h3", text: "Does this work for email receipts and digital purchases?", id: "does-this-work-for-email-receipts-and-digital-purchases" },
      { kind: "p", text: "Yes. For online orders, subscription renewals, or any purchase where the receipt arrives by email, you can forward it to your dedicated ReceiptCycle address and it's processed automatically — no scanning required." },
      { kind: "h3", text: "What about receipts in foreign currencies?", id: "what-about-receipts-in-foreign-currencies" },
      { kind: "p", text: "ReceiptCycle supports multiple currencies and handles the conversion automatically based on the transaction date. Useful for business travel or international purchases." },
      { kind: "h3", text: "Is my financial data safe in the cloud?", id: "is-my-financial-data-safe-in-the-cloud" },
      { kind: "p", text: "ReceiptCycle uses bank-level encryption to protect your records. Your data is stored securely and only accessible to you — or anyone you explicitly choose to share it with." },
      { kind: "h2", text: "Make the Switch Today", id: "make-the-switch-today" },
      { kind: "p", text: "Going paperless with your receipts doesn't require a big system overhaul or a weekend of setup. It requires one decision: the next time you get a receipt, scan it instead of pocketing it." },
      { kind: "p", text: "That single shift, applied consistently, transforms how you handle expenses. No more lost deductions. No more tax-time stress. No more guessing whether you have the documentation you need." },
      { kind: "p", text: "ReceiptCycle makes it easy to start. Scan your first receipt free — in about thirty seconds — and see how quickly an organized digital system starts to feel natural." },
      { kind: "p", text: "Paper receipts were always a temporary solution. A permanent digital record is simply better in every way that matters." },
      {
        kind: "links",
        title: "Helpful resources",
        items: [
          { label: "Maximize your tax refund by scanning receipts", href: "/blog/maximize-tax-refund-by-scanning-receipts" },
          { label: "Gig worker expense guide", href: "/blog/gig-workers-income-expense-guide" },
          { label: "IRS Rev. Proc. 98-25", href: "https://www.irs.gov/pub/irs-drop/rp-97-22.pdf", external: true },
        ],
      },
    ],
  },
  {
    slug: "gig-workers-income-expense-guide",
    title: "Receipt Tracking for Uber, DoorDash & Gig Workers Income and Expense Guide",
    description: "A full expense and receipt guide for gig workers: what to deduct, what proof to keep, and how to avoid leaving $500-$2,000 in deductions unclaimed.",
    featuredImage: "/landing/feature-blog-gig-workers-income-expense-guide.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 11,
    tags: ["gig worker taxes", "uber deductions", "doordash expenses", "receipt tracking", "schedule c"],
    tldr: "If you drive for Uber, deliver for DoorDash, run errands for Instacart, or pick up gig work on any platform, you're running a small business even if it doesn't feel like one.",
    body: [
      { kind: "p", text: "If you drive for Uber, deliver for DoorDash, run errands for Instacart, or pick up gig work on any platform, you're running a small business even if it doesn't feel like one." },
      { kind: "p", text: "And like any business, you have expenses. Gas. Car maintenance. Your phone. Tolls. Insurance. Every time you pay for something that makes your work possible, that's a potential tax deduction." },
      { kind: "p", text: "The problem is, most gig workers never claim all of them not because they don't qualify, but because they didn't keep the receipts to prove it." },
      { kind: "p", text: "This guide will show you exactly what you can deduct, why gig workers leave so much money unclaimed, and how to build a simple receipt habit with ReceiptCycle that takes seconds between rides not hours at the end of the year." },
      { kind: "h2", text: "What Expenses Can Gig Drivers Deduct? (The Full List)", id: "what-expenses-can-gig-drivers-deduct-the-full-list" },
      { kind: "p", text: "As an independent contractor, which is what you are when you work for a gig platform, you can deduct the ordinary and necessary costs of running your work. Here's what that looks like in practice:" },
      { kind: "h3", text: "Fuel and vehicle costs", id: "gig-fuel-and-vehicle-costs" },
      { kind: "p", text: "Gas and fuel. This is the obvious one. Every gallon you buy to do your work is a deductible expense. Keep every fuel receipt, every time." },
      { kind: "p", text: "Vehicle maintenance. Oil changes, tire rotations, brake pads, new wipers — the wear and tear on your car from gig work is a legitimate business cost. If your car needs a repair and you use it for work, a portion of that repair is deductible." },
      { kind: "p", text: "Car insurance. If you use your personal vehicle for gig work, a portion of your insurance premium may be deductible, proportional to your business use of the vehicle." },
      { kind: "h3", text: "Phone and tools", id: "gig-phone-and-tools" },
      { kind: "p", text: "Your phone. You literally can't do gig work without your phone. The business-use portion of your phone bill — and potentially the cost of the phone itself if you bought it primarily for work — is deductible." },
      { kind: "p", text: "Phone accessories. A car mount for navigation, a charger cable, a wireless charger for between rides. These are small purchases, but they add up, and they're all deductible." },
      { kind: "h3", text: "Road and platform costs", id: "gig-road-and-platform-costs" },
      { kind: "p", text: "Tolls and parking. If you pay tolls during work trips or need to park while making a delivery, those costs are deductible. Save those receipts — they're easy to forget." },
      { kind: "p", text: "Bags, coolers, and equipment. DoorDash and Instacart drivers who buy insulated bags or equipment to do their jobs better can deduct those costs." },
      { kind: "p", text: "Platform fees and commissions. The percentage the platform takes from your earnings is also a deductible expense — it's a cost of doing business." },
      { kind: "h2", text: "Why Gig Workers Miss $500–$2,000 in Deductions Every Year", id: "why-gig-workers-miss-500-2-000-in-deductions-every-year" },
      { kind: "p", text: "Here's the honest answer: gig work is fast-paced and transactional. You're focused on the next ride, the next delivery, the next pickup. Stopping to track a receipt feels like friction in the middle of a busy day." },
      { kind: "p", text: "So receipts don't get kept. Small purchases get forgotten. By the end of the year, the only expenses most gig workers can document with certainty are the ones from their bank statements — and bank statements alone don't always have the detail the IRS needs." },
      { kind: "p", text: "The result? Conservative deductions. Larger tax bills. Money left behind." },
      { kind: "p", text: "According to tax professionals who work with gig economy workers, the average driver who actively tracks expenses claims $1,200 to $2,500 more in deductions than one who doesn't. At a 22% tax rate, that's $264 to $550 back in your pocket — just for keeping receipts." },
      { kind: "p", text: "The habit is worth building." },
      { kind: "h2", text: "How to Track Receipts Between Rides", id: "how-to-track-receipts-between-rides" },
      { kind: "p", text: "The key is making the habit fit into your workflow, not the other way around. Here's what works for drivers and delivery workers:" },
      { kind: "h3", text: "At the gas station", id: "gig-at-the-gas-station" },
      { kind: "p", text: "At the gas station: Before you pull back onto the road, open ReceiptCycle and snap the fuel receipt. It takes eight seconds. The app reads the amount, date, and vendor automatically and saves it to your expense log." },
      { kind: "h3", text: "After maintenance appointments", id: "gig-after-maintenance" },
      { kind: "p", text: "After maintenance appointments: When the mechanic hands you the receipt, scan it before you leave the parking lot. For larger expenses like an oil change or new tires, this is especially important — these are the deductions that make the biggest difference." },
      { kind: "h3", text: "For tolls", id: "gig-for-tolls" },
      { kind: "p", text: "For tolls: If you pay with cash, keep the ticket and scan it at the end of your shift. If you use an electronic toll account, you can download your statement monthly and forward the PDF to your ReceiptCycle account." },
      { kind: "h3", text: "For online purchases", id: "gig-for-online-purchases" },
      { kind: "p", text: "For online purchases: When you order supplies — bags, mounts, accessories — forward the email confirmation to your ReceiptCycle address and it's processed automatically." },
      { kind: "p", text: "The goal isn't perfection. It's consistency. A scan rate of 80–90% is dramatically better than the zero-percent approach most gig workers currently use." },
      { kind: "h2", text: "Setting Up a Weekly Expense Habit as a Driver", id: "setting-up-a-weekly-expense-habit-as-a-driver" },
      { kind: "p", text: "Daily scanning handles the capture. A weekly five-minute review handles the organization." },
      { kind: "p", text: "Pick a time — Sunday evening, Friday after your last shift, whenever works — and spend five minutes in the app. Check that the week's receipts were scanned correctly. Make sure the categories are right. Note any purchases you might have missed." },
      { kind: "p", text: "That's it. Five minutes a week keeps your records current and accurate all year, so January isn't a scramble." },
      { kind: "p", text: "At the end of the year, ReceiptCycle generates a complete expense report: every receipt, organized by category, with totals and subtotals. You hand it to your tax preparer — or use it yourself if you file independently — and you're done." },
      { kind: "h2", text: "How to Export Your Expenses for Tax Filing", id: "how-to-export-your-expenses-for-tax-filing" },
      { kind: "p", text: "When tax season arrives, you'll need to report your business income and deductions on Schedule C (if you're in the US). ReceiptCycle makes that straightforward." },
      { kind: "p", text: "From the app, select the date range for the tax year. Choose to export as a PDF (clean and readable, great for sharing with a tax preparer) or CSV (importable into spreadsheet software or tax tools). The report includes every expense, the category it belongs to, and the total by category — which maps directly to the line items on Schedule C." },
      { kind: "p", text: "If you work with a tax professional, you can share the report directly from the app. If you file yourself using software like TurboTax or H&R Block, the categorized totals give you exactly what you need to fill in each deduction line." },
      { kind: "h2", text: "FAQ: What If I Didn't Keep Receipts?", id: "faq-what-if-i-didn-t-keep-receipts" },
      { kind: "h3", text: "Do I need a receipt for every single deduction?", id: "do-i-need-a-receipt-for-every-single-deduction" },
      { kind: "p", text: "The IRS requires receipts for most business expenses, particularly those over $75. For smaller expenses, a contemporaneous record — a note in an app with the date, amount, and purpose — may be sufficient. That said, a receipt is always better than a note." },
      { kind: "h3", text: "What if I lost receipts from earlier this year?", id: "what-if-i-lost-receipts-from-earlier-this-year" },
      { kind: "p", text: "Start now. You can't recover receipts you've lost, but every receipt you capture from today forward counts. Even a partial year of organized records is significantly better than none — and it sets you up for a complete year next year." },
      { kind: "h3", text: "Can I deduct the mileage instead of actual car expenses?", id: "can-i-deduct-the-mileage-instead-of-actual-car-expenses" },
      { kind: "p", text: "Yes. The IRS offers a standard mileage rate as an alternative to tracking actual vehicle expenses. In 2024, that rate was 67 cents per mile for business driving. You can choose whichever method results in a larger deduction — but you can't use both. ReceiptCycle tracks your non-mileage expenses, so you can calculate both methods and pick the better one." },
      { kind: "h3", text: "What if I use my car for both work and personal trips?", id: "what-if-i-use-my-car-for-both-work-and-personal-trips" },
      { kind: "p", text: "Only the business-use percentage of vehicle expenses is deductible. If you use your car 60% for gig work and 40% personally, you can deduct 60% of eligible vehicle costs. Keep a mileage log alongside your receipts to support that calculation." },
      { kind: "h2", text: "Stop Leaving Money on the Road", id: "stop-leaving-money-on-the-road" },
      { kind: "p", text: "You work hard for every dollar you earn on the platform. It makes no sense to hand more of it back to the IRS than you're legally required to." },
      { kind: "p", text: "A simple receipt habit — ten seconds at the gas pump, five minutes on Sunday evening — can recover hundreds or thousands of dollars in deductions you're already entitled to. You just need the system to capture them." },
      { kind: "p", text: "ReceiptCycle is built for exactly this. Download it free, scan your next fuel receipt, and start the habit today." },
      { kind: "p", text: "The deductions are there. The only question is whether you have the receipts to claim them." },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Freelancer expense tracking guide", href: "/blog/freelancers-guide-tracking-business-expenses" },
          { label: "Go paperless with receipts", href: "/blog/go-paperless-with-receipts" },
          { label: "IRS mileage rates", href: "https://www.irs.gov/tax-professionals/standard-mileage-rates", external: true },
        ],
      },
    ],
  },
  
{
  slug: "scan-receipts-for-tax-refund",
  title: "How to Track Business Travel Expenses (And Actually Claim Everything You're Owed)",
  description:
    "Business travel has a way of generating expenses faster than you can track them. A cab to the airport. Breakfast at the hotel.",
  featuredImage: "/landing/feature-blog-scan-receipts-for-tax-refund.png?v=10",
  datePublished: "2026-04-12",
  dateModified: "2026-04-20",
  author: "Receipt Cycle Team",
  readMinutes: 11,
  tags: ["business travel", "expense tracking", "tax deductions", "receipts"],
  tldr: "A client dinner on the last night. Wi-Fi at the conference center. By the time you're back home and unpacked, the receipts are scattered across your wallet, your carry-on, and three different email inboxes.",
  body: [
    { kind: "p", text: "Business travel has a way of generating expenses faster than you can track them. A cab to the airport. Breakfast at the hotel." },
    { kind: "p", text: "A client dinner on the last night. Wi-Fi at the conference center. By the time you're back home and unpacked, the receipts are scattered across your wallet, your carry-on, and three different email inboxes." },
    { kind: "p", text: "Most business travellers claim the big-ticket items, flights and hotels, are hard to forget. But the smaller expenses? Those tend to disappear. And over a year of regular travel, that adds up to a lot of unclaimed money." },
    { kind: "p", text: "This guide walks you through exactly what qualifies as a deductible travel expense, how to build a capture system that works while you're on the road, and how ReceiptCycle keeps everything organised so you can claim every dollar when you get back." },
    { kind: "p", text: "What Counts as a Deductible Business Travel Expense?" },
    { kind: "p", text: "The IRS defines deductible travel expenses as costs that are ordinary, necessary, and incurred away from your tax home while doing business. In plain terms: if you travelled for work and paid for something to make that trip happen, it probably qualifies." },
    { kind: "p", text: "Here's what to track on every business trip:" },
    { kind: "p", text: "Transportation. Flights, trains, rental cars, taxis, rideshares, and public transit all count. So does driving your own car — you can deduct the business mileage using the standard IRS rate (67 cents per mile in 2024) or your actual vehicle costs." },
    { kind: "p", text: "Accommodation. Hotel rooms, Airbnbs, and other lodging for the business portion of your trip are fully deductible. If you extend a trip for personal reasons, only the business nights count." },
    { kind: "p", text: "Meals. Business meals are generally 50% deductible. That applies whether you're eating alone while travelling or taking a client to dinner. Keep the receipt and note the business purpose." },
    { kind: "p", text: "Tips and incidentals. Tips for hotel staff, bellhops, and other service workers during a business trip are deductible as part of the per diem. Small as they are, they're worth tracking." },
    { kind: "p", text: "Business communication. Wi-Fi fees at hotels and airports, international calling charges, and work-related calls made while travelling are deductible." },
    { kind: "p", text: "Baggage fees. If you checked bags for a business trip, those fees count. Keep the airline receipt or include it in your ticket documentation." },
    { kind: "p", text: "Laundry and dry cleaning. On longer business trips, cleaning expenses are deductible. It's easy to forget, but it's right there in IRS Publication 463." },
    { kind: "p", text: "Why Business Travellers Leave So Much Money Behind" },
    { kind: "p", text: "Here's the pattern that plays out for most frequent travellers. You're efficient at booking flights and hotels because those get expensed to a corporate card or reimbursed by a client." },
    { kind: "p", text: "But the dozens of smaller transactions, the coffee before a morning presentation, the parking garage, the rideshare to the venue, those happen in cash or on a personal card and never make it into an expense report." },
    { kind: "p", text: "At $20 to $40 a day in miscellaneous travel expenses, someone who takes twenty trips a year could be leaving $400 to $800 in deductions on the table annually. More, if they're missing some of the larger incidentals." },
    { kind: "p", text: "The solution isn't more discipline. It's a better system. And the best system is the one that works where you actually are: on the road, between meetings, at the gate." },
    { kind: "p", text: "How to Capture Receipts While Travelling" },
    { kind: "p", text: "ReceiptCycle is designed to work in exactly this environment. Here's how to use it on the road:" },
    { kind: "p", text: "At the airport: Grab your coffee, scan the receipt before you put your card away. Thirty seconds at the counter." },
    { kind: "p", text: "At check-in: When the hotel hands you a receipt for incidentals, scan it at the front desk. Don't wait until checkout — that's when things get lost." },
    { kind: "p", text: "After meals: Scan the restaurant receipt while your dining companion is signing theirs. It feels natural, takes ten seconds, and means you never fish through pockets for a diner receipt three weeks later." },
    { kind: "p", text: "For email receipts: Flight confirmations, hotel bookings, car rental agreements — forward them to your ReceiptCycle address the moment they arrive. They're processed automatically." },
    { kind: "p", text: "At checkout: Before you leave the hotel, scan the final itemised folio. That one document often captures room charges, parking, room service, and incidentals all in one place." },
    { kind: "p", text: "Mixing Business and Personal Travel: What the Rules Say" },
    { kind: "p", text: "A lot of business travellers extend a work trip for a personal weekend, or build a conference into a longer vacation. That's completely legitimate. It just means you need to be clear about what's what." },
    { kind: "p", text: "The general rule: you can deduct the expenses directly tied to the business portion of the trip. Transportation costs — flights, for example — can sometimes be fully deductible even if you stayed on longer for personal reasons, as long as the primary purpose of the trip was business. Accommodation and meals for the personal days are not deductible." },
    { kind: "p", text: "The best approach is to track everything and let your accountant decide on mixed-purpose items. ReceiptCycle lets you tag expenses with short notes — a few words about the business purpose takes five seconds and protects you completely if you're ever questioned." },
    { kind: "p", text: "Building Your Travel Expense Report in ReceiptCycle" },
    { kind: "p", text: "When you get home from a trip, the last thing you want is to spend an evening sorting receipts. With ReceiptCycle, you don't have to." },
    { kind: "p", text: "Everything you scanned on the road is already organised by date, vendor, and category. To build a trip expense report:" },
    { kind: "p", text: "Open ReceiptCycle and filter by the travel dates." },
    { kind: "p", text: "Review the expenses and confirm the categories are correct." },
    { kind: "p", text: "Export as a PDF or CSV, labelled by trip name or date range." },
    { kind: "p", text: "If you're submitting for reimbursement, you have a clean professional report with receipt images attached. If you're filing independently, you have exactly what you need for Schedule C. The whole post-trip review takes ten to fifteen minutes." },
    { kind: "p", text: "Don't Leave Your Travel Deductions at the Hotel" },
    { kind: "p", text: "Business travel is expensive. You're already making the investment. The deductions exist specifically to offset that cost — but only if you document them." },
    { kind: "p", text: "Frequent travelers who build a consistent receipt habit with ReceiptCycle recover hundreds or thousands of dollars they would otherwise miss. Not through any complicated tax strategy. Just by capturing what they're already spending." },
    { kind: "p", text: "Start your next trip ready. Download ReceiptCycle free, scan your first travel receipt, and build the habit that pays you back every time you file." },
  ],
},
  
{
  slug: "best-expense-tracker-for-freelancers",
  title: "How to Organize Receipts for Your Accountant (And Make Tax Season Painless)",
  description:
    "There's a moment most people dread every year: the call from their accountant asking for expense documentation, followed by a frantic search through bags, email, and folders.",
  featuredImage: "/landing/feature-blog-best-expense-tracker-for-freelancers.png?v=10",
  datePublished: "2026-04-14",
  dateModified: "2026-04-20",
  author: "Receipt Cycle Team",
  readMinutes: 12,
  tags: ["accountant handoff", "tax prep", "receipt organization", "audit prep"],
  tldr: "Your accountant charges by the hour. Disorganised records mean more time spent sorting through what you've given them and a larger bill at the end.",
  body: [
    { kind: "p", text: "There's a moment most people dread every year: the call from their accountant asking for expense documentation. Suddenly, you're rifling through bags, checking email folders, and trying to remember whether you actually kept the receipt for that hotel stay or just meant to." },
    { kind: "p", text: "Your accountant charges by the hour. Disorganised records mean more time spent sorting through what you've given them and a larger bill at the end." },
    { kind: "p", text: "Even if your accountant doesn't charge extra, arriving unprepared means a longer meeting, more back-and-forth, and the real possibility that some legitimate deductions simply don't make it into your return because the documentation can't be found in time." },
    { kind: "p", text: "The good news is that being the client who arrives with everything organized is much simpler than it sounds. Here's exactly how to do it." },
    { kind: "p", text: "What Your Accountant Actually Needs From You" },
    { kind: "p", text: "Before you can organize your receipts well, it helps to understand what your accountant is working with and what makes their job and yours easier." },
    { kind: "p", text: "Your accountant needs to match your claimed deductions to documented evidence. For each expense you want to deduct, they need to see:" },
    { kind: "p", text: "The amount paid" },
    { kind: "p", text: "The date of the transaction" },
    { kind: "p", text: "The vendor or payee" },
    { kind: "p", text: "The business purpose of the expense" },
    { kind: "p", text: "A clear receipt, physical or digital, covers the first three automatically. The business purpose is the one thing you need to note for yourself, particularly for meals, travel, and purchases that could be interpreted as personal." },
    { kind: "p", text: "Beyond individual receipts, your accountant benefits from a summary: total spending by category, so they can see at a glance how much you're claiming for office supplies, travel, meals, software, and so on." },
    { kind: "p", text: "That summary, cross-referenced with your receipt images, is everything they need." },
    { kind: "p", text: "ReceiptCycle generates both the categorised expense report and the attached receipt images in one export." },
    { kind: "p", text: "The Five Categories That Matter Most at Tax Time" },
    { kind: "p", text: "Not all expenses are created equal when it comes to audit risk and documentation requirements. Here are the five categories your accountant pays most attention to, and what to keep for each:" },
    { kind: "p", text: "Meals and entertainment. These get scrutiny because they're easy to abuse. For every meal you claim, keep the receipt and note who you met with and the business purpose \"lunch with potential client to discuss project proposal\" takes ten seconds to write and makes the deduction airtight." },
    { kind: "p", text: "Travel. Flights and hotels have clear documentation (booking confirmations, folios). The gaps are usually ground transport, meals on the road, and incidentals. Keep all of them. ReceiptCycle lets you tag expenses to a specific trip, which makes travel reporting especially clean." },
    { kind: "p", text: "Home office. If you work from home, you need to document your home office space, typically a floor plan or measurement showing the dedicated work area, along with receipts for rent/mortgage interest, utilities, and internet. Your accountant will calculate the deductible proportion." },
    { kind: "p", text: "Equipment and technology. Large purchases of laptops, cameras, and furniture may be deducted in full in the year of purchase (Section 179) or depreciated over time. Either way, your accountant needs the receipt showing the exact amount and date." },
    { kind: "p", text: "Professional services. Payments to contractors, legal fees, accounting fees, and other professional services are deductible. Keep invoices and payment confirmations for all of them." },
    { kind: "p", text: "How to Organize Before You Hand Things Over" },
    { kind: "p", text: "Handing your accountant a folder of unsorted receipts is the equivalent of handing someone a puzzle without the box; technically, all the pieces are there, but the work to make sense of it is entirely theirs." },
    { kind: "p", text: "A much better approach and one your accountant will genuinely appreciate — is to arrive with your expenses pre-sorted by category, with a summary total for each one." },
    { kind: "p", text: "Here's the system that works best:" },
    { kind: "p", text: "Throughout the year: Scan every receipt into ReceiptCycle at the moment of purchase. The app auto-categorises them and builds your record in real time." },
    { kind: "p", text: "Monthly: Spend five minutes reviewing the month's expenses. Check that categories are correct. Add a note to any meal or entertainment expense explaining the business purpose." },
    { kind: "p", text: "Before your accountant meeting: Export your ReceiptCycle report for the year. The export includes a category summary with totals, plus all receipt images organised by category and date. That's the document you share with your accountant either as a PDF or a CSV, they can import directly." },
    { kind: "p", text: "The result is a meeting that starts with your accountant already having the full picture, rather than one that begins with them asking where things are." },
    { kind: "p", text: "What to Do If Your Records Are Incomplete" },
    { kind: "p", text: "Maybe you didn't track well this year. Maybe you're reading this in March with a filing deadline approaching and a shoebox of unsorted receipts on your desk. It happens." },
    { kind: "p", text: "Here's how to salvage the situation:" },
    { kind: "p", text: "Start with your bank and credit card statements. These give you a complete transaction record date, vendor, and amount. They're not receipts, but they're a starting point for reconstructing your expense history." },
    { kind: "p", text: "Go through each statement line by line. Flag every transaction that was a business expense. For each one, ask yourself: do I have a receipt? If yes, scan it and add it to ReceiptCycle. If no, make a note of the expense with as much detail as you can recall." },
    { kind: "p", text: "Check your email. A large portion of business expenses software subscriptions, online orders, travel bookings generate email confirmations. Search your inbox for common vendors and forward those confirmations to your ReceiptCycle address." },
    { kind: "p", text: "Be honest with your accountant. For expenses where you genuinely have no documentation, let your accountant know. They can advise on what's still claimable and what isn't, and help you decide whether to include borderline items." },
    { kind: "p", text: "It's always better to have that conversation up front than to file a claim you can't support." },
    { kind: "p", text: "Going forward, starting ReceiptCycle today, even mid-year means the second half of the year is fully documented, and next year's filing conversation is a completely different experience." },
    { kind: "p", text: "How ReceiptCycle Makes the Handover Seamless" },
    { kind: "p", text: "The most appreciated thing you can do for your accountant is give them less work, not more." },
    { kind: "p", text: "ReceiptCycle is designed specifically for this. Here's what your accountant gets when you use it:" },
    { kind: "p", text: "A complete expense report organized by category, covering any date range you choose" },
    { kind: "p", text: "Total spending per category, ready to map to your tax return line items" },
    { kind: "p", text: "Individual receipt images attached to each transaction, so every claim is backed by documentation" },
    { kind: "p", text: "Export options in PDF (easy to share and read) or CSV (importable into any accounting or tax software)" },
    { kind: "p", text: "You can share the report directly from the app — email it, share a link, or download it to send however you prefer. Some ReceiptCycle users simply give their accountant direct read access to their account, so the accountant can pull what they need without any back-and-forth at all." },
    { kind: "p", text: "The Preparation That Changes Everything" },
    { kind: "p", text: "Tax time doesn't have to be stressful. It doesn't have to mean a frantic search for missing receipts or a conversation with your accountant that starts with apologies." },
    { kind: "p", text: "The preparation that changes everything is simple: scan as you go, review briefly each month, and let ReceiptCycle build the organized record your accountant needs throughout the year." },
    { kind: "p", text: "By the time your filing deadline arrives, everything is ready. The meeting is short. The documentation is complete. And your accountant can focus on finding deductions rather than chasing evidence." },
    { kind: "p", text: "Try ReceiptCycle free and see how different next tax season can feel. Your accountant and your bank account will thank you." },
  ],
},
  
{
  slug: "catch-subscription-creep",
  title: "Self-Employed Tax Deductions Most People Miss (And How to Claim Them)",
  description:
    "If you work for yourself, tax time is different from employment: no automatic summary, no perfect withholding, and every deduction must be found, documented, and claimed.",
  featuredImage: "/landing/feature-blog-catch-subscription-creep.png?v=10",
  datePublished: "2026-04-16",
  dateModified: "2026-04-20",
  author: "Receipt Cycle Team",
  readMinutes: 12,
  tags: ["self-employed", "tax deductions", "schedule c", "expenses"],
  tldr: "Most self-employed people get the obvious ones. They deduct their home office. They claim their mileage. They remember the big software subscriptions.",
  body: [
    { kind: "p", text: "If you work for yourself, you already know that tax time feels different from when you had an employer. No one sends you a neat summary at the end of the year. No one withholds the right amount throughout. Every deduction is your responsibility to find, document, and claim." },
    { kind: "p", text: "Most self-employed people get the obvious ones. They deduct their home office. They claim their mileage. They remember the big software subscriptions." },
    { kind: "p", text: "But there's a second layer of deductions that most people leave behind not because the deductions don't exist, but because no one told them, or the expense felt too small to bother tracking, or the receipt simply wasn't kept." },
    { kind: "p", text: "This guide covers the deductions that consistently go unclaimed, explains exactly what qualifies, and shows you how ReceiptCycle makes sure you never miss one again." },
    { kind: "p", text: "The Deductions You Probably Already Know" },
    { kind: "p", text: "Let's start with the foundation the commonly claimed deductions so you can check them off and focus on what you're actually missing." },
    { kind: "p", text: "Home office: If you use a portion of your home exclusively and regularly for business, you can deduct a proportional share of rent or mortgage interest, utilities, and internet. The space must be dedicated to work a desk in the corner of your bedroom typically doesn't qualify, but a spare room used as an office usually does." },
    { kind: "p", text: "Mileage: If you drive for business to meet clients, run work errands, or attend professional events, you can deduct those miles. Keep a log of business trips with dates, destinations, and purposes." },
    { kind: "p", text: "Software and apps: Any subscription or tool you use to run your business is deductible. This is one thing people do claim, though they often miss smaller subscriptions they set up and forgot about." },
    { kind: "p", text: "Got those? Good. Here's what most self-employed people miss." },
    { kind: "p", text: "The Deductions Most People Leave Behind" },
    { kind: "p", text: "Your health insurance premiums. Self-employed individuals can deduct 100% of health, dental, and vision insurance premiums for themselves and their families as an adjustment to income, not just an itemised deduction." },
    { kind: "p", text: "This is one of the most valuable deductions available to the self-employed, and it's frequently overlooked because it lives on a different line of your tax return than other business expenses." },
    { kind: "p", text: "Retirement contributions. Contributions to a SEP-IRA, Solo 401(k), or SIMPLE IRA are fully deductible, up to the annual limits. In 2024, you could contribute up to $69,000 to a SEP-IRA as a self-employed person." },
    { kind: "p", text: "If you're not taking advantage of this, you're leaving a substantial deduction on the table and missing the investment growth that comes with it." },
    { kind: "p", text: "Professional development. Books, online courses, workshops, conference tickets, and industry membership fees are all deductible. If you spent $300 on courses to sharpen your skills this year, that $300 should be in your expense log." },
    { kind: "p", text: "Part of your phone bill. Most self-employed people know their phone is deductible in principle, but few actually calculate the business-use percentage and apply it." },
    { kind: "p", text: "If you use your phone 70% for work, 70% of your monthly bill is deductible, including the portion of the phone's purchase price if you bought it primarily for business." },
    { kind: "p", text: "Bank fees and transaction costs. Monthly fees on your business bank account, payment processing fees from Stripe or PayPal, and wire transfer costs are all deductible operating expenses." },
    { kind: "p", text: "They're small individually but consistent, which means they add up meaningfully across a year." },
    { kind: "p", text: "Professional liability insurance. If you carry errors and omissions insurance, general liability, or any other professional coverage, the premiums are fully deductible. Many self-employed professionals pay for this and never think to claim it." },
    { kind: "p", text: "Advertising and marketing. Website hosting, domain registration, paid advertising, social media tools, email marketing platforms, business cards, and any other costs tied to promoting your services are all deductible." },
    { kind: "p", text: "Track every marketing-related expense separately, it's a category that often gets lumped in with \"miscellaneous\" and undercounted." },
    { kind: "p", text: "Client gifts. You can deduct up to $25 per client per year in business gifts. Keep the receipt and note who the gift was for. It's a small category, but worth capturing if you regularly send thank-you gifts or holiday presents to clients." },
    { kind: "p", text: "Why These Deductions Go Unclaimed" },
    { kind: "p", text: "The pattern behind most missed deductions is the same: the expense happens, no receipt is kept, and by the time you're filing your taxes, there's no documentation to support the claim." },
    { kind: "p", text: "Health insurance premiums are often forgotten because they're automatic — they're deducted from an account or charged to a card, and it doesn't feel like a business expense even though it legally is." },
    { kind: "p", text: "Small recurring charges, such as bank fees, software subscriptions, and marketing tools, are easy to overlook because no single charge feels significant. But a $10 monthly fee across twelve months is $120." },
    { kind: "p", text: "Fifteen of those, and you've got $1,800 in deductions that passed through your account without being captured." },
    { kind: "p", text: "Professional development expenses often go untracked because they feel personal: \"I bought that book because I was interested in it\", even when the content directly supports your work." },
    { kind: "p", text: "The fix is simple: treat everything you spend in connection with your business as a potential deduction, and scan the receipt." },
    { kind: "p", text: "Let ReceiptCycle categorise it and build the record. At year's end, you review what's there with your accountant if you work with one and claim what qualifies." },
    { kind: "p", text: "How to Use ReceiptCycle to Capture These Specific Categories" },
    { kind: "p", text: "Setting up ReceiptCycle for the deductions above is straightforward. The key is using consistent category labels so your year-end report maps cleanly to your tax return." },
    { kind: "p", text: "Here's a simple category structure that works well for self-employed people:" },
    { kind: "p", text: "Health & Insurance — health premiums, professional liability, business insurance" },
    { kind: "p", text: "Professional Development — books, courses, conference tickets, memberships" },
    { kind: "p", text: "Marketing & Advertising — website costs, ads, tools, business cards" },
    { kind: "p", text: "Phone & Internet — monthly bills, the business-use portion of your phone" },
    { kind: "p", text: "Banking & Fees — account fees, processing fees, transfer costs" },
    { kind: "p", text: "Retirement — contributions to self-employed retirement accounts" },
    { kind: "p", text: "Client Relations — gifts, meals with clients, entertainment" },
    { kind: "p", text: "For recurring charges, monthly subscriptions, insurance premiums, and bank fees, set a reminder to forward the statement or email confirmation to your ReceiptCycle address at the start of each month." },
    { kind: "p", text: "It takes thirty seconds and keeps the record complete without requiring you to remember it manually every time." },
    { kind: "p", text: "The Deduction You're Most Likely Missing Right Now" },
    { kind: "p", text: "If you want to identify your biggest gap quickly, look at your bank and credit card statements from the last three months. Go line by line and ask: Did I capture this in my expense tracking?" },
    { kind: "p", text: "Most self-employed people find at least three to five categories of expenses they've been consistently missing." },
    { kind: "p", text: "Common culprits: monthly software charges that auto-renew, professional association fees charged once a year, and irregular expenses like the industry event they attended in the spring." },
    { kind: "p", text: "Add those categories to ReceiptCycle, scan any documentation you can still find for recent transactions, and go forward with a complete system." },
    { kind: "p", text: "Every Dollar You Claim Is a Dollar You Earned" },
    { kind: "p", text: "There's nothing aggressive about claiming deductions you're legally entitled to. These deductions exist precisely because the government recognizes that earning money costs money, and self-employed people shouldn't be taxed on every dollar before accounting for legitimate business costs." },
    { kind: "p", text: "The only thing standing between you and your full refund is documentation. ReceiptCycle handles that part." },
    { kind: "p", text: "Download it free, set up your categories, and start building the record that gets you every deduction you've earned." },
    { kind: "p", text: "You worked for that money. Make sure you keep as much of it as the law allows." },
  ],
},
  
{
  slug: "import-bank-statements-expense-tracking",
  title: "How to Manage Receipts as a Side Hustler (Without It Taking Over Your Life)",
  description:
    "Running a side hustle is exciting. You're building something on your own terms, earning extra income, and developing skills that belong entirely to you.",
  featuredImage: "/landing/feature-blog-import-bank-statements-expense-tracking.png?v=10",
  datePublished: "2026-04-18",
  dateModified: "2026-04-20",
  author: "Receipt Cycle Team",
  readMinutes: 12,
  tags: ["side hustle", "expense tracking", "self-employment tax", "receipts"],
  tldr: "What's less exciting is the moment you realize that a side hustle also means side hustle taxes and that you're responsible for tracking every expense that goes into it.",
  body: [
    { kind: "p", text: "Running a side hustle is exciting. You're building something on your own terms, earning extra income, and developing skills that belong entirely to you." },
    { kind: "p", text: "What's less exciting is the moment you realize that a side hustle also means side hustle taxes and that you're responsible for tracking every expense that goes into it." },
    { kind: "p", text: "The good news is that your side hustle spending creates real deductions. The tools you buy, the courses you take, and the services you use to run your business are all potentially deductible against your side income, which means a smaller tax bill at the end of the year." },
    { kind: "p", text: "The not-so-good news is that most side hustlers don't track these expenses because it feels like overhead for something that's supposed to be simple. So the deductions go unclaimed, and the tax bill stays higher than it needs to be." },
    { kind: "p", text: "This guide is for anyone running a side hustle alongside a day job, selling on Etsy, doing freelance design, tutoring, coaching, creating content, or any of the dozens of other ways people earn money outside their primary employment. Here's how to manage your receipts without turning it into a second job." },
    { kind: "p", text: "Why Side Hustle Taxes Are Different" },
    { kind: "p", text: "When you earn side income, whether it's $2,000 or $20,000, that income is typically reported as self-employment earnings. In the US, that means Schedule C." },
    { kind: "p", text: "In the UK, that means self-assessment. In both cases, you're allowed to deduct the legitimate business expenses you incurred to earn that income." },
    { kind: "p", text: "Here's why this matters more for side hustlers than it might seem. Self-employment income is taxed at your marginal rate plus self-employment tax, which covers Social Security and Medicare contributions that an employer would normally split with you. That rate adds up. Good expense tracking is one of the most direct tools you have to reduce it." },
    { kind: "p", text: "And unlike a full-time business where thousands of dollars flow through the books, a side hustle might have $3,000 to $8,000 in annual expenses that are 100% legitimate and 100% claimable if you tracked them." },
    { kind: "p", text: "What Side Hustlers Can Actually Deduct" },
    { kind: "p", text: "The range of deductible expenses depends on your specific hustle, but here are the categories that apply broadly:" },
    { kind: "p", text: "Platforms and marketplace fees. Etsy listing fees, eBay selling fees, Fiverr commissions, Upwork service fees, and every percentage the platform takes from your earnings are a deductible cost of doing business." },
    { kind: "p", text: "Supplies and materials. If you make things crafts, art, physical products the materials you buy are deductible. Every supply run, every raw material purchase, every tool that goes into what you create." },
    { kind: "p", text: "Software and digital tools. Design software, video editing tools, scheduling apps, email marketing platforms, website themes, domain registration if you use it for your hustle, it's a deductible expense." },
    { kind: "p", text: "Shipping and packaging. If you sell and ship physical goods, postage, boxes, bubble wrap, tape, and labels are all deductible. These small expenses add up fast for product-based businesses." },
    { kind: "p", text: "Home office. If you have a dedicated space where you work on your side hustle, you can claim home office expenses proportional to that space. Same rules as full-time self-employment." },
    { kind: "p", text: "Equipment. A camera for content creation. A ring light. A sewing machine for a craft business. A microphone for a podcast. If you bought it for the hustle, it qualifies." },
    { kind: "p", text: "Courses and education. If you invested in skills that directly relate to your side income, such as photography courses for a photography side hustle, marketing courses to grow your audience, those are deductible professional development expenses." },
    { kind: "p", text: "Your phone and internet. The business-use portion of your phone and internet bill is deductible, just like it is for full-time self-employed people." },
    { kind: "p", text: "The Mistake Most Side Hustlers Make" },
    { kind: "p", text: "Here's what usually happens." },
    { kind: "p", text: "A side hustler launches their business with enthusiasm. They buy some tools. They subscribe to a platform. They take a course. They buy supplies. None of this is tracked because it all feels informal; they're not running a \"real\" business yet." },
    { kind: "p", text: "By the time tax season arrives, they have their income from 1099s or payment summaries. But their expenses? Incomplete at best. They try to recall what they spent, check a few bank statements, and end up filing with maybe half of what they could have claimed." },
    { kind: "p", text: "The cost of that gap depends on the tax rate, but at 22% federal plus 15.3% self-employment tax, every $1,000 in missed deductions costs roughly $370. For a side hustler who consistently misses $3,000 to $5,000 in expenses year after year, that's $1,100 to $1,850 in unnecessary tax every single year." },
    { kind: "p", text: "The frustrating part is that the spending already happened. The only thing missing is the record." },
    { kind: "p", text: "A Simple Receipt System Built for Side Hustlers" },
    { kind: "p", text: "The system you need isn't complicated. It needs to be fast, consistent, and low-maintenance because your time is already split between a day job and the hustle itself." },
    { kind: "p", text: "Here's what works:" },
    { kind: "p", text: "Scan everything the moment you buy it. Supplies, tools, software purchases, shipping costs open ReceiptCycle, snap a photo, done. Ten seconds. The app reads the receipt and files it automatically." },
    { kind: "p", text: "Forward digital receipts immediately. For platform fees, software subscriptions, and online purchases, forward the email confirmation to your ReceiptCycle address the moment it arrives. It takes three seconds and you never have to find that email again." },
    { kind: "p", text: "Keep a simple category structure. You don't need dozens of categories. Something like: Supplies, Software, Shipping, Marketing, Education, Equipment, and Fees. ReceiptCycle auto-assigns most expenses you just review occasionally to make sure they landed in the right place." },
    { kind: "p", text: "Do a monthly five-minute check-in. At the end of each month, open the app and scroll through what you captured. Check the categories. Add a note to anything that needs context. Five minutes a month is all it takes to stay completely organized." },
    { kind: "p", text: "Export at tax time. When you're ready to file, pull a year-end report from ReceiptCycle. It gives you total expenses by category, with all receipt images attached. Hand it to a tax preparer or use it yourself everything you need is already organized." },
    { kind: "p", text: "What About Separating Side Hustle and Personal Expenses?" },
    { kind: "p", text: "This is the question most side hustlers ask. The honest answer: a dedicated business account or card makes life significantly easier, but it's not strictly required." },
    { kind: "p", text: "If you use a personal account for everything, you can still track side hustle expenses in ReceiptCycle you just need to be more deliberate about scanning receipts for business purchases and leaving personal ones unscanned." },
    { kind: "p", text: "The cleaner approach is a separate debit card or account for side hustle spending. It costs nothing to open a basic account, and it means every transaction on that card is a business expense by definition. Your records are cleaner, audits are simpler, and the mental overhead of sorting personal from professional disappears entirely." },
    { kind: "p", text: "The Side Hustle That Pays You Twice" },
    { kind: "p", text: "Here's the way to think about it. Your side hustle pays you once when the client pays the invoice or the product sells. It pays you again when the deductions you tracked reduce your tax bill." },
    { kind: "p", text: "The second payment is already sitting there, waiting. You just need the documentation to collect it." },
    { kind: "p", text: "ReceiptCycle is built for exactly this a lightweight, fast, and organized receipt system that works alongside a busy life. Download it free, scan your first side hustle expense, and make sure you're getting paid everything your hustle earns you." },
    { kind: "p", text: "Your side hustle is working. Make sure your expense tracking is working just as hard." },
  ],
},
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
