/**
 * Blog posts imported from user-provided DOCX content.
 */
export type BlogBlock =
  | { kind: "p"; text: string }
  | { kind: "h2"; text: string; id: string }
  | { kind: "h3"; text: string; id: string }
  | { kind: "links"; title: string; items: Array<{ label: string; href: string; external?: boolean }> }
  | { kind: "ul"; items: string[] }
  | { kind: "ol"; items: string[] }
  | { kind: "quote"; text: string; cite?: string }
  | { kind: "callout"; title: string; text: string };

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  featuredImage: string;
  datePublished: string;
  dateModified: string;
  author: string;
  readMinutes: number;
  tags: string[];
  tldr: string;
  body: BlogBlock[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "maximize-tax-refund-by-scanning-receipts",
    title: "How to Maximize Your Tax Refund by Scanning Receipts",
    description: "Most people miss tax deductions because they lose receipts. This guide shows how to scan once, store digitally, and claim every legitimate expense with confidence.",
    featuredImage: "/landing/feature-blog-maximize-tax-refund-by-scanning-receipts.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 9,
    tags: ["tax refund", "receipt scanning", "freelancer", "audit", "bookkeeping"],
    tldr: "Every year, millions of people leave money on the table at tax time, not because they didn't spend on legitimate deductions, but because they lost the receipts to prove it.",
    body: [
      { kind: "p", text: "Every year, millions of people leave money on the table at tax time, not because they didn't spend on legitimate deductions, but because they lost the receipts to prove it." },
      { kind: "p", text: "A crumpled coffee receipt here. A faded pharmacy slip there. A work dinner you're almost sure you paid for but can't confirm. Before you know it, you've handed back hundreds, sometimes thousands, of dollars that were rightfully yours to claim." },
      { kind: "p", text: "The good news? Keeping your receipts no longer means stuffing a shoebox under your desk and hoping for the best." },
      { kind: "h2", text: "Why Most People Leave Money on the Table", id: "why-most-people-leave-money-on-the-table" },
      { kind: "p", text: "Here's the honest truth: most people don't miss deductions because they're careless. They miss them because managing paper receipts is genuinely inconvenient. Ink fades. Paper tears. You're in a rush at checkout, and the receipt ends up at the bottom of your bag." },
      { kind: "p", text: "By the time tax season rolls around, that evidence is gone and so is your refund." },
      { kind: "p", text: "The IRS and most tax authorities don't require you to keep paper copies of receipts. Digital records are fully accepted, as long as they clearly show the vendor, amount, date, and nature of the expense. That changes everything. Because scanning receipts the moment you get them is quick, easy, and permanent." },
      { kind: "h2", text: "What Actually Qualifies as a Tax Deduction?", id: "what-actually-qualifies-as-a-tax-deduction" },
      { kind: "p", text: "Before you start scanning, it helps to know what you're looking for. The list of qualifying deductions is longer than most people realize." },
      { kind: "h3", text: "If you're self-employed or run a small business", id: "self-employed-small-business-deductions" },
      {
        kind: "ul",
        items: [
          "Office supplies and equipment",
          "Software subscriptions used for work",
          "Business travel — flights, hotels, transport",
          "Client meals (typically 50% deductible)",
          "Home office expenses",
          "Phone and internet (the portion used for business)",
          "Professional development and courses",
        ],
      },
      { kind: "h3", text: "If you're an employee", id: "employee-deductions" },
      {
        kind: "ul",
        items: [
          "Unreimbursed work expenses (depending on your country and situation)",
          "Charitable donations",
          "Medical expenses above a certain threshold",
          "Childcare costs in some circumstances",
        ],
      },
      { kind: "p", text: "The rule of thumb is simple: if you spent money to earn money, or to support a legitimate life expense your tax authority recognizes, it's worth tracking. A receipt scanner turns that rule into a habit." },
      { kind: "h2", text: "The Problem With Paper Receipts", id: "the-problem-with-paper-receipts" },
      { kind: "p", text: "Think about the last time you actually filed all your receipts properly. For most people, the honest answer involves a pile on the kitchen counter, a few in the car glove compartment, and a vague memory of \"I think I kept that one.\"" },
      { kind: "p", text: "Paper receipts are designed to be temporary. Thermal paper — the shiny kind most retailers use — fades within months. Humidity, heat, and friction accelerate that process. By the time your accountant needs to see documentation, the receipt you held onto is often unreadable." },
      { kind: "p", text: "There's also the time problem. Manually entering expense data into a spreadsheet, or sorting through months of paper before a filing deadline, costs you hours you don't have." },
      { kind: "p", text: "Scanning receipts solves both problems at once." },
      { kind: "h2", text: "How Scanning Receipts With ReceiptCycle Works", id: "how-scanning-receipts-with-receiptcycle-works" },
      { kind: "p", text: "ReceiptCycle is built around one simple idea: scan once, claim your refund." },
      { kind: "p", text: "Here's how it works in practice:" },
      { kind: "p", text: "You get a receipt — at a restaurant, a store, a gas station, anywhere." },
      { kind: "p", text: "You open ReceiptCycle and snap a photo — it takes about ten seconds." },
      { kind: "p", text: "The app reads the receipt automatically — pulling out the vendor name, date, amount, and category using AI." },
      { kind: "p", text: "Your expense is stored securely in the cloud — organized, searchable, and ready whenever you need it." },
      { kind: "p", text: "That's it. No spreadsheets. No shoeboxes. No frantic searching the night before your accountant meeting." },
      { kind: "p", text: "At the end of the tax year, you have a clean, categorized record of every deductible expense you captured throughout the year. You can export it, share it, or hand it straight to your accountant." },
      { kind: "h2", text: "FAQ: Common Questions About Digital Receipts and Taxes", id: "faq-common-questions-about-digital-receipts-and-taxes" },
      { kind: "h3", text: "Do digital receipts count for tax purposes?", id: "do-digital-receipts-count-for-tax-purposes" },
      { kind: "p", text: "Yes. The IRS and most tax authorities worldwide accept digital images of receipts as valid documentation, provided the image clearly shows the relevant details. ReceiptCycle stores high-quality scans that meet this standard." },
      { kind: "h3", text: "How long do I need to keep my receipts?", id: "how-long-do-i-need-to-keep-my-receipts" },
      { kind: "p", text: "The IRS recommends keeping records for at least three years from the date you filed your return, though six years is safer if there's any chance you underreported income. ReceiptCycle stores your scans indefinitely in secure cloud storage." },
      { kind: "h3", text: "What if I lose my phone?", id: "what-if-i-lose-my-phone" },
      { kind: "p", text: "Your receipts are backed up to the cloud, not stored locally on your device. If you lose your phone, your records are completely safe." },
      { kind: "h3", text: "Do I need receipts for small purchases?", id: "do-i-need-receipts-for-small-purchases" },
      { kind: "p", text: "The IRS generally requires receipts for business expenses over $75, but keeping records of smaller amounts is a good habit — they add up faster than you think." },
      { kind: "h2", text: "Start Small, Win Big", id: "start-small-win-big" },
      { kind: "p", text: "You don't need to overhaul your entire financial system to start seeing results. The simplest shift you can make is this: the next time you get a receipt, scan it before you pocket it." },
      { kind: "p", text: "That one habit — repeated consistently — adds up to a more complete tax return, a bigger refund, and a lot less stress every April." },
      { kind: "p", text: "ReceiptCycle makes it easy to start. Scan your first receipt free and see how simple organized expenses can be." },
      { kind: "p", text: "Your refund is waiting. You just need to keep the evidence." },
      {
        kind: "links",
        title: "Helpful resources",
        items: [
          { label: "How to go paperless with receipts", href: "/blog/go-paperless-with-receipts" },
          { label: "Freelancer expense tracking guide", href: "/blog/freelancers-guide-tracking-business-expenses" },
          { label: "IRS recordkeeping overview", href: "https://www.irs.gov/businesses/small-businesses-self-employed/what-kind-of-records-should-i-keep", external: true },
        ],
      },
    ],
  },
  {
    slug: "best-receipt-scanner-app-small-business-2026",
    title: "Best Receipt Scanner App for Small Businesses in 2026",
    description: "An honest comparison of receipt scanner apps in 2026 and how to choose the right one for your small business workflow, budget, and tax goals.",
    featuredImage: "/landing/feature-blog-best-receipt-scanner-app-small-business-2026.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 8,
    tags: ["receipt scanner app", "small business", "expense tracking", "OCR", "tax prep"],
    tldr: "If you've ever Googled \"receipt scanner app\" and found yourself staring at a dozen options with no clear idea which one to choose, you're not alone.",
    body: [
      { kind: "p", text: "If you've ever Googled \"receipt scanner app\" and found yourself staring at a dozen options with no clear idea which one to choose, you're not alone." },
      { kind: "p", text: "The market is crowded. Some tools are built for large enterprise teams. Others are too basic to be useful. A few are just expensive spreadsheets with a camera button." },
      { kind: "p", text: "This guide cuts through the noise. We looked at the most popular options in 2026, compared them honestly, and broke down exactly who each one is best for so you can stop researching and start scanning." },
      { kind: "h2", text: "What to Look for in a Receipt Scanner App", id: "what-to-look-for-in-a-receipt-scanner-app" },
      { kind: "p", text: "Before you compare specific apps, it helps to know what actually matters. Not every feature on a spec sheet is worth paying for." },
      { kind: "p", text: "Here's what makes a real difference for small businesses:" },
      {
        kind: "ul",
        items: [
          "Accuracy of the scan — Can the app reliably read a crumpled or faded receipt? Poor OCR (text recognition) means more manual corrections, which defeats the purpose.",
          "Automatic categorization — Does the app sort your expenses into categories automatically, or do you have to do it yourself every time?",
          "Cloud storage — Are your receipts backed up securely so you can access them from any device, and never lose them?",
          "Export options — Can you share reports easily with your accountant or import into your accounting software?",
          "Price — Is the cost justified for a small operation, or are you paying for enterprise features you'll never use?",
        ],
      },
      { kind: "p", text: "With those criteria in mind, here's how the leading apps stack up." },
      { kind: "h3", text: "ReceiptCycle — Best for: Tax-focused simplicity", id: "receiptcycle-best-for-tax-focused-simplicity" },
      { kind: "p", text: "ReceiptCycle was built around one promise: scan once, claim your refund. For small business owners who want to capture every deductible expense without learning a complex piece of software, it's the most focused tool available." },
      { kind: "p", text: "The app scans receipts with your phone camera, automatically extracts the vendor, amount, date, and category, and stores everything in secure cloud storage. At tax time, you export a clean report and hand it to your accountant — or file it yourself." },
      { kind: "p", text: "What makes ReceiptCycle stand out is that it doesn't try to do everything. It does receipt capture and expense organization exceptionally well, and it keeps the experience simple enough that you'll actually use it consistently." },
      { kind: "p", text: "Best for: Freelancers, sole traders, small business owners who want a clean, affordable way to track expenses for tax purposes." },
      { kind: "h3", text: "Expensify — Best for: Larger teams with travel expense needs", id: "expensify-best-for-larger-teams" },
      { kind: "p", text: "Expensify is one of the most well-known names in expense management, and for good reason. It handles receipt scanning, mileage tracking, corporate card integration, and multi-level approval workflows — all under one roof." },
      { kind: "p", text: "The trade-off is complexity and cost. Expensify is designed for companies with teams of employees submitting expenses for approval. If you're a sole trader or a small operation with a handful of people, you'll likely find yourself paying for features you never touch." },
      { kind: "p", text: "Best for: Businesses with 10+ employees, frequent travelers, and teams that need structured approval workflows." },
      { kind: "h3", text: "Shoeboxed — Best for: Paper-heavy businesses", id: "shoeboxed-best-for-paper-heavy-businesses" },
      { kind: "p", text: "Shoeboxed takes a unique approach: you can mail your physical receipts to their processing center, and they'll scan and digitize them for you. It's a genuinely useful service for businesses that deal with large volumes of paper — construction, trades, retail." },
      { kind: "p", text: "The downside is that it's slower than scanning yourself, and the pricing gets steep as your volume increases." },
      { kind: "p", text: "Best for: Businesses that generate lots of paper receipts and want a hands-off approach to digitizing them." },
      { kind: "h3", text: "Wave — Best for: Free accounting with light receipt scanning", id: "wave-best-for-free-accounting" },
      { kind: "p", text: "Wave is primarily a free accounting platform, and receipt scanning is one of its supporting features. If you're already using Wave for invoicing or bookkeeping, the receipt scanning capability is a decent addition." },
      { kind: "p", text: "On its own, though, Wave's receipt features are more limited than dedicated apps. It's a good starting point for businesses just beginning to track expenses, but you may outgrow it quickly." },
      { kind: "p", text: "Best for: Sole traders and very small businesses already using Wave for accounting who want basic receipt capture." },
      { kind: "h2", text: "Quick Comparison: Which App Is Right for You?", id: "quick-comparison-which-app-is-right-for-you" },
      { kind: "h2", text: "So, Which One Should You Choose?", id: "so-which-one-should-you-choose" },
      { kind: "p", text: "Here's an honest way to think about it." },
      { kind: "p", text: "If you're running a small business, freelancing, or self-employed — and your main goal is to capture every receipt, stay organized, and make tax time less painful — ReceiptCycle is the right fit. It's built for exactly that job, it won't overwhelm you with features you don't need, and it's priced for businesses at your scale." },
      { kind: "p", text: "If you're managing a team of employees with complex expense workflows and corporate cards, Expensify may be worth the investment." },
      { kind: "p", text: "If you're buried in paper and the idea of scanning every receipt yourself sounds exhausting, Shoeboxed's mail-in service solves a real problem." },
      { kind: "p", text: "And if you're just getting started and want free tools to dip your toes in, Wave is a reasonable place to begin — just know you'll likely want something more focused as your business grows." },
      { kind: "p", text: "The best receipt scanner app isn't the one with the most features. It's the one you'll actually use every day. For most small business owners, that means something simple, fast, and purpose-built for staying tax-ready all year." },
      { kind: "h2", text: "Making the Switch Is Easier Than You Think", id: "making-the-switch-is-easier-than-you-think" },
      { kind: "p", text: "Switching from a shoebox — or no system at all — to a dedicated receipt scanner takes about five minutes. You download the app, scan your first receipt, and the system does the rest." },
      { kind: "p", text: "The real cost isn't the subscription. It's every deductible expense you've been missing because you had no consistent way to capture it." },
      { kind: "p", text: "Try ReceiptCycle free for 30 days and see what a difference an organized expense habit makes. No credit card required to get started." },
      { kind: "p", text: "The right tool, used consistently, makes tax time something you actually look forward to. Or at least something you stop dreading." },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Maximize tax refund by scanning receipts", href: "/blog/maximize-tax-refund-by-scanning-receipts" },
          { label: "Freelancer expense tracking guide", href: "/blog/freelancers-guide-tracking-business-expenses" },
          { label: "HMRC expenses and allowances", href: "https://www.gov.uk/expenses-if-youre-self-employed", external: true },
        ],
      },
    ],
  },
  {
    slug: "freelancers-guide-tracking-business-expenses",
    title: "The Freelancer's Complete Guide to Tracking Business Expenses",
    description: "A practical expense-tracking system for freelancers: what to deduct, what records to keep, and how to build a two-minute daily habit that saves money at tax time.",
    featuredImage: "/landing/feature-blog-freelancers-guide-tracking-business-expenses.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 10,
    tags: ["freelancer taxes", "business expenses", "receipt tracking", "schedule c", "bookkeeping"],
    tldr: "Here's something most freelancers figure out the hard way: the money you save on taxes is just as real as the money you earn from clients.",
    body: [
      { kind: "p", text: "Here's something most freelancers figure out the hard way: the money you save on taxes is just as real as the money you earn from clients." },
      { kind: "p", text: "You could land a great project this month, do excellent work, get paid on time, and then hand a bigger chunk than necessary back to the government in April, simply because you didn't keep track of what you spent to do that work." },
      { kind: "p", text: "Expense tracking isn't just an accounting task. For freelancers, it's one of the most direct ways to increase your take-home income without working an extra hour." },
      { kind: "p", text: "This guide will show you how to build a receipt habit that works, what you should be tracking, and how to set up ReceiptCycle so the whole process takes minutes a week instead of hours a month." },
      { kind: "h2", text: "Why Freelancers Overpay Taxes More Than Anyone Else", id: "why-freelancers-overpay-taxes-more-than-anyone-else" },
      { kind: "p", text: "When you work for an employer, someone else handles the complicated parts of your taxes. Deductions are applied automatically. Your W-2 arrives in January. You plug in the numbers, and you're done." },
      { kind: "p", text: "When you're freelancing, you're the employer and the employee. That means every deductible expense is your responsibility to claim — and if you don't, you don't get it back." },
      { kind: "p", text: "The IRS and most tax authorities allow self-employed people to deduct a wide range of legitimate business expenses from their taxable income. The catch is that you need to document them. No receipt, no deduction. And with no system to capture those receipts in real time, most freelancers end up filing with incomplete records and paying more tax than they should." },
      { kind: "p", text: "Studies consistently show that self-employed individuals leave thousands of dollars in deductions unclaimed each year, not because they didn't qualify, but because they couldn't prove they spent the money." },
      { kind: "h2", text: "What Counts as a Deductible Business Expense for Freelancers?", id: "what-counts-as-a-deductible-business-expense-for-freelancers" },
      { kind: "p", text: "The list is more generous than most people realise. If you spent money in the process of running your freelance business, there's a good chance it qualifies — at least in part." },
      { kind: "p", text: "Here are the most commonly overlooked categories:" },
      {
        kind: "ul",
        items: [
          "Home office. If you work from home and have a dedicated space — even a corner of a room used exclusively for work — you may be able to deduct a portion of your rent or mortgage, utilities, and internet.",
          "Software and subscriptions. Design tools, project management apps, accounting software, cloud storage, and stock photo subscriptions. If you use it for work, track it.",
          "Hardware and equipment. Laptops, monitors, cameras, microphones, and keyboards. The percentage of time you use equipment for work versus personal use matters, but work-related use is deductible.",
          "Professional development. Online courses, books, industry memberships, conference tickets. Staying sharp in your field is a legitimate business expense.",
          "Client meals and entertainment. If you take a client to lunch or meet someone for coffee to discuss a project, that expense is typically 50% deductible. Keep the receipt and note who you met with.",
          "Travel. If you travel for work to meet clients, attend events, or complete a project, flights, accommodation, and transport are deductible. Even the miles you drive to a client meeting add up.",
          "Phone and internet. You can deduct the portion of your phone and internet bill that you use for business. Estimate honestly, and document the basis for your estimate.",
        ],
      },
      { kind: "h2", text: "How to Build a Receipt Habit That Takes 2 Minutes a Day", id: "how-to-build-a-receipt-habit-that-takes-2-minutes-a-day" },
      { kind: "p", text: "The biggest barrier to expense tracking isn't complexity — it's consistency. Most freelancers start strong in January and fade out by March." },
      { kind: "p", text: "The secret is making the habit as frictionless as possible." },
      { kind: "p", text: "Here's a simple system that works:" },
      { kind: "h3", text: "Step 1: Scan instantly", id: "freelancer-step-1-scan-instantly" },
      { kind: "p", text: "Scan the receipt the moment you get it. Don't wait until you get home. Don't stack them on your desk to deal with later. Open ReceiptCycle, take a photo of the receipt before you pocket it, and you're done. The whole thing takes ten seconds." },
      { kind: "h3", text: "Step 2: Keep categories consistent", id: "freelancer-step-2-keep-categories-consistent" },
      { kind: "p", text: "Keep your categories consistent. ReceiptCycle auto-categorizes most expenses, but it helps to use the same categories throughout the year. If you call it \"software\" in January, call it \"software\" in October. Consistency makes your year-end report much easier to read." },
      { kind: "h3", text: "Step 3: Weekly five-minute review", id: "freelancer-step-3-weekly-review" },
      { kind: "p", text: "Do a five-minute weekly review. Once a week — Friday afternoon works well — open the app and scroll through what you captured. Check that the amounts look right and the categories make sense. Catching a misread receipt takes thirty seconds. Catching twelve of them in December takes an afternoon." },
      { kind: "h3", text: "Step 4: Forward digital receipts", id: "freelancer-step-4-forward-digital-receipts" },
      { kind: "p", text: "Forward digital receipts immediately. For online purchases, email confirmations, and subscription renewals, ReceiptCycle lets you forward receipts directly to a dedicated email address. They're processed automatically, so you never have to think about them." },
      { kind: "p", text: "That's the whole system. Four steps. No spreadsheets. No end-of-year chaos." },
      { kind: "h2", text: "Setting Up ReceiptCycle for Freelance Expense Tracking", id: "setting-up-receiptcycle-for-freelance-expense-tracking" },
      { kind: "p", text: "Getting started takes about five minutes." },
      { kind: "p", text: "Download the app and create your account. During setup, you can choose categories that reflect your freelance work — feel free to customize them. The default categories cover most common freelance expenses, but you might want to add specific ones for your industry." },
      { kind: "p", text: "From there, the workflow is simple: scan, confirm, move on. The app reads the key information from each receipt automatically. You review it, adjust the category if needed, and save." },
      { kind: "p", text: "At any point during the year, you can pull up a dashboard showing your total expenses by category, your spending trends over time, and any receipts that might need attention. When tax season arrives, you export the report in whatever format your accountant prefers — PDF or CSV — and share it directly from the app." },
      { kind: "h2", text: "How to Generate an Expense Report for Your Accountant", id: "how-to-generate-an-expense-report-for-your-accountant" },
      { kind: "p", text: "One of the most appreciated things you can do for your accountant — and for yourself — is arrive at tax time with organized records." },
      { kind: "p", text: "ReceiptCycle generates a complete expense report with one tap. The report includes:" },
      { kind: "h3", text: "What your report should include", id: "freelancer-report-should-include" },
      {
        kind: "ul",
        items: [
          "Every captured receipt with a digital image",
          "Vendor name, date, amount, and category for each expense",
          "Subtotals by category for the period you select",
          "A summary of total deductible expenses",
        ],
      },
      { kind: "p", text: "Export it as a PDF to share directly, or as a CSV if your accountant wants to import it into their own software. Either way, you walk into the conversation prepared — which typically means a shorter meeting and a bigger refund." },
      { kind: "h2", text: "End-of-Year Checklist: Receipts Every Freelancer Should Have", id: "end-of-year-checklist-receipts-every-freelancer-should-have" },
      { kind: "p", text: "Before you file, run through this list and make sure you have documentation for each category that applies to you:" },
      { kind: "p", text: "Home office expenses (rent/mortgage portion, utilities, internet)" },
      { kind: "p", text: "All software and app subscriptions for the year" },
      { kind: "p", text: "Hardware or equipment purchased for work" },
      { kind: "p", text: "Professional development — courses, books, events" },
      { kind: "p", text: "Client meals and the names of who you met with" },
      { kind: "p", text: "Business travel — flights, hotels, transport, mileage" },
      { kind: "p", text: "Phone bill (business-use portion)" },
      { kind: "p", text: "Any professional services — accountants, lawyers, contractors" },
      { kind: "p", text: "If you've been scanning consistently throughout the year, most of this is already organized in ReceiptCycle. The checklist is just a final sweep to make sure nothing slipped through." },
      { kind: "p", text: "ReceiptCycle exists to make sure you never leave that money behind. Start tracking your freelance expenses free today — and go into your next tax filing knowing you claimed every dollar you earned." },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Best receipt scanner app for small business", href: "/blog/best-receipt-scanner-app-small-business-2026" },
          { label: "Go paperless with receipts", href: "/blog/go-paperless-with-receipts" },
          { label: "Schedule C instructions (IRS)", href: "https://www.irs.gov/forms-pubs/about-schedule-c-form-1040", external: true },
        ],
      },
    ],
  },
  {
    slug: "go-paperless-with-receipts",
    title: "How to Go Paperless With Your Receipts (And Never Lose One Again)",
    description: "Paper receipts fade and disappear. Learn the legal, practical, and technical workflow for moving to secure digital receipts with zero tax-season chaos.",
    featuredImage: "/landing/feature-blog-go-paperless-with-receipts.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 9,
    tags: ["paperless receipts", "digital receipts", "tax records", "cloud backup", "OCR"],
    tldr: "Picture this: it's the week before your tax deadline. You're sitting at the kitchen table surrounded by a pile of receipts, some faded, some torn, one that's been through the wash.",
    body: [
      { kind: "p", text: "Picture this: it's the week before your tax deadline. You're sitting at the kitchen table surrounded by a pile of receipts, some faded, some torn, one that's been through the wash." },
      { kind: "p", text: "You're squinting at a thermal slip trying to read whether that charge was $14 or $44, and you're pretty sure you've lost the receipt for the biggest business purchase you made all year." },
      { kind: "p", text: "Sound familiar? You're in good company. But it doesn't have to be this way." },
      { kind: "p", text: "Going paperless with your receipts is simpler than most people expect, and the payoff is less stress, better records, and a bigger tax refund, making it one of the smartest financial habits you can build." },
      { kind: "h2", text: "The Real Cost of Losing a Receipt", id: "the-real-cost-of-losing-a-receipt" },
      { kind: "p", text: "Most people think of a lost receipt as a minor inconvenience. In reality, it has a direct financial cost." },
      { kind: "p", text: "Every receipt you can't produce at tax time is a deduction you can't claim. At an average tax rate of 22–25%, a $200 expense you can't document costs you $44 to $50 in unclaimed refund money. Lose ten receipts like that across a year, and you've given back $400 to $500 that was rightfully yours." },
      { kind: "p", text: "There's also the audit risk. If the IRS or your tax authority questions a deduction and you can't produce the receipt, the deduction is typically disallowed — and you may face penalties on top. Digital records that are well-organized and date-stamped are actually stronger evidence than crumpled paper, because they're harder to fabricate or alter after the fact." },
      { kind: "p", text: "Going paperless isn't just tidier. It's financially smarter." },
      { kind: "h2", text: "Are Digital Receipts Legally Valid?", id: "are-digital-receipts-legally-valid" },
      { kind: "p", text: "This is the question most people ask first, and the answer is a clear yes." },
      { kind: "p", text: "The IRS has explicitly accepted digital images of receipts as valid documentation since Revenue Procedure 98-25 — which means this has been settled policy for over 25 years. You are not required to keep paper originals as long as your digital records are legible, accurate, and include the key details: vendor name, date, amount, and the nature of the purchase." },
      { kind: "p", text: "The same is true in the UK under HMRC guidance, in Canada under CRA rules, and in most other major tax jurisdictions around the world." },
      { kind: "p", text: "What matters is the quality of your records, not the format they're stored in. A clear phone photo of a receipt, properly organized and backed up, meets the standard." },
      { kind: "h2", text: "Step 1: Scan Every Receipt the Moment You Get It", id: "step-1-scan-every-receipt-the-moment-you-get-it" },
      { kind: "p", text: "This is the step that makes or breaks the whole system." },
      { kind: "p", text: "The temptation is to save receipts and scan them in batches later. The problem is that \"later\" becomes the weekend, the weekend becomes the end of the month, and by then receipts are lost, faded, or stuffed in three different pockets of three different jackets." },
      { kind: "p", text: "The most effective approach is also the simplest: scan immediately." },
      { kind: "p", text: "When you get a receipt — at a restaurant, a store, a gas station — open ReceiptCycle before you put the receipt away and take a photo. The app reads the information automatically. The whole process takes about ten seconds." },
      { kind: "p", text: "Ten seconds at the moment of purchase beats thirty minutes of frustrating receipt archaeology at the end of the month." },
      { kind: "h2", text: "Step 2: Let ReceiptCycle Categorize and Organize", id: "step-2-let-receiptcycle-categorize-and-organize" },
      { kind: "p", text: "Once you scan a receipt, ReceiptCycle's AI does the rest." },
      { kind: "p", text: "It reads the vendor name, transaction date, total amount, and any tax details from the image, then assigns the expense to a category automatically. You can review the result, adjust the category if needed, and move on." },
      { kind: "p", text: "Over time, the system learns your patterns. If you always categorize receipts from the same coffee shop as \"client meals,\" it will start doing that automatically." },
      { kind: "p", text: "The result is an organized expense log that builds itself throughout the year. By the time you need it for tax purposes, the work is already done." },
      { kind: "h2", text: "Step 3: Store in the Cloud — Access Anywhere, Any Time", id: "step-3-store-in-the-cloud-access-anywhere-any-time" },
      { kind: "p", text: "One of the biggest advantages of digital receipts over paper is that they live in the cloud, not in your desk drawer." },
      { kind: "p", text: "ReceiptCycle stores every scan securely in encrypted cloud storage. That means:" },
      {
        kind: "ul",
        items: [
          "You can't lose your records — a lost phone, a flooded office, or a fire won't erase your receipt archive.",
          "You can access them from any device — pull up a receipt on your laptop, tablet, or a colleague's phone when you need it.",
          "You can share directly with accountants — export a report or grant read access without printing or emailing attachments.",
        ],
      },
      { kind: "p", text: "Cloud storage also means your records are automatically backed up. There's no \"I think I saved that file\" — it's just there, whenever you need it." },
      { kind: "h2", text: "How Long Should You Keep Digital Receipts?", id: "how-long-should-you-keep-digital-receipts" },
      { kind: "p", text: "The general rule in the US is to keep tax-related records for three years from the date you filed your return. That covers the standard IRS audit window." },
      { kind: "h3", text: "Exceptions worth knowing", id: "paperless-exceptions-worth-knowing" },
      {
        kind: "ul",
        items: [
          "If you underreported income by more than 25%, the IRS has six years to audit.",
          "For employment tax records, keep records for at least four years.",
          "If you file a claim for a loss, you may need records going back further.",
        ],
      },
      { kind: "p", text: "Because ReceiptCycle stores your scans indefinitely in the cloud, you don't need to actively manage this. Your records are there when you need them, for as long as you need them. You can also export and download a full archive at any point if you want a local backup." },
      { kind: "h2", text: "FAQ: 5 Common Questions About Digital Receipts", id: "faq-5-common-questions-about-digital-receipts" },
      { kind: "h3", text: "Can I throw away paper receipts after scanning them?", id: "can-i-throw-away-paper-receipts-after-scanning-them" },
      { kind: "p", text: "Yes, in most cases. Once you've scanned a receipt and confirmed the image is clear and complete, the paper original serves no additional purpose from a tax or legal standpoint. The digital copy is your record." },
      { kind: "h3", text: "What if the scan is blurry or the text is hard to read?", id: "what-if-the-scan-is-blurry-or-the-text-is-hard-to-read" },
      { kind: "p", text: "ReceiptCycle will flag receipts where it can't extract information reliably. Retake the photo in better light, or manually enter the details. The app prompts you before saving an incomplete record." },
      { kind: "h3", text: "Does this work for email receipts and digital purchases?", id: "does-this-work-for-email-receipts-and-digital-purchases" },
      { kind: "p", text: "Yes. For online orders, subscription renewals, or any purchase where the receipt arrives by email, you can forward it to your dedicated ReceiptCycle address and it's processed automatically — no scanning required." },
      { kind: "h3", text: "What about receipts in foreign currencies?", id: "what-about-receipts-in-foreign-currencies" },
      { kind: "p", text: "ReceiptCycle supports multiple currencies and handles the conversion automatically based on the transaction date. Useful for business travel or international purchases." },
      { kind: "h3", text: "Is my financial data safe in the cloud?", id: "is-my-financial-data-safe-in-the-cloud" },
      { kind: "p", text: "ReceiptCycle uses bank-level encryption to protect your records. Your data is stored securely and only accessible to you — or anyone you explicitly choose to share it with." },
      { kind: "h2", text: "Make the Switch Today", id: "make-the-switch-today" },
      { kind: "p", text: "Going paperless with your receipts doesn't require a big system overhaul or a weekend of setup. It requires one decision: the next time you get a receipt, scan it instead of pocketing it." },
      { kind: "p", text: "That single shift, applied consistently, transforms how you handle expenses. No more lost deductions. No more tax-time stress. No more guessing whether you have the documentation you need." },
      { kind: "p", text: "ReceiptCycle makes it easy to start. Scan your first receipt free — in about thirty seconds — and see how quickly an organized digital system starts to feel natural." },
      { kind: "p", text: "Paper receipts were always a temporary solution. A permanent digital record is simply better in every way that matters." },
      {
        kind: "links",
        title: "Helpful resources",
        items: [
          { label: "Maximize your tax refund by scanning receipts", href: "/blog/maximize-tax-refund-by-scanning-receipts" },
          { label: "Gig worker expense guide", href: "/blog/gig-workers-income-expense-guide" },
          { label: "IRS Rev. Proc. 98-25", href: "https://www.irs.gov/pub/irs-drop/rp-97-22.pdf", external: true },
        ],
      },
    ],
  },
  {
    slug: "gig-workers-income-expense-guide",
    title: "Receipt Tracking for Uber, DoorDash & Gig Workers Income and Expense Guide",
    description: "A full expense and receipt guide for gig workers: what to deduct, what proof to keep, and how to avoid leaving $500-$2,000 in deductions unclaimed.",
    featuredImage: "/landing/feature-blog-gig-workers-income-expense-guide.png?v=10",
    datePublished: "2026-04-17",
    dateModified: "2026-04-18",
    author: "Receipt Cycle Team",
    readMinutes: 11,
    tags: ["gig worker taxes", "uber deductions", "doordash expenses", "receipt tracking", "schedule c"],
    tldr: "If you drive for Uber, deliver for DoorDash, run errands for Instacart, or pick up gig work on any platform, you're running a small business even if it doesn't feel like one.",
    body: [
      { kind: "p", text: "If you drive for Uber, deliver for DoorDash, run errands for Instacart, or pick up gig work on any platform, you're running a small business even if it doesn't feel like one." },
      { kind: "p", text: "And like any business, you have expenses. Gas. Car maintenance. Your phone. Tolls. Insurance. Every time you pay for something that makes your work possible, that's a potential tax deduction." },
      { kind: "p", text: "The problem is, most gig workers never claim all of them not because they don't qualify, but because they didn't keep the receipts to prove it." },
      { kind: "p", text: "This guide will show you exactly what you can deduct, why gig workers leave so much money unclaimed, and how to build a simple receipt habit with ReceiptCycle that takes seconds between rides not hours at the end of the year." },
      { kind: "h2", text: "What Expenses Can Gig Drivers Deduct? (The Full List)", id: "what-expenses-can-gig-drivers-deduct-the-full-list" },
      { kind: "p", text: "As an independent contractor, which is what you are when you work for a gig platform, you can deduct the ordinary and necessary costs of running your work. Here's what that looks like in practice:" },
      { kind: "h3", text: "Fuel and vehicle costs", id: "gig-fuel-and-vehicle-costs" },
      { kind: "p", text: "Gas and fuel. This is the obvious one. Every gallon you buy to do your work is a deductible expense. Keep every fuel receipt, every time." },
      { kind: "p", text: "Vehicle maintenance. Oil changes, tire rotations, brake pads, new wipers — the wear and tear on your car from gig work is a legitimate business cost. If your car needs a repair and you use it for work, a portion of that repair is deductible." },
      { kind: "p", text: "Car insurance. If you use your personal vehicle for gig work, a portion of your insurance premium may be deductible, proportional to your business use of the vehicle." },
      { kind: "h3", text: "Phone and tools", id: "gig-phone-and-tools" },
      { kind: "p", text: "Your phone. You literally can't do gig work without your phone. The business-use portion of your phone bill — and potentially the cost of the phone itself if you bought it primarily for work — is deductible." },
      { kind: "p", text: "Phone accessories. A car mount for navigation, a charger cable, a wireless charger for between rides. These are small purchases, but they add up, and they're all deductible." },
      { kind: "h3", text: "Road and platform costs", id: "gig-road-and-platform-costs" },
      { kind: "p", text: "Tolls and parking. If you pay tolls during work trips or need to park while making a delivery, those costs are deductible. Save those receipts — they're easy to forget." },
      { kind: "p", text: "Bags, coolers, and equipment. DoorDash and Instacart drivers who buy insulated bags or equipment to do their jobs better can deduct those costs." },
      { kind: "p", text: "Platform fees and commissions. The percentage the platform takes from your earnings is also a deductible expense — it's a cost of doing business." },
      { kind: "h2", text: "Why Gig Workers Miss $500–$2,000 in Deductions Every Year", id: "why-gig-workers-miss-500-2-000-in-deductions-every-year" },
      { kind: "p", text: "Here's the honest answer: gig work is fast-paced and transactional. You're focused on the next ride, the next delivery, the next pickup. Stopping to track a receipt feels like friction in the middle of a busy day." },
      { kind: "p", text: "So receipts don't get kept. Small purchases get forgotten. By the end of the year, the only expenses most gig workers can document with certainty are the ones from their bank statements — and bank statements alone don't always have the detail the IRS needs." },
      { kind: "p", text: "The result? Conservative deductions. Larger tax bills. Money left behind." },
      { kind: "p", text: "According to tax professionals who work with gig economy workers, the average driver who actively tracks expenses claims $1,200 to $2,500 more in deductions than one who doesn't. At a 22% tax rate, that's $264 to $550 back in your pocket — just for keeping receipts." },
      { kind: "p", text: "The habit is worth building." },
      { kind: "h2", text: "How to Track Receipts Between Rides", id: "how-to-track-receipts-between-rides" },
      { kind: "p", text: "The key is making the habit fit into your workflow, not the other way around. Here's what works for drivers and delivery workers:" },
      { kind: "h3", text: "At the gas station", id: "gig-at-the-gas-station" },
      { kind: "p", text: "At the gas station: Before you pull back onto the road, open ReceiptCycle and snap the fuel receipt. It takes eight seconds. The app reads the amount, date, and vendor automatically and saves it to your expense log." },
      { kind: "h3", text: "After maintenance appointments", id: "gig-after-maintenance" },
      { kind: "p", text: "After maintenance appointments: When the mechanic hands you the receipt, scan it before you leave the parking lot. For larger expenses like an oil change or new tires, this is especially important — these are the deductions that make the biggest difference." },
      { kind: "h3", text: "For tolls", id: "gig-for-tolls" },
      { kind: "p", text: "For tolls: If you pay with cash, keep the ticket and scan it at the end of your shift. If you use an electronic toll account, you can download your statement monthly and forward the PDF to your ReceiptCycle account." },
      { kind: "h3", text: "For online purchases", id: "gig-for-online-purchases" },
      { kind: "p", text: "For online purchases: When you order supplies — bags, mounts, accessories — forward the email confirmation to your ReceiptCycle address and it's processed automatically." },
      { kind: "p", text: "The goal isn't perfection. It's consistency. A scan rate of 80–90% is dramatically better than the zero-percent approach most gig workers currently use." },
      { kind: "h2", text: "Setting Up a Weekly Expense Habit as a Driver", id: "setting-up-a-weekly-expense-habit-as-a-driver" },
      { kind: "p", text: "Daily scanning handles the capture. A weekly five-minute review handles the organization." },
      { kind: "p", text: "Pick a time — Sunday evening, Friday after your last shift, whenever works — and spend five minutes in the app. Check that the week's receipts were scanned correctly. Make sure the categories are right. Note any purchases you might have missed." },
      { kind: "p", text: "That's it. Five minutes a week keeps your records current and accurate all year, so January isn't a scramble." },
      { kind: "p", text: "At the end of the year, ReceiptCycle generates a complete expense report: every receipt, organized by category, with totals and subtotals. You hand it to your tax preparer — or use it yourself if you file independently — and you're done." },
      { kind: "h2", text: "How to Export Your Expenses for Tax Filing", id: "how-to-export-your-expenses-for-tax-filing" },
      { kind: "p", text: "When tax season arrives, you'll need to report your business income and deductions on Schedule C (if you're in the US). ReceiptCycle makes that straightforward." },
      { kind: "p", text: "From the app, select the date range for the tax year. Choose to export as a PDF (clean and readable, great for sharing with a tax preparer) or CSV (importable into spreadsheet software or tax tools). The report includes every expense, the category it belongs to, and the total by category — which maps directly to the line items on Schedule C." },
      { kind: "p", text: "If you work with a tax professional, you can share the report directly from the app. If you file yourself using software like TurboTax or H&R Block, the categorized totals give you exactly what you need to fill in each deduction line." },
      { kind: "h2", text: "FAQ: What If I Didn't Keep Receipts?", id: "faq-what-if-i-didn-t-keep-receipts" },
      { kind: "h3", text: "Do I need a receipt for every single deduction?", id: "do-i-need-a-receipt-for-every-single-deduction" },
      { kind: "p", text: "The IRS requires receipts for most business expenses, particularly those over $75. For smaller expenses, a contemporaneous record — a note in an app with the date, amount, and purpose — may be sufficient. That said, a receipt is always better than a note." },
      { kind: "h3", text: "What if I lost receipts from earlier this year?", id: "what-if-i-lost-receipts-from-earlier-this-year" },
      { kind: "p", text: "Start now. You can't recover receipts you've lost, but every receipt you capture from today forward counts. Even a partial year of organized records is significantly better than none — and it sets you up for a complete year next year." },
      { kind: "h3", text: "Can I deduct the mileage instead of actual car expenses?", id: "can-i-deduct-the-mileage-instead-of-actual-car-expenses" },
      { kind: "p", text: "Yes. The IRS offers a standard mileage rate as an alternative to tracking actual vehicle expenses. In 2024, that rate was 67 cents per mile for business driving. You can choose whichever method results in a larger deduction — but you can't use both. ReceiptCycle tracks your non-mileage expenses, so you can calculate both methods and pick the better one." },
      { kind: "h3", text: "What if I use my car for both work and personal trips?", id: "what-if-i-use-my-car-for-both-work-and-personal-trips" },
      { kind: "p", text: "Only the business-use percentage of vehicle expenses is deductible. If you use your car 60% for gig work and 40% personally, you can deduct 60% of eligible vehicle costs. Keep a mileage log alongside your receipts to support that calculation." },
      { kind: "h2", text: "Stop Leaving Money on the Road", id: "stop-leaving-money-on-the-road" },
      { kind: "p", text: "You work hard for every dollar you earn on the platform. It makes no sense to hand more of it back to the IRS than you're legally required to." },
      { kind: "p", text: "A simple receipt habit — ten seconds at the gas pump, five minutes on Sunday evening — can recover hundreds or thousands of dollars in deductions you're already entitled to. You just need the system to capture them." },
      { kind: "p", text: "ReceiptCycle is built for exactly this. Download it free, scan your next fuel receipt, and start the habit today." },
      { kind: "p", text: "The deductions are there. The only question is whether you have the receipts to claim them." },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Freelancer expense tracking guide", href: "/blog/freelancers-guide-tracking-business-expenses" },
          { label: "Go paperless with receipts", href: "/blog/go-paperless-with-receipts" },
          { label: "IRS mileage rates", href: "https://www.irs.gov/tax-professionals/standard-mileage-rates", external: true },
        ],
      },
    ],
  },
  {
    slug: "scan-receipts-for-tax-refund",
    title: "Scan Receipts for Your Tax Refund: A Practical Capture Checklist",
    description:
      "A fast checklist for turning everyday purchases into defensible tax records: what to capture, how to name categories, and how to export without last-minute chaos.",
    featuredImage: "/landing/feature-blog-scan-receipts-for-tax-refund.png?v=10",
    datePublished: "2026-04-12",
    dateModified: "2026-04-20",
    author: "Receipt Cycle Team",
    readMinutes: 7,
    tags: ["tax receipts", "digital records", "self-employed", "audit trail", "OCR"],
    tldr: "Your refund is only as strong as your proof. Scanning receipts at the moment of purchase is the smallest habit that prevents the biggest tax-season regrets.",
    body: [
      { kind: "p", text: "Tax refunds feel mysterious, but the math is simple: legitimate expenses you can document reduce taxable income. The failure mode is almost never \"I didn't spend the money\" — it's \"I can't prove it.\"" },
      { kind: "p", text: "This checklist is designed for busy people: freelancers, side-hustlers, and small-business owners who want audit-ready records without living in spreadsheets." },
      { kind: "h2", text: "The 30-second capture rule", id: "the-30-second-capture-rule" },
      { kind: "p", text: "If a receipt takes more than half a minute to save, you will not keep the habit. The goal is one motion: open your scanner, photograph the receipt, confirm the extracted merchant and total, done." },
      { kind: "h2", text: "What a \"good enough\" digital receipt contains", id: "what-a-good-enough-digital-receipt-contains" },
      {
        kind: "ul",
        items: [
          "Merchant or payee name",
          "Transaction date",
          "Total paid (and tax line if shown)",
          "Payment method hint when available (card last four, cash, etc.)",
          "A category that matches how you file (not how the store markets itself)",
        ],
      },
      { kind: "h2", text: "Categories that survive an accountant review", id: "categories-that-survive-an-accountant-review" },
      { kind: "p", text: "Consistency beats creativity. Pick a small set of categories and reuse them all year: travel, meals, software, office, vehicle, professional services. When in doubt, add a one-line note in the memo field while the memory is fresh." },
      { kind: "h2", text: "Email and PDF receipts count too", id: "email-and-pdf-receipts-count-too" },
      { kind: "p", text: "Subscriptions, SaaS renewals, and online orders often never produce paper. Forward the confirmation email or upload the PDF the same day. Mixed evidence is fine as long as it is complete." },
      { kind: "h2", text: "Export early, export often", id: "export-early-export-often" },
      { kind: "p", text: "Do not wait until April to discover gaps. Once a quarter, export your categorized ledger and skim for missing months, unnamed merchants, and \"uncategorized\" buckets. Fixing a quarter takes minutes; fixing a year takes weekends." },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Deep dive: maximize your tax refund with receipts", href: "/blog/maximize-tax-refund-by-scanning-receipts" },
          { label: "Go paperless with receipts", href: "/blog/go-paperless-with-receipts" },
          { label: "IRS recordkeeping basics", href: "https://www.irs.gov/businesses/small-businesses-self-employed/what-kind-of-records-should-i-keep", external: true },
        ],
      },
    ],
  },
  {
    slug: "best-expense-tracker-for-freelancers",
    title: "Best Expense Tracker for Freelancers in 2026 (What Actually Matters)",
    description:
      "Freelancers need capture-first workflows, not bloated accounting suites. Here is how to evaluate expense trackers for real-world use: speed, accuracy, exports, and privacy.",
    featuredImage: "/landing/feature-blog-best-expense-tracker-for-freelancers.png?v=10",
    datePublished: "2026-04-14",
    dateModified: "2026-04-20",
    author: "Receipt Cycle Team",
    readMinutes: 8,
    tags: ["freelancer", "expense tracker", "receipt app", "self-employed", "CSV export"],
    tldr: "The best tracker is the one you open weekly. Prioritize frictionless capture, honest categorization, and exports your accountant can read without a translation layer.",
    body: [
      { kind: "p", text: "Freelancers do not fail at expense tracking because they lack discipline. They fail because the tool asks for accounting expertise at 9pm after a client call." },
      { kind: "h2", text: "Must-haves for freelance workflows", id: "must-haves-for-freelance-workflows" },
      {
        kind: "ul",
        items: [
          "Mobile receipt capture with reliable OCR",
          "Voice or sentence-based entry for parking-lot moments",
          "Bank or card CSV/PDF import for the transactions you did not photograph",
          "Per-workspace separation if you mix personal and business cards",
          "CSV or PDF export with category subtotals",
        ],
      },
      { kind: "h2", text: "Nice-to-haves that move the needle", id: "nice-to-haves-that-move-the-needle" },
      { kind: "ul", items: ["Duplicate charge alerts", "Subscription cadence warnings", "Multi-currency support for travel", "Encrypted cloud backup you control"] },
      { kind: "h2", text: "Red flags in \"free\" trackers", id: "red-flags-in-free-trackers" },
      { kind: "p", text: "If the business model is selling your purchase graph, the incentives are wrong. Prefer products that charge a transparent subscription and keep the ledger yours." },
      { kind: "h2", text: "How Receipt Cycle fits freelancers", id: "how-receipt-cycle-fits-freelancers" },
      { kind: "p", text: "Receipt Cycle is built around capture truth fast: scan, speak, import, then review in short weekly bursts. The objective is a defensible ledger without turning you into a part-time bookkeeper." },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Freelancer expense tracking playbook", href: "/blog/freelancers-guide-tracking-business-expenses" },
          { label: "Receipt scanner apps compared", href: "/blog/best-receipt-scanner-app-small-business-2026" },
          { label: "HMRC self-employed expenses (UK)", href: "https://www.gov.uk/expenses-if-youre-self-employed", external: true },
        ],
      },
    ],
  },
  {
    slug: "catch-subscription-creep",
    title: "Catch Subscription Creep Before It Quietly Drains Your Business",
    description:
      "Micro-subscriptions and annual renewals add up. Learn how to detect duplicate charges, zombie trials, and price hikes using receipts plus statement cross-checks.",
    featuredImage: "/landing/feature-blog-catch-subscription-creep.png?v=10",
    datePublished: "2026-04-16",
    dateModified: "2026-04-20",
    author: "Receipt Cycle Team",
    readMinutes: 7,
    tags: ["subscriptions", "money leaks", "duplicate charges", "SaaS", "cash flow"],
    tldr: "Creep is slow by design. The defense is boring and effective: capture renewals, reconcile against card charges monthly, and cancel what you forgot you still pay for.",
    body: [
      { kind: "p", text: "Subscription creep rarely shows up as one giant line item. It shows up as five $12 charges, two $39 renewals, and an annual $199 you meant to cancel last quarter." },
      { kind: "h2", text: "The three kinds of creep", id: "the-three-kinds-of-creep" },
      {
        kind: "ul",
        items: [
          "Price hikes on the same SKU (same merchant, higher amount)",
          "Duplicate billing (two charges for the same renewal window)",
          "Zombie trials (a card on file you forgot after the trial ended)",
        ],
      },
      { kind: "h2", text: "A monthly 15-minute review", id: "a-monthly-15-minute-review" },
      { kind: "p", text: "Pick a recurring calendar slot. Sort last month's charges by merchant. Anything unfamiliar gets a 60-second search: what is this, do I still use it, is the amount expected?" },
      { kind: "h2", text: "Why receipts still matter for digital subscriptions", id: "why-receipts-still-matter-for-digital-subscriptions" },
      { kind: "p", text: "Email receipts often include plan tier and renewal period. That context is what lets you prove you canceled — or negotiate a refund — when the card statement only shows a generic processor name." },
      { kind: "h2", text: "When to cancel vs downgrade", id: "when-to-cancel-vs-downgrade" },
      { kind: "p", text: "If you have not logged in for 60 days, cancel. If you use the product rarely, downgrade to the smallest tier that keeps your data. Creep survives on \"I might need it someday.\"" },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Gig worker expense guide", href: "/blog/gig-workers-income-expense-guide" },
          { label: "Import statements into one ledger", href: "/blog/import-bank-statements-expense-tracking" },
          { label: "FTC subscription billing basics", href: "https://www.ftc.gov/business-guidance/resources/negative-option-marketing", external: true },
        ],
      },
    ],
  },
  {
    slug: "import-bank-statements-expense-tracking",
    title: "Import Bank Statements for Expense Tracking (Without Duplicate Chaos)",
    description:
      "CSV and PDF statements help you backfill history — if you dedupe and reconcile. Here is a sane workflow for merging imports with receipt scans.",
    featuredImage: "/landing/feature-blog-import-bank-statements-expense-tracking.png?v=10",
    datePublished: "2026-04-18",
    dateModified: "2026-04-20",
    author: "Receipt Cycle Team",
    readMinutes: 8,
    tags: ["bank import", "CSV", "PDF", "deduplication", "bookkeeping"],
    tldr: "Imports buy speed; receipts buy proof. The winning workflow links both: import for coverage, scan for documentation, reconcile once a week.",
    body: [
      { kind: "p", text: "Imports shine when you have months of history and no shoebox. They fail when you create three copies of the same latte because CSV, Apple Pay, and a receipt all entered separately." },
      { kind: "h2", text: "Start with a date range, not \"all time\"", id: "start-with-a-date-range-not-all-time" },
      { kind: "p", text: "Import one month, reconcile it, then move forward. Backfilling everything at once is how duplicates hide until tax season." },
      { kind: "h2", text: "Deduping rules that work in the real world", id: "deduping-rules-that-work-in-the-real-world" },
      {
        kind: "ul",
        items: [
          "Same date + same amount + same merchant → likely duplicate",
          "Card pending vs posted charges → wait 48 hours before merging",
          "Cash tips and P2P transfers → keep a memo; they rarely have receipts",
        ],
      },
      { kind: "h2", text: "When to attach a receipt anyway", id: "when-to-attach-a-receipt-anyway" },
      { kind: "p", text: "Bank lines prove cash moved. Receipts prove what you bought. Meals, travel, equipment, and anything an auditor might question should have both." },
      { kind: "h2", text: "Weekly reconciliation beats heroic December", id: "weekly-reconciliation-beats-heroic-december" },
      { kind: "p", text: "Spend ten minutes Friday: fix categories, merge duplicates, flag missing receipts for the week's largest charges. That rhythm keeps imports trustworthy." },
      {
        kind: "links",
        title: "Related reading",
        items: [
          { label: "Go paperless with receipts", href: "/blog/go-paperless-with-receipts" },
          { label: "Catch subscription creep", href: "/blog/catch-subscription-creep" },
          { label: "OFX home banking format (reference)", href: "https://financialdataexchange.org/", external: true },
        ],
      },
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
