// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkbbupvauzmrvgpvkdlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrYmJ1cHZhdXptcnZncHZrZGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2MTI3NjgsImV4cCI6MjA4NDE4ODc2OH0.uLpA_eC8JQGFPZpz1vjSYB4NZocSF3JMq9bN95thDXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});